/**
 * Plura P ADMIN Javascript Framework [http://plura.pt]
 * 
 * Copyright (c) 2014 Plura
 *
 * Date: 2014-01-13 12:00:00 (Mon, 13 Jan 2014)
 * Revision: 6246
 */
var plura=plura||{};plura.admin=plura.admin||{};plura.admin.common=plura.admin.common||{};plura.admin.common.Trigger=function(e){var d,b,a,c=function(a){(d=a)?b.removeClass("off").addClass("on"):b.removeClass("on").addClass("off")};this.on=c;a=$.extend(!0,{},{on:!0,data:null},e);this.core=b=$("<div/>").addClass("trigger").text("X").appendTo(a.target).click(function(e){e.stopPropagation();d&&(b.trigger("TRIGGER",a.data),c(!1))});c(a.on);return this};plura=plura||{};plura.admin=plura.admin||{};
plura.admin.Confirm=function(e){var d,b,a,c,l,k=function(a,g,e){a?(b.on("click",function(a){g();k(!1)}),c.text(e||l.labels.alert),d.fadeIn()):(b.off("click"),d.fadeOut())},g=function(){d.width($(window).width()).height($(window).height());a.css({marginLeft:-a.outerWidth()/2,marginTop:-a.outerHeight()/2})};this.resize=g;this.show=k;l=$.extend(!0,{},{labels:{alert:"Do You wish to proceed?",confirm:"OK",cancel:"Cancel"}},e);d=$("<div/>").appendTo(l.target).css({position:"absolute"}).addClass("confirm").hide();
a=$("<form/>").appendTo(d).css({position:"absolute",top:"50%",left:"50%"});c=$("<div/>").appendTo(a).addClass("message");b=$("<input/>").prop({type:"button"}).appendTo(a).val(l.labels.confirm).addClass("yes");$("<input/>").prop({type:"button"}).appendTo(a).val(l.labels.cancel).addClass("no").click(function(a){k(!1)});g()};plura=plura||{};plura.admin=plura.admin||{};
plura.admin.Log=function(e){var d,b;this._admin=function(){return d};e=$.extend(!0,{},{fields:[{label:"Email",name:"email"},{label:"password",name:"pass",type:"password"}],params:{log:1}},e,{target:e.target||"body"});b=new plura.form.Form(e);b.core.on("FORM_PROCESS_ERROR FORM_PROCESS_SUCCESS FORM_REQUEST_ERROR FORM_REQUEST_SUCCESS FORM_VALIDATION_ERROR",function(a,b){a.stopPropagation();$(a.target).trigger(a.type.replace(/(FORM_|ITEM_)/,""),b)}).on("FORM_PROCESS_SUCCESS",function(a,c){d=c.a&&1===
c.a;b.core.slideUp("slow",function(){$(this).trigger("LOGGEDIN",c)})}).addClass("log");this.core=b.core;return this};(function(){Object.defineProperties(plura.admin.Log.prototype,{admin:{get:function(){return this._admin()}}})})();plura=plura||{};plura.admin=plura.admin||{};plura.admin.module=plura.admin.module||{};
plura.admin.module.List=function(e){var d,b,a,c,l,k,g,n=function(a,r){if(!r||r&&d!==a)if(r?b.find(".i"+a).addClass("active"):b.find(".i"+a).removeClass("active"),c.removable)g[a].on(!r);!r||null===d&&d===a||(null!==d&&n(d,!1),d=a,b.trigger("ITEM_SELECT",b.find(".i"+a).data("data")))},p=function(f){console.log("LIST REMOVE: "+c.path+"?"+$.param($.extend({},c.params,{deleteID:f})));$.getJSON(c.path,$.extend({},c.params,{deleteID:f}),function(f){!f.success||"true"!==f.success&&1!==f.success?(f.success&&
"false"===f.success||0===f.success)&&b.trigger("ITEM_REMOVE_ERROR",plura.admin.utils.alert(f,c.labels.alert.remove.error)):(1===a.children().length&&b.children().slideUp(),b.trigger("ITEM_REMOVE_SUCCESS",plura.admin.utils.alert(f,c.labels.alert.remove.success)))})},m=function(a){var b={};c.tree||a.children().each(function(a){b[$(this).data("data")._index]=a});return b},q=function(f){d=null;b.empty();if(f){f=f instanceof Array?{items:f}:f;var e,h,y,z=$("<div/>").appendTo(b).addClass("header");h=f.items&&
1===f.items.length?c.labels.entries[0]:c.labels.entries[1];e=f.items&&f.items.length?f.items.length:0;$("<p/>").appendTo(z).html(e+" "+h).addClass("info");g={};if(f.items){a=$("<ul/>").appendTo(b).addClass("items");console.log(f.items[0]);for(h=0;h<f.items.length;h+=1)e=$("<div/>").html(f.items[h]._label||f.items[h].name).addClass("label"),e=$("<li/>").data({data:f.items[h],index:h}).addClass("i"+h).appendTo(a).append(e).click(v),f.items[h]._img&&(y=f.items[h]._img.match(/\.(jpg|jpeg|png)$/i)?$(new Image).prop({src:f.items[h]._img}).addClass("img"):
$("<div/>").addClass("stream"),y.prependTo(e).on("mouseout mouseover",t)),"1"===f.items[h]._off&&e.addClass("off"),f.items[h]._url&&$("<a/>").prop({href:f.items[h]._url}).addClass("url").appendTo(e).click(u).text("\u21d2"),c.removable&&(g[h]=new plura.admin.common.Trigger({data:f.items[h][c.fields[0].name],target:e}),g[h].core.on("TRIGGER",w));(c.sort||f.sort)&&1<f.items.length&&a.sortable({update:x}).addClass("sort")}f.filter&&(f=new plura.form.Form({fields:[{change:s,label:c.labels.filter,name:"filter",
type:"select",value:k,values:f.filter}],submit:!1,target:z}),f.core.addClass("filter"));l=new plura.admin.module.Thumb({target:b})}},s=function(a){a.stopImmediatePropagation();k=$(a.target).val().match(/^\s*$/)?null:$(a.target).val();console.log("LIST FILTER: "+c.path+"?"+$.param($.extend({},c.params,{refresh:"list"},k?{filter:k}:null)));$.getJSON(c.path,$.extend({},c.params,{refresh:"list"},k?{filter:k}:null),function(a){q(a)})},t=function(a){"mouseout"===a.type?l.show(!1):l.show(!0,$(a.target))},
v=function(a){$(a.target).hasClass("active")||$(a.target).prop("class").match(/url/)||n($(this).data("index"),!0)},u=function(a){a.preventDefault();window.open($(a.target).prop("href"))},x=function(a){a.stopImmediatePropagation();switch(a.type){case "sortupdate":console.log("LIST SORT: "+c.path+"?"+$.param($.extend({},c.params,{rank:m($(a.target))}))),$.getJSON(c.path,$.extend({},c.params,{rank:m($(a.target))}),function(a){b.trigger(a.success?"SORT_SUCCESS":"SORT_ERROR",plura.admin.utils.alert(a,
a.success?c.labels.alert.sort.success:c.labels.alert.sort.error))})}},w=function(a,b){a.stopImmediatePropagation();c.confirm?plura.admin.Confirm.show(!0,function(){p(b)},c.labels.alert.confirm):p(b)};this._selected=function(){return k};this.reset=function(){null!==d&&(n(d,!1),d=null)};this.update=q;c=$.extend(!0,{},{labels:{alert:{confirm:"Do you wish to remove this item?",remove:{success:"Success! Item Removed!",error:"Error! Item Not Removed!"},sort:{error:"Error while sorting items :(",success:"Items were successfully sorted!"}},
entries:["entry","entries"],filter:"Filter"},removable:!0,sort:!1,tree:!1},e);this.core=b=$("<div/>").addClass("list").appendTo(c.target);return this};(function(){Object.defineProperties(plura.form.Form.prototype,{selected:{get:function(){return this._selected()}}})})();plura=plura||{};plura.admin=plura.admin||{};plura.admin.module=plura.admin.module||{};
plura.admin.module.Thumb=function(e){var d,b,a,c,l,k=function(){$(this).remove()},g=function(a){$(a.target).fadeIn();d-=a.target.height/2;b-=a.target.width;c.animate({width:a.target.width,height:a.target.height,top:d,left:b}).fadeIn()},n=function(){c.fadeOut("slow")};this.show=function(e,m){l&&clearTimeout(l);e?(a&&a.fadeOut(k),m.prop("src").match(/\.(gif|jpg|jpeg|png)$/i)&&(a=$(new Image).load(g).appendTo(c).hide().prop({src:m.prop("src")})),b=m.position().left-10,d=m.parent().position().top+m.position().top+
m.height()/2):l=setTimeout(n,1E3)};e=$.extend(!0,{},{width:400,height:400},e);c=$("<div/>").appendTo(e.target).addClass("thumb").hide()};plura=plura||{};plura.admin=plura.admin||{};
plura.admin.Module=function(){var e={ajax:{type:"POST"},alert:{result:{success:"Success! Content updated!",error:"Error! Content not updated! :("}},check:null,fields:null,labels:{},list:!0,params:null,sort:!1,submit:"Submit",upload:{path:""}},d,b,a,c,l,k=this,g=function(a){l.on(!1);d.reset(a);b&&b.reset()},n=function(){console.log("MODULE UPDATE: "+c+"?"+$.param($.extend({},a.params,{refresh:1},b&&b.selected?{filter:b.selected}:null)));$.getJSON(c,$.extend({},a.params,{refresh:1},b&&b.selected?{filter:b.selected}:
null),function(c){c&&(!1!==a.list?b.update(c.list):d.populate(c.list),d.refresh(c))})},p=function(a,b){a.stopPropagation();console.log(b);$(a.target).trigger(a.type.replace(/(FORM_|ITEM_)/,""),b)},m=function(a,b){g(!0);n()},q=function(a,b){switch(a.type){case "ITEM_REMOVE_SUCCESS":n();break;case "ITEM_SELECT":l.on(!0),d.populate(b)}},s=function(a){a.stopImmediatePropagation();g()};this.init=function(g){a=$.extend(!0,{},e,this.set||{},g);c=a.path||window.location.href;d=new plura.form.Form($.extend(!0,
{},a,{path:c,target:a.target}));d.core.on("FORM_PROCESS_SUCCESS",m).addClass("main");a.list&&(b=new plura.admin.module.List($.extend(!0,{confirm:a.confirm,fields:a.fields,labels:a.labels.list||{},params:a.params,path:c,target:a.target},"object"===typeof a.list?a.list:{})),b.core.on("ITEM_REMOVE_SUCCESS ITEM_SELECT",q));l=new plura.admin.common.Trigger({on:!1,target:d.core});l.core.on("TRIGGER",s);k.core=$(a.target).on("FORM_PROCESS_ERROR FORM_PROCESS_SUCCESS FORM_REQUEST_ERROR FORM_REQUEST_SUCCESS FORM_VALIDATION_ERROR ITEM_REMOVE_ERROR ITEM_REMOVE_SUCCESS",
p);k.form=d.core};this.params=function(b){a.params=$.extend(!0,{},a.params,b)};this.update=n;return this};plura=plura||{};plura.admin=plura.admin||{};
plura.admin.Obj=function(e){var d={confirm:!0,data:null,first:!1,labels:{},log:!0,params:null,path:null,wrap:!0},b,a,c,l,k,g,n,p,m=this,q=function(){var a="boolean"===typeof g.log?{target:b}:$.extend(!0,{},g.log,{path:g.path,target:g.log.target||b});c=new plura.admin.Log(a);c.core.on("PROCESS_ERROR PROCESS_SUCCESS REQUEST_ERROR SUBMIT VALIDATION_ERROR",u).on("LOGGEDIN",w)},s=function(c){k={};p=new plura.admin.User({target:b});p.core.on("LOGOUT",f);a=new plura.templates.structures.Tabs({first:g.first,
hide:!1,target:b,tree:c});a.core.on("MENU_COMPLETE MENU_COMPLETE_ITEM MENU_SELECT",x);n=new plura.admin.Screen({target:b});g.confirm&&(plura.admin.Confirm=new plura.admin.Confirm({target:b}));plura.admin.SCREEN=n;a.refresh()},t=function(a){var b;g.params=$.extend(!0,{},g.params,a);plura.admin.PARAMS=g.params;if(k)for(b in k)k.hasOwnProperty(b)&&k[b].hasOwnProperty("params")&&k.params(a);return m},v=function(){b.children().fadeOut("slow",function(){b.empty();g.log&&q()})},u=function(a,b){a.stopImmediatePropagation();
b.name&&b.alert.replace(/%name/,b.name);l.refresh(!a.type.match(/ERROR$/),b.alert)},x=function(b,d){b.stopImmediatePropagation();switch(b.type){case "MENU_COMPLETE":if(g.wrap){var e=g.wrap.menu||$("<div/>").addClass("_menu"),f=g.wrap.form||$("<div/>").addClass("_form"),h=g.wrap.list||$("<div/>").addClass("_list");a.menu.core.wrap(e);a.content.core.find(".holder>.main").wrap(f);a.content.core.find(".holder>.list").wrap(h)}break;case "MENU_COMPLETE_ITEM":f=g.data;e=d.id.replace(/i(.+)/,"$1").split("_");
h=f[e[0]];for(f=1;f<e.length;f+=1)h=h.children[e[f]];e=h;f=a.get(d.id);!1!==e.module?(h=new (plura.utils.Extend(plura.admin.Module,e.content)),c&&c.admin&&(t({plr:1}),e.settings&&(h.set.fields=h.set.fields.concat([{label:"l",name:"_l",type:"checkbox"},{label:"t",name:"_t",type:"checkbox"}]))),h.init({confirm:g.confirm,labels:g.labels.module||{},params:g.params||{},path:g.path,target:f,upload:g.upload||{}})):h=new e.content({params:g.params,target:f});if(h.core)h.core.on("PROCESS_ERROR PROCESS_SUCCESS REMOVE_ERROR REMOVE_SUCCESS REQUEST_ERROR SORT_ERROR SORT_SUCCESS SUBMIT VALIDATION_ERROR",
u);k[d.id]=h;break;case "MENU_SELECT":k[d.id].update&&"function"===typeof k[d.id].update&&k[d.id].update()}},w=function(a,c){a.stopImmediatePropagation();g.data&&s(g.data);b.trigger("LOGGEDIN",c)},f=function(a,b){v()},r=function(a){var c;if(k)for(c in k)k.hasOwnProperty(c)&&k[c].hasOwnProperty("resize")&&k[c].resize();b.width($(a.target).width()).height($(a.target).height())},h=function(){g=$.extend(!0,{},d,e);b=$("<div/>").appendTo(g.target||"body").addClass("admin core");l=new plura.templates.alert.Slide({target:b});
g.log?q():g.data&&s(g.data);$(window).resize(r);m.core=b;return m};this.init=h;this.params=t;this.refresh=function(a){g.data=a;s(g.data)};return h()};plura=plura||{};plura.admin=plura.admin||{};
plura.admin.Screen=function(e){var d,b=function(a,b){d.core.css({width:$(window).width(),height:$(window).height()});a?(d.activate(b,!0),d.core.fadeIn("slow")):(d.disable(),d.core.fadeOut("slow"))};this.get=function(a){return d.get(a)};this.show=b;d=new plura.templates.structures.Content({classes:"screen",target:e.target});d.core.hide().click(function(a){a.target===d.core[0]&&b(!1)})};plura=plura||{};plura.admin=plura.admin||{};
plura.admin.User=function(e){e=$.extend(!0,{},{},e);this.core=$("<div/>").appendTo(e.target||"body").addClass("user core").click(function(d){$(d.target).trigger("LOGOUT")}).html("Logout");return this};plura=plura||{};plura.admin=plura.admin||{};plura.admin.utils=plura.admin.utils||{};plura.admin.utils.alert=function(e,d){return"string"===typeof e?e:e.alert?e:$.extend(!0,{},e,{alert:d})};