/**
 * Plura P Javascript Framework [http://plura.pt]
 * 
 * Copyright (c) 2014 Plura
 *
 * Date: 2014-09-18 12:00:00 (Fri, 18 Sep 2014)
 * Revision: 6246
 */
var plura={obj:function(b,d){var c,e=b.split("."),a=window;b.match(/^\./)&&(e=["plura"].concat(e.splice(1)));for(c=0;c<e.length;c+=1){if(void 0!==d)a[e[c]]=c<e.length-1?a[e[c]]||{}:d;else if(c<e.length-1&&void 0===a[e[c]])return;a=a[e[c]]}return a}};
plura.obj(".constants",{Paths:{PHP:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.php"):null,SWF:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.swf"):null},RegExp:{EMAIL:/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,EMPTY:/^\s*$/}});plura=plura||{};plura.events=plura.events||{};plura.events.EventDispatcher=function(){};
plura.events.EventDispatcher.prototype={constructor:plura.events.EventDispatcher,apply:function(b){b.addEventListener=plura.events.EventDispatcher.prototype.addEventListener;b.hasEventListener=plura.events.EventDispatcher.prototype.hasEventListener;b.removeEventListener=plura.events.EventDispatcher.prototype.removeEventListener;b.dispatchEvent=plura.events.EventDispatcher.prototype.dispatchEvent},addEventListener:function(b,d){void 0===this._listeners&&(this._listeners={});var c=this._listeners;void 0===
c[b]&&(c[b]=[]);-1===c[b].indexOf(d)&&c[b].push(d)},hasEventListener:function(b,d){if(void 0===this._listeners)return!1;var c=this._listeners;return void 0!==c[b]&&-1!==c[b].indexOf(d)?!0:!1},removeEventListener:function(b,d){if(void 0!==this._listeners){var c=this._listeners[b];if(void 0!==c){var e=c.indexOf(d);-1!==e&&c.splice(e,1)}}},dispatchEvent:function(){var b=[];return function(d){if(void 0!==this._listeners){var c=this._listeners[d.type];if(void 0!==c){d.target=this;for(var e=c.length,a=
0;a<e;a++)b[a]=c[a];for(a=0;a<e;a++)b[a].call(this,d)}}}}()};
plura.obj(".core.Loader",function(b){var d,c,e,a,f,k,g,h=function(a){"img"===a.dataType?c[a.name]=$(new Image).error(n).load(m).prop({src:a.path}):$.ajax({url:a.path,dataType:a.dataType,type:a.type,success:function(d){c[a.name]=d;l(c[a.name])},error:function(a,c,h){d.trigger("LOADER_ERROR",q())}})},l=function(c){a[e]=c;k=Math.ceil((e+1)/g.length*100);d.trigger("LOADER_COMPLETE_ITEM",q());e<g.length-1?(e+=1,r(e)):d.trigger("LOADER_COMPLETE",q())},n=function(a){d.trigger("LOADER_ERROR",q())},m=function(a){a=
$(a.target);l(a)},q=function(){return{content:c,index:e,items:a,item:$.extend({},g[e],{obj:c[g[e].name]}),progress:k}},r=function(a){h(g[a]);d.trigger("LOADER_CHANGE",q())},p=function(){g&&"img"===g[e].dataType&&c[g[e].name].off("load")},s=function(d){p();c={};a=[];e=0;var h=$.extend([],d);for(d=0;d<h.length;d+=1)h[d].dataType||(h[d].path.match(/\.(jpg|png|gif)$/i)?h[d].dataType="img":h[d].dataType="text"),h[d].label||(h[d].label=h[d].path.match(/.*\/(.*\..*)$/)[1]),h[d].type||(h[d].type="GET"),f.cache||
(h[d].path=plura.utils.Cache(h[d].path));g=h;r(e)};this._data=function(a){if(void 0===a)return c;s(a)};this._items=function(){return a};this.pause=p;f=$.extend(!0,{},{data:null,cache:!1,log:!1},b);this.core=d=f.target||$(window);f.data&&s(f.data);return this});(function(){Object.defineProperties(plura.core.Loader.prototype,{data:{get:function(){return this._data()},set:function(b){this._data(b)}},items:{get:function(){return this._items()}}})})();
plura.obj(".ecommerce.Cart",function(b){var d=this,c,e,a=function(a){for(var c in a)if(a.hasOwnProperty(c))return!1;return!0};this.add=function(b){0<b.units?(e=e||{},e[b.id]?e[b.id].update(b):e[b.id]=new plura.ecommerce.CartItem(b),b.group&&(c=c||{},c[b.group]=c[b.group]||{},c[b.group][b.id]=e[b.id])):(delete e[b.id],a(e)&&(e=null),c&&c[b.group]&&(delete c[b.group][b.id],a(c[b.group])&&(delete c[b.group],a(c)&&(c=null))));d.dispatchEvent({type:"REFRESH"})};this._group=function(){return c};this._items=
function(){return e};this._length=function(){var a,c=0;if(e)for(a in e)e.hasOwnProperty(a)&&(c+=1);return c};this._total=function(){var a,c={units:0,price:0},d;e&&(a=e);if(a)for(d in a)a.hasOwnProperty(d)&&(c.units+=a[d].units,c.price+=a[d].total);return c};$.extend({},!0,{currency:"\u20ac"},b)});
(function(){Object.defineProperties(plura.ecommerce.Cart.prototype,{group:{get:function(){return this._group()}},length:{get:function(){return this._length()}},items:{get:function(){return this._items()}},total:{get:function(){return this._total()}}});plura.events.EventDispatcher.prototype.apply(plura.ecommerce.Cart.prototype)})();
plura.obj(".ecommerce.CartItem",function(b){this.id=this.group=this.data=null;this.label="item";this.units=this.price=0;var d=this,c=function(c){for(var a in c)c.hasOwnProperty(a)&&a.match(/(data|group|id|label|price|units)/)&&(d[a]=c[a])};this.update=c;this._total=function(){return d.price*d.units};b&&c(b)});(function(){Object.defineProperties(plura.ecommerce.CartItem.prototype,{total:{get:function(){return this._total()}}})})();
plura.obj(".events.Touch",function(b){var d,c,e,a,f,k,g,h,l,n=function(){g=k=f=a=e=c=0;l=h=null};d=$.extend(!0,{},{length:72,target:null},b);this.core=d.target;n();d.target.on("MSPointerDown MSPointerMove MSPointerUp MSPointerOver MSPointerOut touchstart touchend touchmove touchcancel",function(b){b.stopImmediatePropagation();switch(b.type){case "MSPointerUp":case "touchend":b.preventDefault();if(1===c&&0!==f){g=Math.round(Math.sqrt(Math.pow(f-e,2)+Math.pow(k-a,2)));if(g>=d.length){b=e-f;var q=k-
a;Math.round(Math.sqrt(Math.pow(b,2)+Math.pow(q,2)));b=Math.atan2(q,b);h=Math.round(180*b/Math.PI);0>h&&(h=360-Math.abs(h));l=45>=h&&0<=h?"left":360>=h&&315<=h?"left":135<=h&&225>=h?"right":45<h&&135>h?"down":"up"}d.target.trigger("TOUCHSWIPE",{direction:g>=d.length?l:!1})}n();break;case "touchcancel":n();break;case "MSPointerMove":case "touchmove":b.preventDefault();b.originalEvent.touches&&1!==b.originalEvent.touches.length?n():(f=b.originalEvent.pageX||b.originalEvent.touches[0].pageX,k=b.originalEvent.pageY||
b.originalEvent.touches[0].pageY,d.target.trigger("TOUCHMOVE",{delta:{x:e-f,y:a-k},position:{x:f,y:k}}));break;case "MSPointerDown":case "touchstart":b.preventDefault(),c=b.originalEvent.touches?b.originalEvent.touches.length:1,1===c?(e=b.originalEvent.pageX||b.originalEvent.touches[0].pageX,a=b.originalEvent.pageY||b.originalEvent.touches[0].pageY):n()}})});
plura.obj(".form.Form",function(b){var d,c,e,a,f,k=function(a){var c=d.find("*[name="+a.name+"]"),b,e,g;switch(a.type){case "list":case "select":for(c.empty(),"select"===a.type&&c.append("<option/>"),b=0;b<a.values.length;b+=1)"string"===typeof a.values[b]?(g=a.values[b],e=a.values[b]):(g=void 0!==a.values[b].value?a.values[b].value:a.values[b][a.name],e=a.values[b].label||a.values[b].name||a.values[b].value),$("<option/>").prop({value:g}).appendTo(c).html(e)}a.value&&c.val(a.value)},g=function(c,
b){var n,m,q=c||(a.submit?a.fields.concat([{type:"submit",value:a.submit}]):a.fields);for(n=0;n<q.length;n+=1)if(q[n]instanceof Array||q[n].fields||q[n].type&&q[n].type.match(/^(field)?set$/i))m=$("<fieldset/>").appendTo(b||d).prop({name:q[n].name}),q[n]instanceof Array||$("<legend/>").appendTo(m).text(q[n].label||q[n].name),g(q[n].fields||q[n],m);else{m=q[n];var r=b||d,p=void 0,s=void 0;$("<div/>");var t=p=void 0;switch(m.type){case "select":p=$("<select/>");break;case "list":p=$("<select/>").prop({multiple:!0,
size:m.size||1});break;case "textarea":p=$("<textarea/>");m.wysiwyg&&window.tinyMCE&&(s=tinymce.DOM.uniqueId(),t=$.extend(!0,a.tinyMCE,{editor_selector:s},"number"!==typeof m.wysiwyg?m.wysiwyg:null,{width:300}),p.addClass(s+" tinyMCE").prop({id:s}).appendTo("body").width(p.width()).height(p.height()),tinyMCE.init(t));break;case "file":p=new plura.form.Upload($.extend({name:m.name,target:r},a.upload));break;default:p=m.type&&"date"!==m.type?m.type:"text",p=$("<input/>").prop({type:p}),jQuery.ui&&"date"===
m.type&&p.datepicker({dateFormat:"yy-mm-dd"})}m.disabled&&p.prop({disabled:"disabled"});m.change&&p.change(m.change);m.label&&$("<label/>").text(m.label||m.name).appendTo(r).prop({"for":m.name}).addClass("type-"+(m.type||"text"));m.type&&m.type.match(/file/)||p.prop({name:m.name}).appendTo(r);m.type&&m.type.match(/file/)&&f.push(p);void 0===m.value&&!m.values||m.type&&!m.type.match(/(checkbox|list|select|submit|radio|text|textarea)/)||(m.type&&m.type.match(/(checkbox|radio|submit)/)?(p.prop({value:m.value}),
m.type.match(/(checkbox|radio)/)&&m.checked&&p.prop("checked",!0)):k(m));e[m.name]=m}};this._query=function(){return c._query()};this._params=function(a){return c._params(a)};this.populate=function(a){var c,b;for(c in a)if(a.hasOwnProperty(c)&&(b=d.find("*[name="+c+"]"),b.length))switch(b.prop("type")){case "checkbox":b.prop("checked","0"!==a[c]);break;default:b[0].tagName.match(/textarea/i)&&b.hasClass("tinyMCE")?tinyMCE.get(b.prop("id")).setContent(a[c]||""):b.val(a[c])}};this.refresh=function(a){var c,
d;for(d in a)a.hasOwnProperty(d)&&e[d]&&(c=$.extend(!0,{},e[d],{values:a[d]}),k(c))};this.reset=function(a){c.reset(a)};a=$.extend(!0,{},{alert:{success:"Success! Content updated!",error:"Error! Content not updated! :("},check:null,fields:null,path:null,params:null,reset:!1,send:!0,submit:"Submit",tinyMCE:{mode:"specific_textareas",theme:"advanced",plugins:"fullscreen",theme_advanced_buttons1:"bold,italic,underline,|,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,outdent,indent",
theme_advanced_buttons2:"formatselect,sub,sup,code,fullscreen,link,unlink,|,forecolor,removeformat"}},b);d=$("<form/>").appendTo(a.target);f=[];e={};g();this.core=d;this.uploads=f;c=new plura.form.FormManager($.extend(!0,{},{ajax:a.ajax||{},alert:a.alert||{},check:a.check||{},params:a.params||{}},{path:a.path,reset:a.reset,send:a.send,target:this,type:"getJSON"}));return this});
(function(){Object.defineProperties(plura.form.Form.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(b){this._params(b)}}})})();
plura.obj(".form.FormManager",function(b){var d,c,e,a=function(a){d.find("input[type=file]").each(function(c){e[c]=new plura.form.Upload($.extend({name:$(this).attr("name"),target:d},a));e[c].core.replaceAll($(this))})},f=function(a){var c=$.extend({},{not:":button, :submit, :reset",checked:!0,selected:!0,upload:!0}),b=d.find(":input").not(c.not);b.not(":checkbox, :radio").val("");c.checked&&b.prop("checked",!1);c.selected&&b.prop("selected",!1);for(c=0;c<e.length;c+=1)e[c].reset(a);window.tinyMCE&&
d.find(".tinyMCE").each(function(){tinymce.get($(this).prop("id")).setContent("");tinymce.get($(this).prop("id")).nodeChanged()})},k=function(){var a=c.path||window.location.href,b=function(a,c){return"string"===typeof a?a:a.alert?a:$.extend(!0,{},a,{alert:c})};console&&console.log(c.ajax.dataType+" | "+c.ajax.type+" | "+a+":"+g());$.ajax({url:a,data:g(),dataType:c.ajax.dataType,type:c.ajax.type,success:function(a){d.trigger("FORM_REQUEST_SUCCESS",b(a,c.alert.complete));!a.success||"true"!==a.success&&
1!==a.success?(a.success&&"false"===a.success||0===a.success)&&d.trigger("FORM_PROCESS_ERROR",b(a,c.alert.error)):(c.reset&&f(!0),d.trigger("FORM_PROCESS_SUCCESS",b(a,c.alert.success)))},error:function(a,c,b){d.trigger("FORM_REQUEST_ERROR",{xhr:a,textStatus:c,errorThrown:b,alert:b})}});d.trigger("FORM_SUBMIT",{alert:c.alert.submit})},g=function(){return d.serialize()+"&"+$.param(c.params||{})};this._query=g;this._params=function(a){void 0!==a&&(c.params=$.extend(!0,c.params||{},a));return c.params};
this.reset=f;c=$.extend(!0,{},{ajax:{dataType:"json",type:"GET"},alert:{complete:"Your form was submited.",error:"There was an error processing your form.",field:"Please correctly fill the % field. Thank you",submit:"Form is being submitted. Please wait.",success:"Your form was successfully processed! Thank you."},check:!1,params:null,path:null,replace:!0,reset:!1,send:!0,target:null,upload:{}},b);d=c.target.core||c.target;e=c.target.uploads||[];this.form=d;c.replace&&a(c.upload);d.submit(function(a){a.preventDefault();
window.tinyMCE&&tinyMCE.triggerSave();if(!(a=!c.check))a:{var b,e,g,f;for(b=0;b<c.check.length;b+=1)for(a=c.check[b],g=a.rules?a.rules instanceof Array?a.rules:[a.rules]:[{alert:a.alert||null}],e=0;e<g.length;e+=1)if(f=plura.utils.String.test([/\./,/#/],a.id)?d.find(a.id):d.find("*[name="+a.id+"]"),g[e].exp&&!plura.utils.String.test(g[e].exp,f.val())||!g[e].exp&&f.val().match(/^\s*$/)){a=g[e].alert||c.alert.field.replace(/%/,a.id);d.trigger("FORM_VALIDATION_ERROR",{alert:a});a=!1;break a}d.trigger("FORM_VALIDATION_SUCCESS");
a=!0}a&&c.send&&k()}).find("input[type=reset]").click(function(a){a.preventDefault();f()})});(function(){Object.defineProperties(plura.form.FormManager.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(b){this._params(b)}}})})();
plura.obj(".form.upload.File",function(b){var d,c,e,a,f,k,g=function(){c.slideUp("slow",n);k.reset()},h=function(a){$.getJSON(f.process,{action:"delete",file:e.file,path:f.path,type:"upload"},function(d){"true"===d.success&&a&&(g(),c.trigger("FORM_UPLOAD_REMOVE"))})},l=function(a){if(e&&!a)h(!0);else if(!e||e&&a)e||(swf.cancel(f.id),c.trigger("FORM_UPLOAD_CANCEL")),g()},n=function(){$(this).remove()};this.update=function(g){e=g;a=a||$("<input/>").prop({type:"hidden",name:b.name+"[]"}).appendTo(c);
a.val(g.file+"|"+g.name);d.val(f.label.remove)};this.clean=function(){e&&h();d.val(f.label.cancel)};this.reset=l;this.refresh=function(a){k.refresh(a)};f=$.extend(!0,{},{css:{button:{border:"none","float":"right","text-align":"center",width:50},file:{"float":"left",width:"100%"},progress:{"float":"left"}},height:20,label:{cancel:"Cancel",remove:"Delete"},margin:5,swf:null,width:100},b);c=$("<div/>").addClass("file i"+f.id).appendTo(f.target);k=new plura.layout.ProgressBar({target:c,css:{core:$.extend({},
f.css.file,{width:f.width-3*f.margin-f.css.button.width})}});d=$("<input/>").prop({type:"button"}).val(f.label.cancel).addClass("delete").appendTo(c).click(function(a){l()});this.core=c;c.css($.extend({},f.css.file,{"margin-bottom":f.margin}));d.css($.extend({},f.css.button,{height:f.height}));return this});
plura.obj(".form.Upload",function(b){var d,c,e,a,f,k,g,h=function(){d.children(".files").slideUp("slow",function(){$(this).remove()})},l=function(a){if(c){for(var d in c)c.hasOwnProperty(d)&&(c[d].reset(a),delete c[d]);c=null}h()},n=function(a){a.stopImmediatePropagation();1===d.children(".files").children().length&&l()},m=function(a){var c=$("<div/>");f=swfobject.getObjectById(a.id);c.replaceAll(d);$("body").prepend(d);$("#"+a.id).css({left:k.position().left,position:"absolute",top:k.position().top,
zIndex:100});d.replaceAll(c)},q=function(a,c,d){"true"===d.success&&g.instances["i"+a].update(c,d)},r=function(a,c){g.instances["i"+a].init(c)},p=function(a,c,d){g.instances["i"+a].refresh(c,d)},s=function(a){};this.init=function(b){a.multiple||!a.multiple&&!c?(c=c||{},c["i"+b]=new plura.form.upload.File($.extend(!0,{},a.file,{id:b,name:a.name,path:plura.utils.String.path(a.path,a.process||plura.constants.Paths.PHP),process:a.process||plura.constants.Paths.PHP,swf:f,target:d.children(".files").length?
d.children(".files"):$("<div/>").appendTo(d).addClass("files").css($.extend({},a.css.files,{"margin-top":a.margin,padding:a.margin+"px "+a.margin+"px 0 "+a.margin+"px",width:a.width-2*a.margin})),width:a.width})),c["i"+b].core.on("FORM_UPLOAD_CANCEL FORM_UPLOAD_REMOVE",n)):!a.multiple&&c&&c["i"+b].clean()};this.refresh=function(a,d){c["i"+a].refresh(d)};this.reset=l;this.update=function(a,d){c["i"+a].update(d)};g=plura.form.upload;g.count=void 0===g.count?0:g.count+1;g.instances=g.instances||{};g.instances["i"+
g.count]=this;g.complete=g.complete||q;g.init=g.init||r;g.refresh=g.refresh||p;g.test=g.test||s;e=g.count;a=$.extend(!0,{},{css:{files:{"float":"left","background-color":"#e0e0e0"},progress:{"float":"left"},trigger:{border:"none","float":"right","text-align":"center",width:70}},file:{},label:{cancel:"Cancel",remove:"Delete",upload:"Upload"},height:30,limit:0,margin:5,multiple:!1,path:"",obj:"plura.form.upload",swf:{params:{allowscriptaccess:"always",menu:"false",wmode:"transparent"},version:"10.0"},
process:null,width:220},b);d=$("<div/>").css({position:"relative"}).addClass("upload i"+e).appendTo(a.target);new plura.layout.ProgressBar({target:d,css:{core:$.extend({},a.css.progress,{width:a.width-a.css.trigger.width-a.margin,height:a.height})}});k=$("<input/>").prop({type:"button",value:a.label.upload}).addClass("trigger").appendTo(d);this.core=d;d.css({width:a.width});k.css($.extend({},a.css.trigger,{height:a.height}));(function(){var c=$("<div/>").attr({id:"plura_form_upload_"+e}).appendTo(d),
b=k.outerHeight(!0),g={id:e,limit:a.limit,multiple:a.multiple,obj:a.obj,path:plura.utils.String.path(a.path,a.process||plura.constants.Paths.PHP),process:a.process||plura.constants.Paths.PHP,type:"upload"},h=k.outerWidth(!0);swfobject.embedSWF(plura.constants.Paths.SWF,c.attr("id"),h,b,a.swf.version,null,g,a.swf.params,null,m)})();return this});
plura.obj(".fx.Center",function(b){var d=$.isPlainObject(b.target)?b.target:b.target||$("body"),c=b.dimensions&&b.dimensions.height?b.dimensions.height:b.obj.height(),e=b.dimensions&&b.dimensions.width?b.dimensions.width:b.obj.width(),a=$.isPlainObject(d)?d.height||0:d.height(),f=$.isPlainObject(d)?d.left||0:d.position().left,k=$.isPlainObject(d)?d.top||0:d.position().top,d=$.isPlainObject(d)?d.width||0:d.width();b.obj.css({top:(a-c)/2+k,left:(d-e)/2+f,position:"absolute"})});
plura.obj(".fx.Parallax",function(b){var d,c,e,a,f,k,g,h,l,n=function(){return{height:f.dimensions&&f.dimensions.height?f.dimensions.height:f.target.height(),width:f.dimensions&&f.dimensions.width?f.dimensions.width:f.target.width()}},m=function(){return g.x+c.x>g.x&&g.x+c.x<g.x+g.width&&g.y+c.y>g.y&&g.y+c.y<g.y+g.height?!0:!1};f=$.extend(!0,{},{enabled:{x:!0,y:!0},dimensions:null,rectangle:{width:0,height:0,y:0,x:0},restrict:{x:!0,y:!0},speed:8,target:null},b);d=f.enabled;g=f.rectangle;h=f.restrict;
l=f.target;e=l.position().left;a=l.position().top;c={x:0,y:0};k={x:0,y:0};$(document).mousemove(function(a){c={x:a.pageX-l.parent().offset().left-g.x,y:a.pageY-l.parent().offset().top-g.y}});setInterval(function(){if(!(!g||!g.width&&d.x||!g.height&&d.y)){var b,r;k.x=isNaN(k.x)?0:k.x;k.y=isNaN(k.y)?0:k.y;d.x&&(e=m()?c.x:e,g.width<n().width&&h.x||g.width>n().width&&!h.x?(b=-e*((n().width-g.width)/g.width)+g.x,k.x+=(b-l.position().left)/f.speed):d.x&&g.width>n().width&&h.x&&(b=((g.width-l.width)/2+e-
l.position().left)/f.speed,k.x+=b),1<Math.abs(b-l.position().left)&&l.css({left:k.x}));d.y&&(a=m()?c.y:a,g.height<n().height&&h.y||g.height>n().height&&!h.y?(r=-a*((n().height-g.height)/g.height)+g.y,k.y+=(r-l.position().top)/f.speed):d.x&&g.width>n().width&&h.x&&(r=((g.height-l.height)/2+a-l.position().top)/f.speed,k.y+=r),1<Math.abs(r-l.position().top)&&l.css({top:k.y}));l.trigger("PARALLAX",{dimensions:n(),inside:m(),mouse:c,rectangle:g,target:l,position:k})}},13);return this});
plura.obj(".fx.Resize",function(b){var d,c,e={increase:!0,height:null,inside:!1,target:null,width:null},a,f,k=function(){var b=f.target;d=b?$.isPlainObject(b)&&b.height?b.height:$.isPlainObject(b)?a.height():b.height():f.height||$(window).height();c=b?$.isPlainObject(b)&&b.width?b.width:$.isPlainObject(b)?a.width():b.width():f.width||$(window).width();!b||$.isPlainObject(b)&&!b.x||$.isPlainObject(b)||b.position();!b||$.isPlainObject(b)&&!b.y||$.isPlainObject(b)||b.position()},g=function(){var b,e;
if(f.increase||!f.increase&&(a.height()>d||a.width()>c))a.width()/a.height()>c/d&&f.inside||a.width()/a.height()<c/d&&!f.inside?(b=c/a.width()*a.width(),e=b*a.height()/a.width()):(e=d/a.height()*a.height(),b=e*a.width()/a.height());a.css({width:b,height:e});f.center&&plura.fx.Center({obj:f.obj,target:f.target,dimensions:f.center.dimensions||!1})};b.obj&&(f=$.extend(!0,{},e,b),a=f.obj,k(),g())});
plura.obj(".layout.LoaderBar",function(b){var d;d=new plura.layout.ProgressBar(b);b.loader.core.on("LOADER_COMPLETE_ITEM",function(c,b){d.refresh(b.progress)})});
plura.obj(".layout.navigation.Nav",function(b){var d,c,e,a,f=function(a,b){b&&(!b||d&&d[0]===a[0])||(b?a.addClass("active"):a.removeClass("active"));!b||d&&d[0]===a[0]||(d&&f(d,!1),d=a,c.trigger("SELECT",a.data()))},k=function(a){c.find(".i"+a).length?f(c.find(".i"+a),!0):e[a].data({active:!0})},g=function(c){e[c].prop({src:a.path+(a.data[c].thumb||a.data[c].file)})},h=function(a){f($(a.currentTarget),!0)},l=function(b){var d,f,l,p;b=$(b.target);var s=b.data("index");(a.width||a.height)&&plura.fx.Resize({target:{width:a.width,
height:a.height},obj:b,inside:!0});a.wrap?(l=b.parent(),l=a.wrap(b).data(b.data()).appendTo(l)):l=b;b.data("active")&&k(b.data("index"));l=l.addClass("item i"+b.data("index")).click(h);p=l.prev();a.css&&(d=0!==s%a.limit&&0<s?p.width()+p.position().left+a.margin:0,f=0!==s%a.limit&&0<s?p.position().top:0===s%a.limit&&0<s?p.position().top+p.height()+a.margin:0,l.css({position:"absolute",left:d,top:f}));a.parallax&&(d=0<s&&p.position().left+p.width()>d+l.width()?p.position().left+p.width():d+l.width(),
f=0<s&&p.position().top+p.height()>f+l.height()?p.position().top+p.height():f+l.height(),l.parent().width(d).height(f));b.fadeIn();e[s+1]&&g(s+1);c.trigger("COMPLETE_ITEM",s)};this.select=k;a=$.extend(!0,{},{css:{core:{position:"absolute",zIndex:2},parallax:{core:{position:"absolute",zIndex:1},holder:{position:"absolute",zIndex:2}}},height:null,limit:0,margin:5,overflow:!1,path:"",parallax:{},text:!1,width:null},b);c=$("<div/>").appendTo(a.target||"body").addClass(["nav",a.text?"txt":"img"].join(" "));
e=[];(function(b){var d,f;a.parallax&&(f=$("<div/>").prependTo(c).addClass("holder"),d=$.extend(!0,{rectangle:{x:0,y:0},target:f},a.parallax),$("<div/>").prependTo(c).addClass("parallax").css($.extend({},a.css.parallax.core,{width:d.rectangle.width,height:d.rectangle.height})),new plura.fx.Parallax(d),a.css&&(f.css(a.css.parallax.holder),a.overflow||c.css({overflow:"hidden",width:d.rectangle.width,height:d.rectangle.height})));for(d=0;d<b.length;d+=1)a.text?$("<a/>").appendTo(f||c).addClass("item i"+
d).data({index:d}).html(d+1).click(h):(e[d]=$(new Image).appendTo(f||c).data({index:d}).hide().load(l),0===d&&g(d))})(a.data);a.css&&c.css(a.css.core);this.core=c;return this});
plura.obj(".layout.ProgressBar",function(b){var d,c,e;this.refresh=function(a){c.height(d.height()).width(d.width()*a/100).show();100===a&&e.hide&&d.stop().fadeOut("slow")};this.reset=function(){c.fadeIn()};e=$.extend(!0,{},{bottom:!0,css:{core:{width:200,height:20,border:"2px solid #000"},bar:{backgroundColor:"#000"}},hide:!1,horizontal:!0,target:null},b);d=$("<div/>").appendTo(e.target||"body").addClass("plura progress").css(e.css.core);c=$("<div/>").appendTo(d).addClass("bar").css(e.css.bar).hide();
(function(a){a.height(a.height()-2*parseInt(a.css("border-top-width"),10)).width(a.width()-2*parseInt(a.css("border-top-width"),10))})(d);this.core=d;this.bar=c});
plura.obj(".layout.Refresh",function(b){var d,c,e=0,a,f,k=function(a){var b=c.format?c.format(a):a;c.fade?d.fadeOut(c.speed,function(){$(this).html(b).fadeIn(c.speed)}):d.html(b);d.trigger("CHANGE");c.refresh&&(clearInterval(f),f=setInterval(h,c.time))},g=function(a,b){var d,e=[],g;for(d in c.data)c.data.hasOwnProperty(d)&&(g=Math.floor(d/b),e[g]=e[g]||[],e[g].push(a[d]));return e},h=function(){"string"===typeof c.data?c.json?$.getJSON(c.data,null,function(a){k(a)}):$.get(c.data,null,function(a){k(a)}):
"object"===typeof c.data&&(k(a[e%a.length]),e+=1)};c=$.extend(!0,{},{data:!1,fade:!0,format:null,json:!1,limit:1,refresh:!0,speed:"slow",target:null,time:1E4},b);d=$("<div/>").appendTo(c.target||"body").addClass("refresh core");"object"===typeof c.data&&(a=g(c.data,c.limit));h()});
plura.obj(".layout.Slideshow",function(b){var d={auto:!0,cache:!1,center:!1,controls:!1,css:{core:{position:"relative"},media:{core:{position:"relative"},item:{position:"absolute"}}},data:null,height:null,id:"",navigation:{},outside:!1,path:"",resize:!1,target:null,timer:8E3,width:null,video:null},c,e,a,f=0,k,g,h,l,n,m,q,r=this,p=function(c){m&&clearTimeout(m);g&&g.core.remove();var b=[],d;for(d=0;d<c.length;d+=1)"string"===typeof c[d]?b.push({file:c[d]}):b.push(c[d]);a=b;1<a.length&&(h.navigation&&
(g=new plura.layout.navigation.Nav($.extend(!0,{data:a,path:h.path,target:e},h.navigation)),r.navigation=g,g.core.on("COMPLETE_ITEM SELECT",z)),h.swipe&&(n=new plura.events.Touch($.extend({target:k},"object"===typeof h.swipe?h.swipe:null)),n.core.on("TOUCHMOVE TOUCHSWIPE",w)));s(f,!0)},s=function(b,d){d&&(void 0!==c&&c.removeClass("active").addClass("inactive").fadeOut(function(){$(this).remove()}),f=b,c=t(a[f]).addClass("item active i"+f),e.trigger("CHANGE",{index:f}),g&&g.select(f),h.css&&c.css(h.css.media.item))},
t=function(a){var c,b=a.data&&a.file,d=b?$("<div/>").addClass("mixed").appendTo(k):k,e;a.data&&(c=$("<div/>").html(a.data).appendTo(d).addClass("data").hide().fadeIn());if(a.file)if(a.file.match(/\.(gif|jpg|png)$/i)||a.type&&a.type.match(/image/i))a=h.cache?h.path+a.file:h.path+a.file+"?"+(new Date).getTime(),c=$(new Image).load(v).appendTo(d).prop({src:a}).hide();else if(a.file.match(/\.(mp4)$/i)||a.type&&a.type.match(/video/i))e=new plura.media.Video($.extend({src:h.path+a.file,target:d},h.video)),
c=e.core.on("METADATA",A);return $(b?d:c).data({video:e||!1})},u=function(){s(f<a.length-1?f+1:0,!0)},y=function(){s(0<f?f-1:a.length-1,!0)},v=function(c){c=$(c.target).css({width:"auto",height:"auto"}).fadeIn();var b=c.height(),d=h.resize&&h.resize.target?h.resize.target.height():h.height||k.height(),g=c.width(),f=h.resize&&h.resize.target?h.resize.target.width():h.width||k.width();h.resize&&(h.outside&&(g>d||b>d)||!h.outside)&&plura.fx.Resize({center:"boolean"===typeof h.resize||void 0===h.resize.center?
!1:h.resize.center,inside:"boolean"===typeof h.resize||void 0===h.resize.inside?!0:h.resize.inside,obj:c,target:{width:f,height:d}});h.center&&plura.fx.Center({target:{width:f,height:d},obj:c});h.auto&&1<a.length&&(clearTimeout(m),m=setTimeout(u,h.timer));e.trigger("COMPLETE_ITEM",c)},A=function(a){a.stopImmediatePropagation();e.trigger("COMPLETE_ITEM",$(a.target))},z=function(a,c){a.stopImmediatePropagation();switch(a.type){case "SELECT":c.index!==f&&s(c.index,!0)}e.trigger("NAVIGATION_"+a.type,
c)},w=function(a,b){a.stopPropagation();var d;switch(a.type){case "TOUCHMOVE":c.css({left:-b.delta.x});break;case "TOUCHSWIPE":d=b.direction&&b.direction.match(/(left|right)/)?("left"===b.direction?-1:1)*c.outerWidth():0,c.animate({left:d},"slow"),"left"===b.direction?u():"right"===b.direction&&y()}},x=function(){};this._index=function(a){if(void 0===a)return f;s(a,!0)};this._items=function(c){if(void 0===c)return a;p(c)};this.next=u;this.pause=function(a,b){clearTimeout(m);var d=void 0!==a?a:!l;
d?d&&b&&c.data("video")&&c.data("video").pause(!0):m=setTimeout(u,h.timer);l=d};this.previous=y;(function(){h=$.extend({},d,b);e=$("<div/>").appendTo(h.target||"body").addClass("plura slideshow "+h.id);k=$("<div/>").appendTo(e).addClass("media");l=!1;"string"===typeof h.data?$.getJSON(h.data,function(a){p(a)}):h.data&&"object"===typeof h.data&&p(h.data);h.css&&(e.css(h.css.core),k.css(h.css.media.core));r.core=e;r.media=k;q=plura.layout.Slideshow;q.items=q.items||[];q.stop=q.stop||x;q.items.push(r)})();
return this});(function(){Object.defineProperties(plura.layout.Slideshow.prototype,{index:{get:function(){return this._index()},set:function(b){this._index(b)}},items:{get:function(){return this._items()},set:function(b){this._items(b)}}})})();
plura.obj(".layout.Social",function(b){var d,c=function(a){var c=$("<div/>").appendTo(d).addClass("fb-like"),b=[];a=$.extend(!0,{},a,{height:"button_count"===a.layout?21:"box_count"===a.layout?65:a.show_faces?80:35,href:a.href||window.location.href});for(var e in a)a.hasOwnProperty(e)&&b.push(e+"="+(a[e]||""));$("<iframe/>").appendTo(c).css({width:a.width,height:a.height,border:"none",overflow:"hidden"}).prop({allowTransparency:"true",frameborder:0,scrolling:"no",src:"//www.facebook.com/plugins/like.php?"+
b.join("&")})},e=function(a){var c=$("<div/>").appendTo(d).addClass("twitter"),b=$("<a/>").appendTo(c).prop({href:"http://twitter.com/share"}).addClass("twitter-share-button").html("Tweet"),e=document.createElement("script"),h;for(h in a)a.hasOwnProperty(h)&&("related"===h?a[h].user&&b.attr("data-"+h,a[h].user+(a[h].text?":"+a[h].text:"")):a[h]&&b.attr("data-"+h,a[h]));$(e).attr({type:"text/javascript",src:"http://platform.twitter.com/widgets.js"}).appendTo(c)};d=$("<div/>").addClass("share");b=$.extend(!0,
{},{like:{action:"like",colorsheme:"light",font:null,href:null,layout:"standard",show_faces:!0,width:450},twitter:{count:"horizontal",related:{text:null,via:null},text:null,via:null,url:null},target:null},b);b.target&&d.appendTo(b.target);b.like&&c(b.like);b.twitter&&e(b.twitter);return d});
plura.obj(".layout.Table",function(b){var d,c,e=function(c){a();var e,g,h=[],l={};for(e in c[0])c[0].hasOwnProperty(e);for(e=0;e<c.length;e+=1)for(g in c[e])c[e].hasOwnProperty(g)&&(h[e]=h[e]||[],l[g]=l[g]||{rowspan:1},b&&b.merge&&0<e&&c[e][g]===c[e-1][g]&&("string"===typeof b.merge?(new RegExp(b.merge)).test(g):1)?(l[g].rowspan+=1,h[l[g].r][l[g].c].rowspan=l[g].rowspan):(l[g]={rowspan:1,r:e,c:h[e].length},h[e].push({value:c[e][g],span:l[g].rowspan})));var n,l=$("<table/>").appendTo(d);for(g=0;g<
h.length;g+=1)for(e=$("<tr/>").appendTo(l),c=0;c<h[g].length;c+=1)n=$("<td/>").appendTo(e).html(h[g][c].value||h[g][c]),h[g][c].rowspan&&1<h[g][c].rowspan&&n.prop({rowspan:h[g][c].rowspan})},a=function(){d.empty()};this.refresh=e;this.empty=a;c=$.extend(!0,{},{limit:0,merge:!0,target:null},b);this.core=d=$("<div/>").appendTo(c.target||"body").addClass("table core "+(c.classes||""));c.data&&e(c.data);return this});
plura.obj(".media.Audio",function(b){var d,c,e,a,f,k,g=function(c){console.log("B:"+a);a=void 0===c?!a:c;console.log("A:"+a);a?d.find(".play").removeClass("active").html(e.labels.play):d.find(".play").addClass("active").html(e.labels.pause);f?f.pause(a):a||f||q()},h=function(a){var b=$("<div/>").attr({id:"plura_media_audio_"+c}).appendTo(d);a={content:a,id:c,obj:"plura.media.Audio",type:"audio"};swfobject.embedSWF(plura.constants.Paths.SWF,b.attr("id"),"0","0","10.0.0",null,a,null,null,n)},l=function(c){g(!a)},
n=function(a){f=swfobject.getObjectById(a.id)},m=function(a){for(var c in k.instances)k.instances.hasOwnProperty(c)&&!c.match("i"+a)&&k.instances[c].pause(!0)},q=function(){e.data?h(e.data):e.path&&$.get(e.path,function(a){h(a)})};this.fade=function(a){d.find(".menu").fadeIn("slow")};this.pause=g;k=plura.media.Audio;k.count=void 0===k.count?0:k.count+1;k.instances=k.instances||{};k.instances["i"+k.count]=this;k.pause=k.pause||m;c=k.count;e=$.extend(!0,{},{auto:!0,data:null,controls:!0,css:{flash:{position:"relative",
height:0,width:0},test:{position:"absolute",zIndex:1E3,width:400,height:400}},fade:!0,labels:{pause:"Pause",play:"Play"},path:null,params:null,target:"body",test:!1},b);(function(){d=$("<div/>").appendTo(e.target).addClass("p audio").css({position:"relative"});var a=$("<ul/>").appendTo(d).addClass("menu controls");e.controls&&$("<li/>").appendTo(a).click(l).addClass("play");g(!e.auto)})();this.core=d});
plura.obj(".media.Video",function(b){var d,c,e=!0,a,f,k=this,g=function(c){a.empty();var b,d=c instanceof Array?c:[c],e;for(c=0;c<d.length;c+=1)b=d[c].src||d[c],e=d[c].type||"video/"+b.match(/\.([^.]+)$/)[1],$("<source/>").prop({src:b,type:e}).appendTo(a);return k},h=function(b){(e=void 0===b?!e:b)?(c.addClass("pause"),a[0].pause()):(c.removeClass("pause"),a[0].play())},l=function(c){void 0!==c&&(a[0].volume=c);return a[0].volume},n=function(a){a.stopImmediatePropagation();h()};this.pause=h;this.prop=
function(c){a.prop(c);return k};this.src=g;this.volume=l;d=new plura.net.Client;b=$.extend(!0,{},{autoplay:!0,controls:!0,pause:!0,preload:!0,loop:!0,wrap:!1},b);f={autoplay:b.autoplay,controls:b.controls,loop:b.loop,height:b.height,preload:b.preload,width:b.width,poster:b.poster};a=$("<video/>").prop(f).on("loadedmetadata",function(a){c.trigger("METADATA",{width:this.videoWidth,height:this.videoHeight})});c=b.wrap?$("boolean"===typeof b.wrap?"<div/>":b.wrap).append(a).addClass("video"):a;c.appendTo(b.target||
"body");b.src&&g(b.src);k.core=c;if(b.pause&&!b.controls||d.data.ios)a.on("click touchstart",n),b.wrap&&c.click(n);b.volume&&l(b.volume);d.data.ios||h(!b.autoplay);return this});
plura.obj(".net.Client",function(b){var d;d=navigator.userAgent;var c=Boolean(d.match(/Android/i)),e=Boolean(d.match(/(explorer|MSIE)/i)),a=Boolean(d.match(/iPad/i)),f=Boolean(d.match(/iPhone/i)),k=Boolean(d.match(/iPod/i)),f=f?"iPhone":a?"iPad":k?"iPod":null,g=Boolean(null===document.location.href.match(/https?:\/\//)),h=Boolean(f||c||d.match(/Windows.+Touch/i)),l=parseInt(navigator.appVersion,10);e&&(l=parseInt(navigator.appVersion.match(/msie ([0-9\.]+)/i)[1],10));d={agent:d,android:c,ie:e,ios:f,
ipad:a,ipod:k,offline:g,touch:h,version:l};c=[];a=b&&b.ie?b.ie:11;if(d.ie){if(c.push("ie","ie"+d.version),d.version<a)for(c.push("ie_lte"+d.version),e=d.version;e<a;e+=1)c.push("ie_lt"+(e+1))}else d.ios?c=c.concat(["ios",d.ios.toLowerCase()]):d.android&&c.push("android");d.offline&&c.push("offline");c.push((d.touch?"":"no-")+"touch");d.classes=c;this.data=d;b&&b.classes&&$("body").addClass(d.classes.join(" "))});
plura.obj(".net.URLManager",function(b){var d={analytics:!0,lang:!0,separator:"#"},c,e,a,f,k,g,h=function(a,c,b,d,e){window._gaq&&(a=["_trackEvent",a,c,b,d],void 0!==e&&!0===e&&a.push(e),_gaq.push(a))},l=function(a){var b=[];a&&c&&b.push(c);k&&b.push(k);return b.join("/")},n=function(a){void 0!==a&&a!==k&&(k=a,e.push(k));window.location.href="#!/"+l(!0);f.analytics&&(a="/"+l(!0),window._gaq&&_gaq.push(["_trackPageview",a]))};this._history=function(){return e};this._index=function(){return a};this._lang=
function(a){void 0!==a&&(c=a,n());return c};this._path=function(a){void 0!==a&&n(a);return k};this._root=function(){return g};this._url=function(){return g+"#!/"+l(!0)+"/"};this.event=function(){h.apply(null,arguments)};this.perma=function(a){return a.match(g+".*?([^=]*[^/])/?$")[1]};(function(){var h=window.location.href;f=$.extend(!0,{},d,b);e=[];a=0;g=h.match(/[^#]+/)[0];h.match(/#!\/(.+)/)&&(h=h.match(/#!\/(.+)/)[1].replace(/\/$/,"").split(/\//),f.lang&&h[0].match(/^[a-z]{2}$/)&&(c=h.shift()),
k=h.join("/"),e.push(k))})()});(function(){Object.defineProperties(plura.net.URLManager.prototype,{history:{get:function(){return this._history()}},index:{get:function(){return this._index()}},lang:{get:function(){return this._lang()},set:function(b){this._lang(b)}},path:{get:function(){return this._path()},set:function(b){this._path(b)}},root:{get:function(){return this._root()}},url:{get:function(){return this._url()}}})})();
plura.obj(".templates.alert.Slide",function(b){var d,c;this.refresh=function(b,a){clearTimeout(c);d.html(a).stop(!0,!0).slideDown().addClass(b?"success":"error").removeClass(b?"error":"success");c=setTimeout(function(){d.slideUp()},2E3)};d=$("<p/>").appendTo(b.target||"body").addClass("alert").hide()});
plura.obj(".templates.checkout.end.Form",function(b){var d;this._items=function(c){d.params={items:c}};b=$.extend(!0,{},{labels:{check:{email:{empty:"Please insert your email. Thank you!",invalid:"Your email address is invalid."},name:"Please insert your first and last name. Thank you!",message:"Please include a message. Thank you!"},fields:{email:"Email",name:"Name",message:"Message"}}},b);d=new plura.form.Form({check:[{id:"user_email",rules:[{alert:b.labels.check.email.empty},{exp:String(plura.constants.RegExp.EMAIL),
alert:b.labels.check.email.invalid}]},{id:"user_message",alert:b.labels.check.message},{id:"user_name",alert:b.labels.check.name}],fields:[[{name:"user_name",label:b.labels.fields.name},{name:"user_email",label:b.labels.fields.email},{name:"user_message",type:"textarea",label:b.labels.fields.message}]],params:$.extend({type:"checkout"},b.params),reset:!0,target:b.target});d.core.on("FORM_PROCESS_ERROR FORM_PROCESS_SUCCESS FORM_VALIDATION_ERROR",function(c,b){switch(c.type){case "FORM_PROCESS_ERROR":alert(b.alert);
break;case "FORM_PROCESS_SUCCESS":alert(b.alert);break;case "FORM_VALIDATION_ERROR":alert(b.alert)}}).addClass("big check-out");this.core=d.core});(function(){Object.defineProperties(plura.templates.checkout.end.Form.prototype,{items:{set:function(b){this._items(b)}}})})();
plura.obj(".templates.checkout.end.List",function(b){var d,c,e;this.refresh=function(a){var c,b,g,h=$("<ul/>").addClass("items");d.empty().append(h).prepend(e);for(c=0;c<a.length;c+=1){b=a[c];var l=$("<li/>").addClass("group");$("<span/>").text(b.name).addClass("group-label").appendTo(l);$("<ul/>").appendTo(l).addClass("group-items");b=l.appendTo(h);for(g in a[c].items)if(a[c].items.hasOwnProperty(g)){var l=a[c].items[g],n=$("<li/>").addClass("item item-"+l.data.ID),m=$("<ul/>").addClass("subitems").appendTo(n);
$("<li/>").addClass("icon").css("background-image","url("+l.data.img.dark+")").appendTo(m);$("<li/>").addClass("label").appendTo(m).html(l.data.title);n.appendTo(b)}}};c=$.extend(!0,{},{labels:{title:"List"}},b);d=$("<div/>").appendTo(b.target).addClass("list");e=$("<div/>").addClass("title").text(c.labels.title);this.core=d});(function(){Object.defineProperties(plura.templates.checkout.end.List.prototype,{items:{set:function(b){this.refresh(b)}}})})();
plura.obj(".templates.checkout.End",function(b){var d,c,e;this._items=function(a){void 0!==a&&(d.items=a,e.list&&(c.items=a))};e=$.extend(!0,{},{list:!0},b);b=$("<div/>").addClass("checkout-end");d=new plura.templates.checkout.end.Form({path:e.process,params:e.params,target:b});e.list&&(c=new plura.templates.checkout.end.List($.extend({target:b},e.list)));this.core=b;this.form=d;this.list=c});
(function(){Object.defineProperties(plura.templates.checkout.End.prototype,{items:{get:function(){return this._items()},set:function(b){this._items(b)}}})})();
plura.obj(".templates.Checkout",function(b){var d,c,e,a;e=$.extend(!0,{},{end:!0,labels:{sequence:{end:"Checkout"}}},b);d=$("<div/>").appendTo(b.target).addClass("checkout");a=new plura.templates.Sequence({items:function(){var a;e.end&&(c=new plura.templates.checkout.End(e.end),a=[{name:"end",label:e.labels.sequence.end,obj:c}]);return b.sequence?b.sequence.concat(a):a}(),parent:e.parent,target:d});a.core.on("CHANGE COMPLETE COMPLETE_ITEM EXIT",function(b,e){b.stopImmediatePropagation();switch(b.type){case "COMPLETE":var g,
h;if(1<a.items.length)for(h=[],g=0;g<a.items.length-1;g+=1)a.items[g].obj.cart&&h.push({name:a.items[g].name||"i"+g,items:a.items[g].obj.cart.items});c.items=h;break;case "EXIT":d.trigger("EXIT")}});this.core=d;this.sequence=a});
plura.obj(".templates.sequence.Breadcrumbs",function(b){var d,c,e,a,f=function(){d.trigger("PARENT")},k=function(a){d.trigger("SEQUENCE",$(a.target).data("index"))};this.refresh=function(a){var c,b;for(c=0;c<a.items.length;c+=1)b=[],e[c].off("click",k).removeClass("active completed disabled enabled"),a.items[c].completed||!c||c&&a.items[c-1].completed?(a.items[c].completed?b.push("completed"):b.push("enabled"),e[c].click(k)):b.push("disabled"),a.index===c&&b.push("active"),e[c].addClass(b.join(" "))};
c=$.extend(!0,{},{},b);d=$("<div/>").appendTo(c.target).addClass("breadcrumbs");(function(){var b;d.empty();e=[];c.parent&&$("<div/>").addClass("breadcrumbs-parent").text(c.parent).appendTo(d).click(f);a=$("<div/>").addClass("breadcrumbs-sequence-items").appendTo(d);for(b=0;b<c.items.length;b+=1)e[b]=$("<div/>").addClass("breadcrumbs-sequence-item breadcrumbs-sequence-item-"+b).text(c.items[b].label||b).data("index",b).appendTo(a)})();this.core=d});
plura.obj(".templates.sequence.PreviousNext",function(b){var d,c,e,a,f=function(a){a.stopImmediatePropagation();d.trigger("NEXT")},k=function(a){a.stopImmediatePropagation();d.trigger("PREVIOUS")},g=function(a){a.stopImmediatePropagation();d.trigger("PARENT")};this.refresh=function(c){a.off("click",k).off("click",g);e.off("click",f);if(!c.index&&b.parent||0<c.index)a.addClass("active").on("click",c.index?k:g);else a.removeClass("active");c.index<c.items.length-1&&c.items[c.index].completed?e.on("click",
f).addClass("active"):e.removeClass("active")};c=$.extend(!0,{},{},b);d=$("<div/>").appendTo(c.target).addClass("previous-next");e=$("<div/>").appendTo(d).addClass("previous-next-item next");a=$("<div/>").appendTo(d).addClass("previous-next-item previous");this.core=d});
plura.obj(".templates.Sequence",function(b){var d={chained:!0,navigation:{breadcrumbs:!0,previous_next:!0}},c,e,a,f,k,g,h,l,n,m=this,q=function(c){c!==a&&(f=a,a=c,r())},r=function(){var b;b=void 0===k[a].obj.completed||k[a].obj.completed;if(k[a].completed=b)c.trigger("COMPLETE_ITEM",{index:a}),a===k.length-1&&c.trigger("COMPLETE");else if(g.chained)for(b=a+1;b<k.length;b+=1){var d=b;k[d].completed=!1;"function"===typeof k[d].obj.reset&&k[d].obj.reset()}for(b=0;b<k.length;b+=1)d=[],k[b].obj.core.removeClass("active completed disabled enabled"),
k[b].completed||!b||b&&k[b-1].completed?void 0===k[b].obj.completed||k[b].obj.completed?d.push("completed"):d.push("enabled"):d.push("disabled"),a===b&&d.push("active"),k[b].obj.core.addClass(d.join(" "));void 0!==f&&c.removeClass("sequence-"+f);c.addClass("sequence-"+a);n&&n.refresh({index:a,items:k});l&&l.refresh({index:a,items:k})},p=function(a,b){a.stopImmediatePropagation();switch(a.type){case "PARENT":c.trigger("EXIT");break;case "SEQUENCE":q(b)}},s=function(b){b.stopImmediatePropagation();
switch(b.type){case "PARENT":c.trigger("EXIT");break;case "NEXT":q(a+1);break;case "PREVIOUS":q(a-1)}},t=function(a,c){a.stopImmediatePropagation();r(c)};this._items=function(){return k};(function(){g=$.extend(!0,{},d,b);c=$("<div/>").appendTo(g.target).addClass("sequence");if(g.navigation){h=$("<div/>").appendTo(c).addClass("sequence-nav");var a={target:h,items:g.items,parent:g.parent};g.navigation.breadcrumbs&&(l=new plura.templates.sequence.Breadcrumbs($.extend(!0,{},g.navigation.breadcrumbs,a)),
l.core.on("PARENT SEQUENCE",p));g.navigation.previous_next&&(n=new plura.templates.sequence.PreviousNext($.extend(!0,{},g.navigation.previous_next,a)),n.core.on("PARENT NEXT PREVIOUS",s))}var a=g.items,f;if(k){for(f=0;f<k.length;f+=1)k[f].obj.core.off("REFRESH",t).removeClass("completed");k=null}e&&e.remove();var v;e=$("<div/>").appendTo(c).addClass("sequence-items");k=[];for(f=0;f<a.length;f+=1)v=a[f].obj?a[f]:{obj:a[f]},k[f]=v,k[f].obj.core.appendTo(e).addClass("sequence-item").on("REFRESH",t);
q(0);m.core=c})()});(function(){Object.defineProperties(plura.templates.Sequence.prototype,{items:{get:function(){return this._items()}}})})();
plura.obj(".templates.structures.Content",function(b){var d,c,e,a=function(b,e){var l="string"===typeof b?k(b):b,n=void 0===e?!0:e;n&&(!n||d&&d[0]===l[0])||f(l,n);!n||d&&d[0]===l[0]||(d&&a(d,!1),d=l,c.trigger("REFRESH",l.data()))},f=function(a,c){!0===c?a.stop(!0).fadeIn().addClass("active"):a.stop(!0).fadeOut(function(){$(this).hide()}).removeClass("active")},k=function(a){a="object"===typeof a?a:{id:a};var b=[a.id,a.vanity||"",a.classes||""].join(" "),b=e[a.id]||$("<div/>").addClass("holder "+b).append(a.obj||
null).data(a).appendTo(c).hide();return e[a.id]=b};this.activate=a;this.disable=function(){d&&(a(d,!1),d=null)};this.get=k;b=$.extend(!0,{},{},b);c=$("<div/>").appendTo(b.target||"body").addClass(["content",b.classes||""].join(" "));e={};this.core=c;this.tree=e;return this});
plura.obj(".templates.structures.Menu",function(b){var d,c,e,a,f=this,k=function(b,g){var f=void 0===g?!0:g;if(!f||d&&d[0]===b[0]){if(f)return;d=null}else d&&k(d,!1),d=b;var h="selected selected-"+b.data("id");f?(c.addClass(h),b.addClass("active")):(c.removeClass(h),b.removeClass("active"));var h=b.data("id").replace(/i(.+)/,"$1").split("_").slice(0,-1),l,n;if(h.length)for(l=0;l<h.length;l+=1)n="i"+h.slice(0,l?-l:h.length).join("_"),f?(0===l&&a[n].addClass("parent"),a[n].addClass("ancestor ancestor-"+
l)):f||(0===l&&a[n].removeClass("parent"),a[n].removeClass("ancestor ancestor-"+l));if(f){if(e.url){h=b.data();f=r(h);h=[h];l=[];f&&(h=f.concat(h));for(f=0;f<h.length;f+=1)l.push(h[f].vanity||h[f].id);url.path=l.join("/")}c.trigger("SELECT",b.data())}},g=function(b,d){var f,h,k=b.data("id").replace(/i(.+)/,"$1").split("_");if(void 0===d?!b.hasClass("open"):d){e.close&&c.find(".open").each(function(a){$(this).data("id").match(b.data("id"))||g($(this),!1)});for(f=0;f<k.length;f+=1)h="i"+k.slice(0,f?
-f:k.length).join("_"),a[h].addClass("open");c.trigger("OPEN",b.data())}else b.removeClass("open")},h=function(a){return e.leaf?e.leaf(a):a.children?!1:!0},l=function(a){return e.trigger?e.trigger(a):$("<a/>").prop({href:"#"}).html(a.label).click(function(a){a.preventDefault()})},n=function(b,d,f){var m,p,q,r,w=function(a){g($(a.currentTarget).parent())},x=function(a){k($(this),!0)};for(p=0;p<b.length;p+=1)q=f?f+"_"+p:"i"+p,r={data:b[p],depth:q.split("_").length-1,id:q,label:b[p].label||b[p].name||
b[p].vanity||b[p].id||("string"===typeof b[p]?b[p]:q),vanity:b[p].id||b[p].vanity||null},m=q+" node"+(r.vanity?" id-"+r.vanity:"")+(b[p][e.nodeID]?" id-"+b[p][e.nodeID]:""),m=$(e.tags.leaf||e.tags).appendTo(d).data(r).addClass(m),r=l(r).appendTo(m).addClass("trigger"),a[q]=m,h(b[p])?(m.click(x).addClass("leaf"),c.trigger("COMPLETE_ITEM",m.data())):(r.click(w),m=$(e.tags.branch||e.tags).appendTo(m).addClass("branch"),n(b[p].children,m,q))},m=function(b){c.empty();a={};f.tree=a;e.data=b;n(e.data,c);
e.first&&p(e.first);c.trigger("COMPLETE")},q=function(b){var c;if(void 0===b||"boolean"===typeof b){if(d)return d;for(c in a)if(a.hasOwnProperty(c)&&h(a[c].data("data")))return a[c]}else{if("string"===typeof b)return a[b];if("number"===typeof b)return a["i"+b]}},r=function(b){var c,d,e=b.id.split("_");if(1<e.length){c=[];for(b=1;b<e.length;b+=1)d=e.slice(0,b?-b:e.length).join("_"),c.push(a[d].data());c=c.reverse()}return c},p=function(a){a=q(a);k(a)};this.activate=k;this.ancestors=r;this.disable=
function(){if(d){var a=d.data();k(d,!1);c.trigger("UNSELECT",a)}};this.get=q;this.refresh=m;this.select=p;e=$.extend(!0,{},{close:!0,data:null,first:!1,id:"",leaf:null,nodeID:"nodeID",tags:{branch:"<ul/>",leaf:"<li/>"},url:null},b);c=$(e.tags.branch||e.tags).appendTo(e.target||"body").addClass("menu "+e.id);f.core=c;f.tree=a;e.data&&m(e.data)});
plura.obj(".templates.structures.Tabs",function(b){var d,c,e,a,f=function(a){a=c.tree[a]?c.tree[a].data():"object"===typeof a?a:{id:a};return e.get({classes:k(a.id).join(" "),id:a.id,vanity:a.vanity})},k=function(a){var b=[],c=a.split("_").slice(0,-1);for(a=0;a<c.length;a+=1)b[a]=a?b.join("_")+"_"+c[a]:c[a].replace(/i/,"p");return b};this.disable=function(){c.disable();e.disable()};this.get=f;this.refresh=function(){c.refresh(a.tree)};this.select=function(a){c.select(a)};a=$.extend(!0,{},{first:!1,
delay:!1,id:null,menu:{},tree:null},b);d=$("<div/>").appendTo(a.target||"body").addClass("plura templates tabs core "+(a.id||""));c=new plura.templates.structures.Menu($.extend(!0,{},a.menu,{target:d,first:a.first}));c.core.on("COMPLETE COMPLETE_ITEM OPEN SELECT",function(a,b){a.stopPropagation();if("SELECT"===a.type){var c=f(b.id);e.activate(c)}d.trigger("MENU_"+a.type,b)});this.content=e=new plura.templates.structures.Content({target:d});this.core=d;this.menu=c;return this});
plura.obj(".utils.Cache",function(b){var d=(new Date).getTime();b+=b.match(/\?/)?b.match(/\&$/)?"":"&":"?";return b+d});plura.obj(".utils.Extend",function(b,d){function c(){}c.prototype=new b;d.prototype=new c;return d});
plura.obj(".utils.Flat",function(b,d,c){var e=[],a,f=d||{},k,g=plura.utils.Flat;for(a in b)if(b.hasOwnProperty(a))if(b[a]instanceof Array)for(d=0;d<b[a].length;d+=1)if("object"===typeof b[a][d]&&!(b[a][d]instanceof Array))e=e.concat(g(b[a][d],f,a));else{if("number"===typeof b[a][d]||"string"===typeof b[a][d])k=$.extend({},f),k[a]=b[a][d],e.push(k)}else"object"===typeof b[a]&&(f[c]=a,e=e.concat(g(b[a],f)));return e});
plura.obj(".utils.Hidden",function(b){var d=(new Date).getTime(),c=function(c){b.parents("body *").each(function(){$(this).is(":animated")||(!c&&void 0!==c||"none"!==$(this).css("display")?!1===c&&$(this).hasClass("i"+d)&&$(this).removeClass("i"+d).hide():$(this).addClass("i"+d).show())})};this.get=function(){c();var d={width:b.width(),height:b.height(),innerWidth:b.innerWidth(),innerHeight:b.innerHeight(),outerWidth:b.outerWidth(),outerHeight:b.outerHeight()};c(!1);return d};this.show=c});
plura.obj(".utils.String",{path:function(b,d){var c=[],e,a,f,k;e=function(a){a.match(/^https?:\/\//)||(a=window.location.href.replace(/[^\/]+$/,"")+a);return a};b=e(b);d=d?e(d):window.location.href;d.match(/^http/)&&(f=d.replace(/(https?:\/\/)(.+)(\/([^\/]+)?)$/g,"$1$2").split("/"));a=f.length;for(e=0;e<a;e+=1){if(b.match(f.join("/"))){k=b.replace(f.join("/"),"");break}f.splice(-1);c.push("..")}return c.join("/")+k},test:function(b,d){var c,e,a;c=b instanceof Array?b:[b];for(e=0;e<c.length;e+=1)if(a=
"string"===typeof c[e]?new RegExp(c[e].replace(/^(\/)(.*)(\/)$/,"$2")):c[e],!a.test(d))return!1;return!0}});