/**
 * Plura P Javascript Framework [http://plura.pt]
 * 
 * Copyright (c) 2014 Plura
 *
 * Date: 2014-07-29 12:00:00 (Tue, 29 Jul 2014)
 * Revision: 6246
 */
var plura=plura||{};plura.events=plura.events||{};plura.events.EventDispatcher=function(){};
plura.events.EventDispatcher.prototype={constructor:plura.events.EventDispatcher,apply:function(b){b.addEventListener=plura.events.EventDispatcher.prototype.addEventListener;b.hasEventListener=plura.events.EventDispatcher.prototype.hasEventListener;b.removeEventListener=plura.events.EventDispatcher.prototype.removeEventListener;b.dispatchEvent=plura.events.EventDispatcher.prototype.dispatchEvent},addEventListener:function(b,d){void 0===this._listeners&&(this._listeners={});var c=this._listeners;void 0===
c[b]&&(c[b]=[]);-1===c[b].indexOf(d)&&c[b].push(d)},hasEventListener:function(b,d){if(void 0===this._listeners)return!1;var c=this._listeners;return void 0!==c[b]&&-1!==c[b].indexOf(d)?!0:!1},removeEventListener:function(b,d){if(void 0!==this._listeners){var c=this._listeners[b];if(void 0!==c){var e=c.indexOf(d);-1!==e&&c.splice(e,1)}}},dispatchEvent:function(){var b=[];return function(d){if(void 0!==this._listeners){var c=this._listeners[d.type];if(void 0!==c){d.target=this;for(var e=c.length,a=
0;a<e;a++)b[a]=c[a];for(a=0;a<e;a++)b[a].call(this,d)}}}}()};plura=plura||{};plura.constants={PHP:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.php"):null,REGEX_EMAIL:/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,SWF:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.swf"):null};plura=plura||{};plura.core=plura.core||{};
plura.core.Loader=function(b){var d,c,e,a,g,h,f,k=function(a){"img"===a.dataType?(c[a.name]=$(new Image),c[a.name].error(function(){d.trigger("LOADER_ERROR",m())}).load(function(){l(c[a.name])}).prop({src:a.path})):$.ajax({url:a.path,dataType:a.dataType,type:a.type,success:function(d){c[a.name]=d;l(c[a.name])},error:function(a,c,k){d.trigger("LOADER_ERROR",m())}})},l=function(c){a[e]=c;h=Math.ceil((e+1)/f.length*100);d.trigger("LOADER_COMPLETE_ITEM",m());e<f.length-1?(e+=1,n(e)):d.trigger("LOADER_COMPLETE",
m())},m=function(){return{content:c,index:e,items:a,item:$.extend({},f[e],{obj:c[f[e].name]}),progress:h}},n=function(a){k(f[a]);d.trigger("LOADER_CHANGE",m())};g=$.extend(!0,{},{data:null,cache:!1,log:!1},b);d=g.target||$(window);c={};a=[];e=0;f=function(a){var c=$.extend([],a);for(a=0;a<c.length;a+=1)c[a].dataType||(c[a].path.match(/\.(jpg|png|gif)$/i)?c[a].dataType="img":c[a].dataType="text"),c[a].label||(c[a].label=c[a].path.match(/.*\/(.*\..*)$/)[1]),c[a].type||(c[a].type="GET"),g.cache||(c[a].path=
plura.utils.Cache(c[a].path),console.log(plura.utils.Cache(c[a].path)));return c}(g.data);this.core=d;this.data=c;this.items=a;n(e);return this};plura=plura||{};plura.ecommerce=plura.ecommerce||{};
plura.ecommerce.Cart=function(b){var d=this,c,e,a=function(a){for(var c in a)if(a.hasOwnProperty(c))return!1;return!0};this.add=function(b){0<b.units?(e=e||{},e[b.id]?e[b.id].update(b):e[b.id]=new plura.ecommerce.CartItem(b),b.group&&(c=c||{},c[b.group]=c[b.group]||{},c[b.group][b.id]=e[b.id])):(delete e[b.id],a(e)&&(e=null),c&&c[b.group]&&(delete c[b.group][b.id],a(c[b.group])&&(delete c[b.group],a(c)&&(c=null))));d.dispatchEvent({type:"REFRESH"})};this._group=function(){return c};this._items=function(){return e};
this._length=function(){var a,c=0;if(e)for(a in e)e.hasOwnProperty(a)&&(c+=1);return c};this._total=function(){var a,c={units:0,price:0},d;e&&(a=e);if(a)for(d in a)a.hasOwnProperty(d)&&(c.units+=a[d].units,c.price+=a[d].total);return c};$.extend({},!0,{currency:"\u20ac"},b)};
(function(){Object.defineProperties(plura.ecommerce.Cart.prototype,{group:{get:function(){return this._group()}},length:{get:function(){return this._length()}},items:{get:function(){return this._items()}},total:{get:function(){return this._total()}}});plura.events.EventDispatcher.prototype.apply(plura.ecommerce.Cart.prototype)})();plura=plura||{};plura.ecommerce=plura.ecommerce||{};
plura.ecommerce.CartItem=function(b){this.id=this.group=this.data=null;this.label="item";this.units=this.price=0;var d=this,c=function(c){for(var a in c)c.hasOwnProperty(a)&&a.match(/(data|group|id|label|price|units)/)&&(d[a]=c[a])};this.update=c;this._total=function(){return d.price*d.units};b&&c(b)};(function(){Object.defineProperties(plura.ecommerce.CartItem.prototype,{total:{get:function(){return this._total()}}})})();plura=plura||{};plura.events=plura.events||{};
plura.events.Touch=function(b){var d,c,e,a,g,h,f,k,l,m=function(){f=h=g=a=e=c=0;l=k=null};d=$.extend(!0,{},{length:72,target:null},b);this.core=d.target;m();d.target.on("MSPointerDown MSPointerMove MSPointerUp MSPointerOver MSPointerOut touchstart touchend touchmove touchcancel",function(b){b.stopImmediatePropagation();switch(b.type){case "MSPointerUp":case "touchend":b.preventDefault();if(1===c&&0!==g){f=Math.round(Math.sqrt(Math.pow(g-e,2)+Math.pow(h-a,2)));if(f>=d.length){b=e-g;var q=h-a;Math.round(Math.sqrt(Math.pow(b,
2)+Math.pow(q,2)));b=Math.atan2(q,b);k=Math.round(180*b/Math.PI);0>k&&(k=360-Math.abs(k));l=45>=k&&0<=k?"left":360>=k&&315<=k?"left":135<=k&&225>=k?"right":45<k&&135>k?"down":"up"}d.target.trigger("TOUCHSWIPE",{direction:f>=d.length?l:!1})}m();break;case "touchcancel":m();break;case "MSPointerMove":case "touchmove":b.preventDefault();b.originalEvent.touches&&1!==b.originalEvent.touches.length?m():(g=b.originalEvent.pageX||b.originalEvent.touches[0].pageX,h=b.originalEvent.pageY||b.originalEvent.touches[0].pageY,
d.target.trigger("TOUCHMOVE",{delta:{x:e-g,y:a-h},position:{x:g,y:h}}));break;case "MSPointerDown":case "touchstart":b.preventDefault(),c=b.originalEvent.touches?b.originalEvent.touches.length:1,1===c?(e=b.originalEvent.pageX||b.originalEvent.touches[0].pageX,a=b.originalEvent.pageY||b.originalEvent.touches[0].pageY):m()}})};plura=plura||{};plura.form=plura.form||{};
plura.form.Form=function(b){var d,c,e,a,g,h=function(a){var c=d.find("*[name="+a.name+"]"),b,f,e;switch(a.type){case "list":case "select":for(c.empty(),"select"===a.type&&c.append("<option/>"),b=0;b<a.values.length;b+=1)"string"===typeof a.values[b]?(e=a.values[b],f=a.values[b]):(e=void 0!==a.values[b].value?a.values[b].value:a.values[b][a.name],f=a.values[b].label||a.values[b].name||a.values[b].value),$("<option/>").prop({value:e}).appendTo(c).html(f)}a.value&&c.val(a.value)},f=function(c,b){var m,
n,q=c||(a.submit?a.fields.concat([{type:"submit",value:a.submit}]):a.fields);for(m=0;m<q.length;m+=1)if(q[m]instanceof Array||q[m].fields||q[m].type&&q[m].type.match(/^(field)?set$/i))n=$("<fieldset/>").appendTo(b||d).prop({name:q[m].name}),q[m]instanceof Array||$("<legend/>").appendTo(n).text(q[m].label||q[m].name),f(q[m].fields||q[m],n);else{n=q[m];var r=b||d,p=void 0,s=void 0;$("<div/>");var t=p=void 0;switch(n.type){case "select":p=$("<select/>");break;case "list":p=$("<select/>").prop({multiple:!0,
size:n.size||1});break;case "textarea":p=$("<textarea/>");n.wysiwyg&&window.tinyMCE&&(s=tinymce.DOM.uniqueId(),t=$.extend(!0,a.tinyMCE,{editor_selector:s},"number"!==typeof n.wysiwyg?n.wysiwyg:null,{width:300}),p.addClass(s+" tinyMCE").prop({id:s}).appendTo("body").width(p.width()).height(p.height()),tinyMCE.init(t));break;case "file":p=new plura.form.Upload($.extend({name:n.name,target:r},a.upload));break;default:p=n.type&&"date"!==n.type?n.type:"text",p=$("<input/>").prop({type:p}),jQuery.ui&&"date"===
n.type&&p.datepicker({dateFormat:"yy-mm-dd"})}n.disabled&&p.prop({disabled:"disabled"});n.change&&p.change(n.change);n.label&&$("<label/>").text(n.label||n.name).appendTo(r).prop({"for":n.name}).addClass("type-"+(n.type||"text"));n.type&&n.type.match(/file/)||p.prop({name:n.name}).appendTo(r);n.type&&n.type.match(/file/)&&g.push(p);void 0===n.value&&!n.values||n.type&&!n.type.match(/(checkbox|list|select|submit|radio|text|textarea)/)||(n.type&&n.type.match(/(checkbox|radio|submit)/)?(p.prop({value:n.value}),
n.type.match(/(checkbox|radio)/)&&n.checked&&p.prop("checked",!0)):h(n));e[n.name]=n}};this._query=function(){return c._query()};this._params=function(a){return c._params(a)};this.populate=function(a){var c,b;for(c in a)if(a.hasOwnProperty(c)&&(b=d.find("*[name="+c+"]"),b.length))switch(b.prop("type")){case "checkbox":b.prop("checked","0"!==a[c]);break;default:b[0].tagName.match(/textarea/i)&&b.hasClass("tinyMCE")?tinyMCE.get(b.prop("id")).setContent(a[c]||""):b.val(a[c])}};this.refresh=function(a){var c,
d;for(d in a)a.hasOwnProperty(d)&&e[d]&&(c=$.extend(!0,{},e[d],{values:a[d]}),h(c))};this.reset=function(a){c.reset(a)};a=$.extend(!0,{},{alert:{success:"Success! Content updated!",error:"Error! Content not updated! :("},check:null,fields:null,path:null,params:null,reset:!1,send:!0,submit:"Submit",tinyMCE:{mode:"specific_textareas",theme:"advanced",plugins:"fullscreen",theme_advanced_buttons1:"bold,italic,underline,|,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,outdent,indent",
theme_advanced_buttons2:"formatselect,sub,sup,code,fullscreen,link,unlink,|,forecolor,removeformat"}},b);d=$("<form/>").appendTo(a.target);g=[];e={};f();this.core=d;this.uploads=g;c=new plura.form.FormManager($.extend(!0,{},{ajax:a.ajax||{},alert:a.alert||{},check:a.check||{},params:a.params||{}},{path:a.path,reset:a.reset,send:a.send,target:this,type:"getJSON"}));return this};
(function(){Object.defineProperties(plura.form.Form.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(b){this._params(b)}}})})();plura=plura||{};plura.form=plura.form||{};
plura.form.FormManager=function(b){var d,c,e,a=function(a){d.find("input[type=file]").each(function(c){e[c]=new plura.form.Upload($.extend({name:$(this).attr("name"),target:d},a));e[c].core.replaceAll($(this))})},g=function(a){var c=$.extend({},{not:":button, :submit, :reset",checked:!0,selected:!0,upload:!0}),b=d.find(":input").not(c.not);b.not(":checkbox, :radio").val("");c.checked&&b.prop("checked",!1);c.selected&&b.prop("selected",!1);for(c=0;c<e.length;c+=1)e[c].reset(a);window.tinyMCE&&d.find(".tinyMCE").each(function(){tinymce.get($(this).prop("id")).setContent("");
tinymce.get($(this).prop("id")).nodeChanged()})},h=function(){var a=c.path||window.location.href,b=function(a,c){return"string"===typeof a?a:a.alert?a:$.extend(!0,{},a,{alert:c})};console&&console.log(c.ajax.dataType+" | "+c.ajax.type+" | "+a+":"+f());$.ajax({url:a,data:f(),dataType:c.ajax.dataType,type:c.ajax.type,success:function(a){d.trigger("FORM_REQUEST_SUCCESS",b(a,c.alert.complete));!a.success||"true"!==a.success&&1!==a.success?(a.success&&"false"===a.success||0===a.success)&&d.trigger("FORM_PROCESS_ERROR",
b(a,c.alert.error)):(c.reset&&g(!0),d.trigger("FORM_PROCESS_SUCCESS",b(a,c.alert.success)))},error:function(a,c,b){d.trigger("FORM_REQUEST_ERROR",{xhr:a,textStatus:c,errorThrown:b,alert:b})}});d.trigger("FORM_SUBMIT",{alert:c.alert.submit})},f=function(){return d.serialize()+"&"+$.param(c.params||{})};this._query=f;this._params=function(a){void 0!==a&&(c.params=$.extend(!0,c.params||{},a));return c.params};this.reset=g;c=$.extend(!0,{},{ajax:{dataType:"json",type:"GET"},alert:{complete:"Your form was submited.",
error:"There was an error processing your form.",field:"Please correctly fill the % field. Thank you",submit:"Form is being submitted. Please wait.",success:"Your form was successfully processed! Thank you."},check:!1,params:null,path:null,replace:!0,reset:!1,send:!0,target:null,upload:{}},b);d=c.target.core||c.target;e=c.target.uploads||[];this.form=d;c.replace&&a(c.upload);d.submit(function(a){a.preventDefault();window.tinyMCE&&tinyMCE.triggerSave();if(!(a=!c.check))a:{var b,f,e,g;for(b=0;b<c.check.length;b+=
1)for(a=c.check[b],e=a.rules?a.rules instanceof Array?a.rules:[a.rules]:[{alert:a.alert||null}],f=0;f<e.length;f+=1)if(g=plura.utils.String.test([/\./,/#/],a.id)?d.find(a.id):d.find("*[name="+a.id+"]"),e[f].exp&&!plura.utils.String.test(e[f].exp,g.val())||!e[f].exp&&g.val().match(/^\s*$/)){a=e[f].alert||c.alert.field.replace(/%/,a.id);d.trigger("FORM_VALIDATION_ERROR",{alert:a});a=!1;break a}d.trigger("FORM_VALIDATION_SUCCESS");a=!0}a&&c.send&&h()}).find("input[type=reset]").click(function(a){a.preventDefault();
g()})};(function(){Object.defineProperties(plura.form.FormManager.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(b){this._params(b)}}})})();plura=plura||{};plura.form=plura.form||{};plura.form.upload=plura.form.upload||{};
plura.form.upload.File=function(b){var d,c,e,a,g,h,f=function(){c.slideUp("slow",m);h.reset()},k=function(a){$.getJSON(g.process,{action:"delete",file:e.file,path:g.path,type:"upload"},function(b){"true"===b.success&&a&&(f(),c.trigger("FORM_UPLOAD_REMOVE"))})},l=function(a){if(e&&!a)k(!0);else if(!e||e&&a)e||(swf.cancel(g.id),c.trigger("FORM_UPLOAD_CANCEL")),f()},m=function(){$(this).remove()};this.update=function(f){e=f;a=a||$("<input/>").prop({type:"hidden",name:b.name+"[]"}).appendTo(c);a.val(f.file+
"|"+f.name);d.val(g.label.remove)};this.clean=function(){e&&k();d.val(g.label.cancel)};this.reset=l;this.refresh=function(a){h.refresh(a)};g=$.extend(!0,{},{css:{button:{border:"none","float":"right","text-align":"center",width:50},file:{"float":"left",width:"100%"},progress:{"float":"left"}},height:20,label:{cancel:"Cancel",remove:"Delete"},margin:5,swf:null,width:100},b);c=$("<div/>").addClass("file i"+g.id).appendTo(g.target);h=new plura.layout.ProgressBar({target:c,css:{core:$.extend({},g.css.file,
{width:g.width-3*g.margin-g.css.button.width})}});d=$("<input/>").prop({type:"button"}).val(g.label.cancel).addClass("delete").appendTo(c).click(function(a){l()});this.core=c;c.css($.extend({},g.css.file,{"margin-bottom":g.margin}));d.css($.extend({},g.css.button,{height:g.height}));return this};plura=plura||{};plura.form=plura.form||{};
plura.form.Upload=function(b){var d,c,e,a,g,h,f,k=function(){d.children(".files").slideUp("slow",function(){$(this).remove()})},l=function(a){if(c){for(var b in c)c.hasOwnProperty(b)&&(c[b].reset(a),delete c[b]);c=null}k()},m=function(a){a.stopImmediatePropagation();1===d.children(".files").children().length&&l()},n=function(a){var c=$("<div/>");g=swfobject.getObjectById(a.id);c.replaceAll(d);$("body").prepend(d);$("#"+a.id).css({left:h.position().left,position:"absolute",top:h.position().top,zIndex:100});
d.replaceAll(c)},q=function(a,c,b){"true"===b.success&&f.instances["i"+a].update(c,b)},r=function(a,c){f.instances["i"+a].init(c)},p=function(a,c,b){f.instances["i"+a].refresh(c,b)},s=function(a){};this.init=function(b){a.multiple||!a.multiple&&!c?(c=c||{},c["i"+b]=new plura.form.upload.File($.extend(!0,{},a.file,{id:b,name:a.name,path:plura.utils.String.path(a.path,a.process||plura.constants.PHP),process:a.process||plura.constants.PHP,swf:g,target:d.children(".files").length?d.children(".files"):
$("<div/>").appendTo(d).addClass("files").css($.extend({},a.css.files,{"margin-top":a.margin,padding:a.margin+"px "+a.margin+"px 0 "+a.margin+"px",width:a.width-2*a.margin})),width:a.width})),c["i"+b].core.on("FORM_UPLOAD_CANCEL FORM_UPLOAD_REMOVE",m)):!a.multiple&&c&&c["i"+b].clean()};this.refresh=function(a,b){c["i"+a].refresh(b)};this.reset=l;this.update=function(a,b){c["i"+a].update(b)};f=plura.form.upload;f.count=void 0===f.count?0:f.count+1;f.instances=f.instances||{};f.instances["i"+f.count]=
this;f.complete=f.complete||q;f.init=f.init||r;f.refresh=f.refresh||p;f.test=f.test||s;e=f.count;a=$.extend(!0,{},{css:{files:{"float":"left","background-color":"#e0e0e0"},progress:{"float":"left"},trigger:{border:"none","float":"right","text-align":"center",width:70}},file:{},label:{cancel:"Cancel",remove:"Delete",upload:"Upload"},height:30,limit:0,margin:5,multiple:!1,path:"",obj:"plura.form.upload",swf:{params:{allowscriptaccess:"always",menu:"false",wmode:"transparent"},version:"10.0"},process:null,
width:220},b);d=$("<div/>").css({position:"relative"}).addClass("upload i"+e).appendTo(a.target);new plura.layout.ProgressBar({target:d,css:{core:$.extend({},a.css.progress,{width:a.width-a.css.trigger.width-a.margin,height:a.height})}});h=$("<input/>").prop({type:"button",value:a.label.upload}).addClass("trigger").appendTo(d);this.core=d;d.css({width:a.width});h.css($.extend({},a.css.trigger,{height:a.height}));(function(){var c=$("<div/>").attr({id:"plura_form_upload_"+e}).appendTo(d),b=h.outerHeight(!0),
f={id:e,limit:a.limit,multiple:a.multiple,obj:a.obj,path:plura.utils.String.path(a.path,a.process||plura.constants.PHP),process:a.process||plura.constants.PHP,type:"upload"},k=h.outerWidth(!0);swfobject.embedSWF(plura.constants.SWF,c.attr("id"),k,b,a.swf.version,null,f,a.swf.params,null,n)})();return this};plura=plura||{};plura.fx=plura.fx||{};
plura.fx.Center=function(b){var d=$.isPlainObject(b.target)?b.target:b.target||$("body"),c=b.dimensions&&b.dimensions.height?b.dimensions.height:b.obj.height(),e=b.dimensions&&b.dimensions.width?b.dimensions.width:b.obj.width(),a=$.isPlainObject(d)?d.height||0:d.height(),g=$.isPlainObject(d)?d.left||0:d.position().left,h=$.isPlainObject(d)?d.top||0:d.position().top,d=$.isPlainObject(d)?d.width||0:d.width();b.obj.css({top:(a-c)/2+h,left:(d-e)/2+g,position:"absolute"})};plura=plura||{};
plura.fx=plura.fx||{};
plura.fx.Parallax=function(b){var d,c,e,a,g,h,f,k,l,m=function(){return{height:g.dimensions&&g.dimensions.height?g.dimensions.height:g.target.height(),width:g.dimensions&&g.dimensions.width?g.dimensions.width:g.target.width()}},n=function(){return f.x+c.x>f.x&&f.x+c.x<f.x+f.width&&f.y+c.y>f.y&&f.y+c.y<f.y+f.height?!0:!1};g=$.extend(!0,{},{enabled:{x:!0,y:!0},dimensions:null,rectangle:{width:0,height:0,y:0,x:0},restrict:{x:!0,y:!0},speed:8,target:null},b);d=g.enabled;f=g.rectangle;k=g.restrict;l=g.target;
e=l.position().left;a=l.position().top;c={x:0,y:0};h={x:0,y:0};$(document).mousemove(function(a){c={x:a.pageX-l.parent().offset().left-f.x,y:a.pageY-l.parent().offset().top-f.y}});setInterval(function(){if(!(!f||!f.width&&d.x||!f.height&&d.y)){var b,r;h.x=isNaN(h.x)?0:h.x;h.y=isNaN(h.y)?0:h.y;d.x&&(e=n()?c.x:e,f.width<m().width&&k.x||f.width>m().width&&!k.x?(b=-e*((m().width-f.width)/f.width)+f.x,h.x+=(b-l.position().left)/g.speed):d.x&&f.width>m().width&&k.x&&(b=((f.width-l.width)/2+e-l.position().left)/
g.speed,h.x+=b),1<Math.abs(b-l.position().left)&&l.css({left:h.x}));d.y&&(a=n()?c.y:a,f.height<m().height&&k.y||f.height>m().height&&!k.y?(r=-a*((m().height-f.height)/f.height)+f.y,h.y+=(r-l.position().top)/g.speed):d.x&&f.width>m().width&&k.x&&(r=((f.height-l.height)/2+a-l.position().top)/g.speed,h.y+=r),1<Math.abs(r-l.position().top)&&l.css({top:h.y}));l.trigger("PARALLAX",{dimensions:m(),inside:n(),mouse:c,rectangle:f,target:l,position:h})}},13);return this};plura=plura||{};
plura.fx=plura.fx||{};
plura.fx.Resize=function(b){var d,c,e={increase:!0,height:null,inside:!1,target:null,width:null},a,g,h=function(){var b=g.target;d=b?$.isPlainObject(b)&&b.height?b.height:$.isPlainObject(b)?a.height():b.height():$(window).height();c=b?$.isPlainObject(b)&&b.width?b.width:$.isPlainObject(b)?a.width():b.width():$(window).width();!b||$.isPlainObject(b)&&!b.x||$.isPlainObject(b)||b.position();!b||$.isPlainObject(b)&&!b.y||$.isPlainObject(b)||b.position()},f=function(){var b,f;if(g.increase||!g.increase&&
(a.height()>d||a.width()>c))a.width()/a.height()>c/d&&g.inside||a.width()/a.height()<c/d&&!g.inside?(b=c/a.width()*a.width(),f=b*a.height()/a.width()):(f=d/a.height()*a.height(),b=f*a.width()/a.height());a.css({width:b,height:f});g.center&&plura.fx.Center({obj:g.obj,target:g.target,dimensions:g.center.dimensions||!1})};b.obj&&(g=$.extend(!0,{},e,b),a=g.obj,h(),f())};plura=plura||{};plura.layout=plura.layout||{};
plura.layout.LoaderBar=function(b){var d;d=new plura.layout.ProgressBar(b);b.loader.core.on("LOADER_COMPLETE_ITEM",function(c,b){d.refresh(b.progress)})};plura=plura||{};plura.layout=plura.layout||{};plura.layout.navigation=plura.layout||{};
plura.layout.navigation.Nav=function(b){var d,c,e,a,g=function(a,b){b&&(!b||d&&d[0]===a[0])||(b?a.addClass("active"):a.removeClass("active"));!b||d&&d[0]===a[0]||(d&&g(d,!1),d=a,c.trigger("SELECT",a.data()))},h=function(a){c.find(".i"+a).length?g(c.find(".i"+a),!0):e[a].data({active:!0})},f=function(c){e[c].prop({src:a.path+(a.data[c].thumb||a.data[c].file)})},k=function(a){g($(a.currentTarget),!0)},l=function(b){var d,g,l,p;b=$(b.target);var s=b.data("index");(a.width||a.height)&&plura.fx.Resize({target:{width:a.width,
height:a.height},obj:b,inside:!0});a.wrap?(l=b.parent(),l=a.wrap(b).data(b.data()).appendTo(l)):l=b;b.data("active")&&h(b.data("index"));l=l.addClass("item i"+b.data("index")).click(k);p=l.prev();a.css&&(d=0!==s%a.limit&&0<s?p.width()+p.position().left+a.margin:0,g=0!==s%a.limit&&0<s?p.position().top:0===s%a.limit&&0<s?p.position().top+p.height()+a.margin:0,l.css({position:"absolute",left:d,top:g}));a.parallax&&(d=0<s&&p.position().left+p.width()>d+l.width()?p.position().left+p.width():d+l.width(),
g=0<s&&p.position().top+p.height()>g+l.height()?p.position().top+p.height():g+l.height(),l.parent().width(d).height(g));b.fadeIn();e[s+1]&&f(s+1);c.trigger("COMPLETE_ITEM",s)};this.select=h;a=$.extend(!0,{},{css:{core:{position:"absolute",zIndex:2},parallax:{core:{position:"absolute",zIndex:1},holder:{position:"absolute",zIndex:2}}},height:null,limit:0,margin:5,overflow:!1,path:"",parallax:{},text:!1,width:null},b);c=$("<div/>").appendTo(a.target||"body").addClass(["nav",a.text?"txt":"img"].join(" "));
e=[];(function(b){var d,g;a.parallax&&(g=$("<div/>").prependTo(c).addClass("holder"),d=$.extend(!0,{rectangle:{x:0,y:0},target:g},a.parallax),$("<div/>").prependTo(c).addClass("parallax").css($.extend({},a.css.parallax.core,{width:d.rectangle.width,height:d.rectangle.height})),new plura.fx.Parallax(d),a.css&&(g.css(a.css.parallax.holder),a.overflow||c.css({overflow:"hidden",width:d.rectangle.width,height:d.rectangle.height})));for(d=0;d<b.length;d+=1)a.text?$("<a/>").appendTo(g||c).addClass("item i"+
d).data({index:d}).html(d+1).click(k):(e[d]=$(new Image).appendTo(g||c).data({index:d}).hide().load(l),0===d&&f(d))})(a.data);a.css&&c.css(a.css.core);this.core=c;return this};plura=plura||{};plura.layout=plura.layout||{};
plura.layout.ProgressBar=function(b){var d,c,e;this.refresh=function(a){c.height(d.height()).width(d.width()*a/100).show();100===a&&e.hide&&d.stop().fadeOut("slow")};this.reset=function(){c.fadeIn()};e=$.extend(!0,{},{bottom:!0,css:{core:{width:200,height:20,border:"2px solid #000"},bar:{backgroundColor:"#000"}},hide:!1,horizontal:!0,target:null},b);d=$("<div/>").appendTo(e.target||"body").addClass("plura progress").css(e.css.core);c=$("<div/>").appendTo(d).addClass("bar").css(e.css.bar).hide();(function(a){a.height(a.height()-
2*parseInt(a.css("border-top-width"),10)).width(a.width()-2*parseInt(a.css("border-top-width"),10))})(d);this.core=d;this.bar=c};plura=plura||{};plura.layout=plura.layout||{};
plura.layout.Refresh=function(b){var d,c,e=0,a,g,h=function(a){var b=c.format?c.format(a):a;c.fade?d.fadeOut(c.speed,function(){$(this).html(b).fadeIn(c.speed)}):d.html(b);d.trigger("CHANGE");c.refresh&&(clearInterval(g),g=setInterval(k,c.time))},f=function(a,b){var d,f=[],e;for(d in c.data)c.data.hasOwnProperty(d)&&(e=Math.floor(d/b),f[e]=f[e]||[],f[e].push(a[d]));return f},k=function(){"string"===typeof c.data?c.json?$.getJSON(c.data,null,function(a){h(a)}):$.get(c.data,null,function(a){h(a)}):
"object"===typeof c.data&&(h(a[e%a.length]),e+=1)};c=$.extend(!0,{},{data:!1,fade:!0,format:null,json:!1,limit:1,refresh:!0,speed:"slow",target:null,time:1E4},b);d=$("<div/>").appendTo(c.target||"body").addClass("refresh core");"object"===typeof c.data&&(a=f(c.data,c.limit));k()};plura=plura||{};plura.layout=plura.layout||{};
plura.layout.Slideshow=function(b){var d={auto:!0,cache:!1,center:!1,controls:!1,css:{core:{position:"relative"},media:{core:{position:"relative"},item:{position:"absolute"}}},data:null,height:null,id:"",navigation:{},outside:!1,path:"",resize:!1,target:null,timer:8E3,width:null,video:null},c,e,a,g=0,h,f,k,l,m,n,q,r=this,p=function(b){n&&clearTimeout(n);f&&f.core.remove();var c=[],d;for(d=0;d<b.length;d+=1)"string"===typeof b[d]?c.push({file:b[d]}):c.push(b[d]);a=c;1<a.length&&(k.navigation&&(f=new plura.layout.navigation.Nav($.extend(!0,
{data:a,path:k.path,target:e},k.navigation)),r.navigation=f,f.core.on("COMPLETE_ITEM SELECT",z)),k.swipe&&(m=new plura.events.Touch($.extend({target:h},"object"===typeof k.swipe?k.swipe:null)),m.core.on("TOUCHMOVE TOUCHSWIPE",w)));s(g,!0)},s=function(b,d){d&&(void 0!==c&&c.removeClass("active").addClass("inactive").fadeOut(function(){$(this).remove()}),g=b,c=t(a[g]).addClass("item active i"+g),e.trigger("CHANGE",{index:g}),f&&f.select(g),k.css&&c.css(k.css.media.item))},t=function(a){var b,c=a.data&&
a.file,d=c?$("<div/>").addClass("mixed").appendTo(h):h,f;a.data&&(b=$("<div/>").html(a.data).appendTo(d).addClass("data").hide().fadeIn());if(a.file)if(a.file.match(/\.(gif|jpg|png)$/i)||a.type&&a.type.match(/image/i))a=k.cache?k.path+a.file:k.path+a.file+"?"+(new Date).getTime(),b=$(new Image).load(v).appendTo(d).prop({src:a}).hide();else if(a.file.match(/\.(mp4)$/i)||a.type&&a.type.match(/video/i))f=new plura.media.Video($.extend({src:k.path+a.file,target:d},k.video)),b=f.core.on("METADATA",A);
return $(c?d:b).data({video:f||!1})},u=function(){s(g<a.length-1?g+1:0,!0)},y=function(){s(0<g?g-1:a.length-1,!0)},v=function(b){b=$(b.target).css({width:"auto",height:"auto"}).fadeIn();var c=b.height(),d=k.resize&&k.resize.target?k.resize.target.height():k.height||h.height(),f=b.width(),g=k.resize&&k.resize.target?k.resize.target.width():k.width||h.width();k.resize&&(k.outside&&(f>d||c>d)||!k.outside)&&plura.fx.Resize({center:"boolean"===typeof k.resize||void 0===k.resize.center?!1:k.resize.center,
inside:"boolean"===typeof k.resize||void 0===k.resize.inside?!0:k.resize.inside,obj:b,target:{width:g,height:d}});k.center&&plura.fx.Center({target:{width:g,height:d},obj:b});k.auto&&1<a.length&&(clearTimeout(n),n=setTimeout(u,k.timer));e.trigger("COMPLETE_ITEM",b)},A=function(a){a.stopImmediatePropagation();e.trigger("COMPLETE_ITEM",$(a.target))},z=function(a,b){a.stopImmediatePropagation();switch(a.type){case "SELECT":b.index!==g&&s(b.index,!0)}e.trigger("NAVIGATION_"+a.type,b)},w=function(a,b){a.stopPropagation();
var d;switch(a.type){case "TOUCHMOVE":c.css({left:-b.delta.x});break;case "TOUCHSWIPE":d=b.direction&&b.direction.match(/(left|right)/)?("left"===b.direction?-1:1)*c.outerWidth():0,c.animate({left:d},"slow"),"left"===b.direction?u():"right"===b.direction&&y()}},x=function(){var a;for(a=0;a<q.items.length;a+=1)q.items[a].pause(!0,!0)};this._index=function(a){if(void 0===a)return g;s(a,!0)};this._items=function(b){if(void 0===b)return a;p(b)};this.next=u;this.pause=function(a,b){clearTimeout(n);var d=
void 0!==a?a:!l;d?d&&b&&c.data("video")&&c.data("video").pause(!0):n=setTimeout(u,k.timer);l=d};this.previous=y;(function(){k=$.extend({},d,b);e=$("<div/>").appendTo(k.target||"body").addClass("plura slideshow "+k.id);h=$("<div/>").appendTo(e).addClass("media");l=!1;"string"===typeof k.data?$.getJSON(k.data,function(a){p(a)}):k.data&&"object"===typeof k.data&&p(k.data);k.css&&(e.css(k.css.core),h.css(k.css.media.core));r.core=e;r.media=h;q=plura.layout.Slideshow;q.items=q.items||[];q.stop=q.stop||
x;q.items.push(r)})();return this};(function(){Object.defineProperties(plura.layout.Slideshow.prototype,{index:{get:function(){return this._index()},set:function(b){this._index(b)}},items:{get:function(){return this._items()},set:function(b){this._items(b)}}})})();plura=plura||{};plura.layout=plura.layout||{};
plura.layout.Social=function(b){var d,c=function(a){var b=$("<div/>").appendTo(d).addClass("fb-like"),c=[];a=$.extend(!0,{},a,{height:"button_count"===a.layout?21:"box_count"===a.layout?65:a.show_faces?80:35,href:a.href||window.location.href});for(var f in a)a.hasOwnProperty(f)&&c.push(f+"="+(a[f]||""));$("<iframe/>").appendTo(b).css({width:a.width,height:a.height,border:"none",overflow:"hidden"}).prop({allowTransparency:"true",frameborder:0,scrolling:"no",src:"//www.facebook.com/plugins/like.php?"+
c.join("&")})},e=function(a){var b=$("<div/>").appendTo(d).addClass("twitter"),c=$("<a/>").appendTo(b).prop({href:"http://twitter.com/share"}).addClass("twitter-share-button").html("Tweet"),f=document.createElement("script"),e;for(e in a)a.hasOwnProperty(e)&&("related"===e?a[e].user&&c.attr("data-"+e,a[e].user+(a[e].text?":"+a[e].text:"")):a[e]&&c.attr("data-"+e,a[e]));$(f).attr({type:"text/javascript",src:"http://platform.twitter.com/widgets.js"}).appendTo(b)};d=$("<div/>").addClass("share");b=$.extend(!0,
{},{like:{action:"like",colorsheme:"light",font:null,href:null,layout:"standard",show_faces:!0,width:450},twitter:{count:"horizontal",related:{text:null,via:null},text:null,via:null,url:null},target:null},b);b.target&&d.appendTo(b.target);b.like&&c(b.like);b.twitter&&e(b.twitter);return d};plura=plura||{};plura.layout=plura.layout||{};
plura.layout.Table=function(b){var d,c,e=function(c){a();var e,f,k=[],l={};for(e in c[0])c[0].hasOwnProperty(e);for(e=0;e<c.length;e+=1)for(f in c[e])c[e].hasOwnProperty(f)&&(k[e]=k[e]||[],l[f]=l[f]||{rowspan:1},b&&b.merge&&0<e&&c[e][f]===c[e-1][f]&&("string"===typeof b.merge?(new RegExp(b.merge)).test(f):1)?(l[f].rowspan+=1,k[l[f].r][l[f].c].rowspan=l[f].rowspan):(l[f]={rowspan:1,r:e,c:k[e].length},k[e].push({value:c[e][f],span:l[f].rowspan})));var m,l=$("<table/>").appendTo(d);for(f=0;f<k.length;f+=
1)for(e=$("<tr/>").appendTo(l),c=0;c<k[f].length;c+=1)m=$("<td/>").appendTo(e).html(k[f][c].value||k[f][c]),k[f][c].rowspan&&1<k[f][c].rowspan&&m.prop({rowspan:k[f][c].rowspan})},a=function(){d.empty()};this.refresh=e;this.empty=a;c=$.extend(!0,{},{limit:0,merge:!0,target:null},b);this.core=d=$("<div/>").appendTo(c.target||"body").addClass("table core "+(c.classes||""));c.data&&e(c.data);return this};plura=plura||{};plura.media=plura.media||{};
plura.media.Audio=function(b){var d,c,e,a,g,h,f=function(b){console.log("B:"+a);a=void 0===b?!a:b;console.log("A:"+a);a?d.find(".play").removeClass("active").html(e.labels.play):d.find(".play").addClass("active").html(e.labels.pause);g?g.pause(a):a||g||q()},k=function(a){var b=$("<div/>").attr({id:"plura_media_audio_"+c}).appendTo(d);a={content:a,id:c,obj:"plura.media.Audio",type:"audio"};swfobject.embedSWF(plura.constants.SWF,b.attr("id"),"0","0","10.0.0",null,a,null,null,m)},l=function(b){f(!a)},
m=function(a){g=swfobject.getObjectById(a.id)},n=function(a){for(var b in h.instances)h.instances.hasOwnProperty(b)&&!b.match("i"+a)&&h.instances[b].pause(!0)},q=function(){e.data?k(e.data):e.path&&$.get(e.path,function(a){k(a)})};this.fade=function(a){d.find(".menu").fadeIn("slow")};this.pause=f;h=plura.media.Audio;h.count=void 0===h.count?0:h.count+1;h.instances=h.instances||{};h.instances["i"+h.count]=this;h.pause=h.pause||n;c=h.count;e=$.extend(!0,{},{auto:!0,data:null,controls:!0,css:{flash:{position:"relative",
height:0,width:0},test:{position:"absolute",zIndex:1E3,width:400,height:400}},fade:!0,labels:{pause:"Pause",play:"Play"},path:null,params:null,target:"body",test:!1},b);(function(){d=$("<div/>").appendTo(e.target).addClass("p audio").css({position:"relative"});var a=$("<ul/>").appendTo(d).addClass("menu controls");e.controls&&$("<li/>").appendTo(a).click(l).addClass("play");f(!e.auto)})();this.core=d};plura=plura||{};plura.media=plura.media||{};
plura.media.Video=function(b){var d,c,e=!0,a,g,h=this,f=function(b){a.empty();var c,d=b instanceof Array?b:[b],e;for(b=0;b<d.length;b+=1)c=d[b].src||d[b],e=d[b].type||"video/"+c.match(/\.([^.]+)$/)[1],$("<source/>").prop({src:c,type:e}).appendTo(a);return h},k=function(b){(e=void 0===b?!e:b)?(c.addClass("pause"),a[0].pause()):(c.removeClass("pause"),a[0].play())},l=function(b){void 0!==b&&(a[0].volume=b);return a[0].volume},m=function(a){a.stopImmediatePropagation();k()};this.pause=k;this.prop=function(b){a.prop(b);
return h};this.src=f;this.volume=l;d=new plura.net.Client;b=$.extend(!0,{},{autoplay:!0,controls:!0,pause:!0,preload:!0,loop:!0,wrap:!1},b);g={autoplay:b.autoplay,controls:b.controls,loop:b.loop,height:b.height,preload:b.preload,width:b.width,poster:b.poster};a=$("<video/>").prop(g).on("loadedmetadata",function(a){c.trigger("METADATA",{width:this.videoWidth,height:this.videoHeight})});c=b.wrap?$("boolean"===typeof b.wrap?"<div/>":b.wrap).append(a).addClass("video"):a;c.appendTo(b.target||"body");
b.src&&f(b.src);h.core=c;if(b.pause&&!b.controls||d.data.ios)a.on("click touchstart",m),b.wrap&&c.click(m);b.volume&&l(b.volume);d.data.ios||k(!b.autoplay);return this};plura=plura||{};plura.net=plura.net||{};
plura.net.Client=function(b){var d;d=navigator.userAgent;var c=Boolean(d.match(/Android/i)),e=Boolean(d.match(/(explorer|MSIE)/i)),a=Boolean(d.match(/iPad/i)),g=Boolean(d.match(/iPhone/i)),h=Boolean(d.match(/iPod/i)),g=g?"iPhone":a?"iPad":h?"iPod":null,f=Boolean(null===document.location.href.match(/https?:\/\//)),k=Boolean(g||c||d.match(/Windows.+Touch/i)),l=parseInt(navigator.appVersion,10);e&&(l=parseInt(navigator.appVersion.match(/msie ([0-9\.]+)/i)[1],10));d={agent:d,android:c,ie:e,ios:g,ipad:a,
ipod:h,offline:f,touch:k,version:l};c=[];a=b&&b.ie?b.ie:11;if(d.ie){if(c.push("ie","ie"+d.version),d.version<a)for(c.push("ie_lte"+d.version),e=d.version;e<a;e+=1)c.push("ie_lt"+(e+1))}else d.ios?c=c.concat(["ios",d.ios.toLowerCase()]):d.android&&c.push("android");d.offline&&c.push("offline");c.push((d.touch?"":"no-")+"touch");d.classes=c;this.data=d;b&&b.classes&&$("body").addClass(d.classes.join(" "))};plura=plura||{};plura.net=plura.net||{};
plura.net.URLManager=function(b){var d={analytics:!0,lang:!0,separator:"#"},c,e,a,g,h,f,k=function(a,b,c,d,e){window._gaq&&(a=["_trackEvent",a,b,c,d],void 0!==e&&!0===e&&a.push(e),_gaq.push(a))},l=function(a){var b=[];a&&c&&b.push(c);h&&b.push(h);return b.join("/")},m=function(a){void 0!==a&&a!==h&&(h=a,e.push(h));window.location.href="#!/"+l(!0);g.analytics&&(a="/"+l(!0),window._gaq&&_gaq.push(["_trackPageview",a]))};this._history=function(){return e};this._index=function(){return a};this._lang=
function(a){void 0!==a&&(c=a,m());return c};this._path=function(a){void 0!==a&&m(a);return h};this._root=function(){return f};this._url=function(){return f+"#!/"+l(!0)+"/"};this.event=function(){k.apply(null,arguments)};this.perma=function(a){return a.match(f+".*?([^=]*[^/])/?$")[1]};(function(){var k=window.location.href;g=$.extend(!0,{},d,b);e=[];a=0;f=k.match(/[^#]+/)[0];k.match(/#!\/(.+)/)&&(k=k.match(/#!\/(.+)/)[1].replace(/\/$/,"").split(/\//),g.lang&&k[0].match(/^[a-z]{2}$/)&&(c=k.shift()),
h=k.join("/"),e.push(h))})()};(function(){Object.defineProperties(plura.net.URLManager.prototype,{history:{get:function(){return this._history()}},index:{get:function(){return this._index()}},lang:{get:function(){return this._lang()},set:function(b){this._lang(b)}},path:{get:function(){return this._path()},set:function(b){this._path(b)}},root:{get:function(){return this._root()}},url:{get:function(){return this._url()}}})})();plura=plura||{};plura.templates=plura.templates||{};
plura.templates.alert=plura.templates.alert||{};plura.templates.alert.Slide=function(b){var d,c;this.refresh=function(b,a){clearTimeout(c);d.html(a).stop(!0,!0).slideDown().addClass(b?"success":"error").removeClass(b?"error":"success");c=setTimeout(function(){d.slideUp()},2E3)};d=$("<p/>").appendTo(b.target||"body").addClass("alert").hide()};plura=plura||{};plura.templates=plura.templates||{};plura.templates.checkout=plura.templates.checkout||{};
plura.templates.checkout.end=plura.templates.checkout.end||{};
plura.templates.checkout.end.Form=function(b){var d;this._items=function(b){d.params={items:b}};b=$.extend(!0,{},{labels:{check:{email:{empty:"Please insert your email. Thank you!",invalid:"Your email address is invalid."},name:"Please insert your first and last name. Thank you!",message:"Please include a message. Thank you!"},fields:{email:"Email",name:"Name",message:"Message"}}},b);d=new plura.form.Form({check:[{id:"user_email",rules:[{alert:b.labels.check.email.empty},{exp:String(plura.constants.REGEX_EMAIL),
alert:b.labels.check.email.invalid}]},{id:"user_message",alert:b.labels.check.message},{id:"user_name",alert:b.labels.check.name}],fields:[[{name:"user_name",label:b.labels.fields.name},{name:"user_email",label:b.labels.fields.email},{name:"user_message",type:"textarea",label:b.labels.fields.message}]],params:$.extend({type:"checkout"},b.params),reset:!0,target:b.target});d.core.on("FORM_PROCESS_ERROR FORM_PROCESS_SUCCESS FORM_VALIDATION_ERROR",function(b,d){switch(b.type){case "FORM_PROCESS_ERROR":alert(d.alert);
break;case "FORM_PROCESS_SUCCESS":alert(d.alert);break;case "FORM_VALIDATION_ERROR":alert(d.alert)}}).addClass("big check-out");this.core=d.core};(function(){Object.defineProperties(plura.templates.checkout.end.Form.prototype,{items:{set:function(b){this._items(b)}}})})();plura=plura||{};plura.templates=plura.templates||{};plura.templates.checkout=plura.templates.checkout||{};plura.templates.checkout.end=plura.templates.checkout.end||{};
plura.templates.checkout.end.List=function(b){var d,c,e;this.refresh=function(a){var b,c,f,k=$("<ul/>").addClass("items");d.empty().append(k).prepend(e);for(b=0;b<a.length;b+=1){c=a[b];var l=$("<li/>").addClass("group");$("<span/>").text(c.name).addClass("group-label").appendTo(l);$("<ul/>").appendTo(l).addClass("group-items");c=l.appendTo(k);for(f in a[b].items)if(a[b].items.hasOwnProperty(f)){var l=a[b].items[f],m=$("<li/>").addClass("item item-"+l.data.ID),n=$("<ul/>").addClass("subitems").appendTo(m);
$("<li/>").addClass("icon").css("background-image","url("+l.data.img.dark+")").appendTo(n);$("<li/>").addClass("label").appendTo(n).html(l.data.title);m.appendTo(c)}}};c=$.extend(!0,{},{labels:{title:"List"}},b);d=$("<div/>").appendTo(b.target).addClass("list");e=$("<div/>").addClass("title").text(c.labels.title);this.core=d};(function(){Object.defineProperties(plura.templates.checkout.end.List.prototype,{items:{set:function(b){this.refresh(b)}}})})();plura=plura||{};
plura.templates=plura.templates||{};plura.templates.checkout=plura.templates.checkout||{};plura.templates.checkout.End=function(b){var d,c,e;this._items=function(a){void 0!==a&&(d.items=a,e.list&&(c.items=a))};e=$.extend(!0,{},{list:!0},b);b=$("<div/>").addClass("checkout-end");d=new plura.templates.checkout.end.Form({path:e.process,params:e.params,target:b});e.list&&(c=new plura.templates.checkout.end.List($.extend({target:b},e.list)));this.core=b;this.form=d;this.list=c};
(function(){Object.defineProperties(plura.templates.checkout.End.prototype,{items:{get:function(){return this._items()},set:function(b){this._items(b)}}})})();plura=plura||{};plura.templates=plura.templates||{};
plura.templates.Checkout=function(b){var d,c,e,a;e=$.extend(!0,{},{end:!0,labels:{sequence:{end:"Checkout"}}},b);d=$("<div/>").appendTo(b.target).addClass("checkout");a=new plura.templates.Sequence({items:function(){var a;e.end&&(c=new plura.templates.checkout.End(e.end),a=[{name:"end",label:e.labels.sequence.end,obj:c}]);return b.sequence?b.sequence.concat(a):a}(),parent:e.parent,target:d});a.core.on("CHANGE COMPLETE COMPLETE_ITEM EXIT",function(b,e){b.stopImmediatePropagation();switch(b.type){case "COMPLETE":var f,
k;if(1<a.items.length)for(k=[],f=0;f<a.items.length-1;f+=1)a.items[f].obj.cart&&k.push({name:a.items[f].name||"i"+f,items:a.items[f].obj.cart.items});c.items=k;break;case "EXIT":d.trigger("EXIT")}});this.core=d;this.sequence=a};plura=plura||{};plura.templates=plura.templates||{};plura.templates.sequence=plura.templates.sequence||{};
plura.templates.sequence.Breadcrumbs=function(b){var d,c,e,a,g=function(){d.trigger("PARENT")},h=function(a){d.trigger("SEQUENCE",$(a.target).data("index"))};this.refresh=function(a){var b,c;for(b=0;b<a.items.length;b+=1)c=[],e[b].off("click",h).removeClass("active completed disabled enabled"),a.items[b].completed||!b||b&&a.items[b-1].completed?(a.items[b].completed?c.push("completed"):c.push("enabled"),e[b].click(h)):c.push("disabled"),a.index===b&&c.push("active"),e[b].addClass(c.join(" "))};c=
$.extend(!0,{},{},b);d=$("<div/>").appendTo(c.target).addClass("breadcrumbs");(function(){var b;d.empty();e=[];c.parent&&$("<div/>").addClass("breadcrumbs-parent").text(c.parent).appendTo(d).click(g);a=$("<div/>").addClass("breadcrumbs-sequence-items").appendTo(d);for(b=0;b<c.items.length;b+=1)e[b]=$("<div/>").addClass("breadcrumbs-sequence-item breadcrumbs-sequence-item-"+b).text(c.items[b].label||b).data("index",b).appendTo(a)})();this.core=d};plura=plura||{};plura.templates=plura.templates||{};
plura.templates.sequence=plura.templates.sequence||{};
plura.templates.sequence.PreviousNext=function(b){var d,c,e,a,g=function(a){a.stopImmediatePropagation();d.trigger("NEXT")},h=function(a){a.stopImmediatePropagation();d.trigger("PREVIOUS")},f=function(a){a.stopImmediatePropagation();d.trigger("PARENT")};this.refresh=function(c){a.off("click",h).off("click",f);e.off("click",g);if(!c.index&&b.parent||0<c.index)a.addClass("active").on("click",c.index?h:f);else a.removeClass("active");c.index<c.items.length-1&&c.items[c.index].completed?e.on("click",
g).addClass("active"):e.removeClass("active")};c=$.extend(!0,{},{},b);d=$("<div/>").appendTo(c.target).addClass("previous-next");e=$("<div/>").appendTo(d).addClass("previous-next-item next");a=$("<div/>").appendTo(d).addClass("previous-next-item previous");this.core=d};plura=plura||{};plura.templates=plura.templates||{};
plura.templates.Sequence=function(b){var d={chained:!0,navigation:{breadcrumbs:!0,previous_next:!0}},c,e,a,g,h,f,k,l,m,n=this,q=function(b){b!==a&&(g=a,a=b,r())},r=function(){var b;b=void 0===h[a].obj.completed||h[a].obj.completed;if(h[a].completed=b)c.trigger("COMPLETE_ITEM",{index:a}),a===h.length-1&&c.trigger("COMPLETE");else if(f.chained)for(b=a+1;b<h.length;b+=1){var d=b;h[d].completed=!1;"function"===typeof h[d].obj.reset&&h[d].obj.reset()}for(b=0;b<h.length;b+=1)d=[],h[b].obj.core.removeClass("active completed disabled enabled"),
h[b].completed||!b||b&&h[b-1].completed?void 0===h[b].obj.completed||h[b].obj.completed?d.push("completed"):d.push("enabled"):d.push("disabled"),a===b&&d.push("active"),h[b].obj.core.addClass(d.join(" "));void 0!==g&&c.removeClass("sequence-"+g);c.addClass("sequence-"+a);m&&m.refresh({index:a,items:h});l&&l.refresh({index:a,items:h})},p=function(a,b){a.stopImmediatePropagation();switch(a.type){case "PARENT":c.trigger("EXIT");break;case "SEQUENCE":q(b)}},s=function(b){b.stopImmediatePropagation();
switch(b.type){case "PARENT":c.trigger("EXIT");break;case "NEXT":q(a+1);break;case "PREVIOUS":q(a-1)}},t=function(a,b){a.stopImmediatePropagation();r(b)};this._items=function(){return h};(function(){f=$.extend(!0,{},d,b);c=$("<div/>").appendTo(f.target).addClass("sequence");if(f.navigation){k=$("<div/>").appendTo(c).addClass("sequence-nav");var a={target:k,items:f.items,parent:f.parent};f.navigation.breadcrumbs&&(l=new plura.templates.sequence.Breadcrumbs($.extend(!0,{},f.navigation.breadcrumbs,a)),
l.core.on("PARENT SEQUENCE",p));f.navigation.previous_next&&(m=new plura.templates.sequence.PreviousNext($.extend(!0,{},f.navigation.previous_next,a)),m.core.on("PARENT NEXT PREVIOUS",s))}var a=f.items,g;if(h){for(g=0;g<h.length;g+=1)h[g].obj.core.off("REFRESH",t).removeClass("completed");h=null}e&&e.remove();var v;e=$("<div/>").appendTo(c).addClass("sequence-items");h=[];for(g=0;g<a.length;g+=1)v=a[g].obj?a[g]:{obj:a[g]},h[g]=v,h[g].obj.core.appendTo(e).addClass("sequence-item").on("REFRESH",t);
q(0);n.core=c})()};(function(){Object.defineProperties(plura.templates.Sequence.prototype,{items:{get:function(){return this._items()}}})})();plura=plura||{};plura.templates=plura.templates||{};plura.templates.structures=plura.templates.structures||{};
plura.templates.structures.Content=function(b){var d,c,e,a=function(b,e){var l="string"===typeof b?h(b):b,m=void 0===e?!0:e;m&&(!m||d&&d[0]===l[0])||g(l,m);!m||d&&d[0]===l[0]||(d&&a(d,!1),d=l,c.trigger("REFRESH",l.data()))},g=function(a,b){!0===b?a.stop(!0).fadeIn().addClass("active"):a.stop(!0).fadeOut(function(){$(this).hide()}).removeClass("active")},h=function(a){a="object"===typeof a?a:{id:a};var b=[a.id,a.vanity||"",a.classes||""].join(" "),b=e[a.id]||$("<div/>").addClass("holder "+b).append(a.obj||
null).data(a).appendTo(c).hide();return e[a.id]=b};this.activate=a;this.disable=function(){d&&(a(d,!1),d=null)};this.get=h;b=$.extend(!0,{},{},b);c=$("<div/>").appendTo(b.target||"body").addClass(["content",b.classes||""].join(" "));e={};this.core=c;this.tree=e;return this};plura=plura||{};plura.templates=plura.templates||{};plura.templates.structures=plura.templates.structures||{};
plura.templates.structures.Menu=function(b){var d,c,e,a,g=this,h=function(b,f){var g=void 0===f?!0:f;if(!g||d&&d[0]===b[0]){if(g)return;d=null}else d&&h(d,!1),d=b;var k="selected selected-"+b.data("id");g?(c.addClass(k),b.addClass("active")):(c.removeClass(k),b.removeClass("active"));var k=b.data("id").replace(/i(.+)/,"$1").split("_").slice(0,-1),l,m;if(k.length)for(l=0;l<k.length;l+=1)m="i"+k.slice(0,l?-l:k.length).join("_"),g?(0===l&&a[m].addClass("parent"),a[m].addClass("ancestor ancestor-"+l)):
g||(0===l&&a[m].removeClass("parent"),a[m].removeClass("ancestor ancestor-"+l));if(g){if(e.url){k=b.data();g=r(k);k=[k];l=[];g&&(k=g.concat(k));for(g=0;g<k.length;g+=1)l.push(k[g].vanity||k[g].id);url.path=l.join("/")}c.trigger("SELECT",b.data())}},f=function(b,d){var g,k,h=b.data("id").replace(/i(.+)/,"$1").split("_");if(void 0===d?!b.hasClass("open"):d){e.close&&c.find(".open").each(function(a){$(this).data("id").match(b.data("id"))||f($(this),!1)});for(g=0;g<h.length;g+=1)k="i"+h.slice(0,g?-g:
h.length).join("_"),a[k].addClass("open");c.trigger("OPEN",b.data())}else b.removeClass("open")},k=function(a){return e.leaf?e.leaf(a):a.children?!1:!0},l=function(a){return e.trigger?e.trigger(a):$("<a/>").prop({href:"#"}).html(a.label).click(function(a){a.preventDefault()})},m=function(b,d,g){var n,p,q,r,w=function(a){f($(a.currentTarget).parent())},x=function(a){h($(this),!0)};for(p=0;p<b.length;p+=1)q=g?g+"_"+p:"i"+p,r={data:b[p],depth:q.split("_").length-1,id:q,label:b[p].label||b[p].name||b[p].vanity||
b[p].id||("string"===typeof b[p]?b[p]:q),vanity:b[p].id||b[p].vanity||null},n=q+" node"+(r.vanity?" id-"+r.vanity:"")+(b[p][e.nodeID]?" id-"+b[p][e.nodeID]:""),n=$(e.tags.leaf||e.tags).appendTo(d).data(r).addClass(n),r=l(r).appendTo(n).addClass("trigger"),a[q]=n,k(b[p])?(n.click(x).addClass("leaf"),c.trigger("COMPLETE_ITEM",n.data())):(r.click(w),n=$(e.tags.branch||e.tags).appendTo(n).addClass("branch"),m(b[p].children,n,q))},n=function(b){c.empty();a={};g.tree=a;e.data=b;m(e.data,c);e.first&&p(e.first);
c.trigger("COMPLETE")},q=function(b){var c;if(void 0===b||"boolean"===typeof b){if(d)return d;for(c in a)if(a.hasOwnProperty(c)&&k(a[c].data("data")))return a[c]}else{if("string"===typeof b)return a[b];if("number"===typeof b)return a["i"+b]}},r=function(b){var c,d,e=b.id.split("_");if(1<e.length){c=[];for(b=1;b<e.length;b+=1)d=e.slice(0,b?-b:e.length).join("_"),c.push(a[d].data());c=c.reverse()}return c},p=function(a){a=q(a);h(a)};this.activate=h;this.ancestors=r;this.disable=function(){d&&(h(d,!1),
c.trigger("UNSELECT",d.data()))};this.get=q;this.refresh=n;this.select=p;e=$.extend(!0,{},{close:!0,data:null,first:!1,id:"",leaf:null,nodeID:"nodeID",tags:{branch:"<ul/>",leaf:"<li/>"},url:null},b);c=$(e.tags.branch||e.tags).appendTo(e.target||"body").addClass("menu "+e.id);g.core=c;g.tree=a;e.data&&n(e.data)};plura=plura||{};plura.templates=plura.templates||{};plura.templates.structures=plura.templates.structures||{};
plura.templates.structures.Tabs=function(b){var d,c,e,a,g=function(a){a=c.tree[a]?c.tree[a].data():"object"===typeof a?a:{id:a};return e.get({classes:h(a.id).join(" "),id:a.id,vanity:a.vanity})},h=function(a){var b=[],c=a.split("_").slice(0,-1);for(a=0;a<c.length;a+=1)b[a]=a?b.join("_")+"_"+c[a]:c[a].replace(/i/,"p");return b};this.disable=function(){c.disable();e.disable()};this.get=g;this.refresh=function(){c.refresh(a.tree)};this.select=function(a){c.select(a)};a=$.extend(!0,{},{first:!1,delay:!1,
id:null,menu:{},tree:null},b);d=$("<div/>").appendTo(a.target||"body").addClass("plura templates tabs core "+(a.id||""));c=new plura.templates.structures.Menu($.extend(!0,{},a.menu,{target:d,first:a.first}));c.core.on("COMPLETE COMPLETE_ITEM OPEN SELECT",function(a,b){a.stopPropagation();if("SELECT"===a.type){var c=g(b.id);e.activate(c)}d.trigger("MENU_"+a.type,b)});this.content=e=new plura.templates.structures.Content({target:d});this.core=d;this.menu=c;return this};plura=plura||{};
plura.utils=plura.utils||{};plura.utils.Cache=function(b){var d=(new Date).getTime();b+=b.match(/\?/)?b.match(/\&$/)?"":"&":"?";return b+d};plura=plura||{};plura.utils=plura.utils||{};plura.utils.Extend=function(b,d){function c(){}c.prototype=new b;d.prototype=new c;return d};plura=plura||{};plura.utils=plura.utils||{};
plura.utils.Flat=function(b,d,c){var e=[],a,g=d||{},h,f=plura.utils.Flat;for(a in b)if(b.hasOwnProperty(a))if(b[a]instanceof Array)for(d=0;d<b[a].length;d+=1)if("object"===typeof b[a][d]&&!(b[a][d]instanceof Array))e=e.concat(f(b[a][d],g,a));else{if("number"===typeof b[a][d]||"string"===typeof b[a][d])h=$.extend({},g),h[a]=b[a][d],e.push(h)}else"object"===typeof b[a]&&(g[c]=a,e=e.concat(f(b[a],g)));return e};plura=plura||{};plura.utils=plura.utils||{};
plura.utils.Hidden=function(b){var d=(new Date).getTime(),c=function(c){b.parents("body *").each(function(){$(this).is(":animated")||(!c&&void 0!==c||"none"!==$(this).css("display")?!1===c&&$(this).hasClass("i"+d)&&$(this).removeClass("i"+d).hide():$(this).addClass("i"+d).show())})};this.get=function(){c();var d={width:b.width(),height:b.height(),innerWidth:b.innerWidth(),innerHeight:b.innerHeight(),outerWidth:b.outerWidth(),outerHeight:b.outerHeight()};c(!1);return d};this.show=c};plura=plura||{};
plura.utils=plura.utils||{};
plura.utils.String={path:function(b,d){var c=[],e,a,g,h;e=function(a){a.match(/^https?:\/\//)||(a=window.location.href.replace(/[^\/]+$/,"")+a);return a};b=e(b);d=d?e(d):window.location.href;d.match(/^http/)&&(g=d.replace(/(https?:\/\/)(.+)(\/([^\/]+)?)$/g,"$1$2").split("/"));a=g.length;for(e=0;e<a;e+=1){if(b.match(g.join("/"))){h=b.replace(g.join("/"),"");break}g.splice(-1);c.push("..")}return c.join("/")+h},test:function(b,d){var c,e,a;c=b instanceof Array?b:[b];for(e=0;e<c.length;e+=1)if(a="string"===
typeof c[e]?new RegExp(c[e].replace(/^(\/)(.*)(\/)$/,"$2")):c[e],!a.test(d))return!1;return!0}};