/**
 * Plura P Javascript Framework [http://plura.pt]
 * 
 * Copyright (c) 2015 Plura
 *
 * Date: 2015-09-25 12:00:00 (Fri, 25 Sep 2015)
 * Revision: 6246
 */
var plura={obj:function(e,b){var c,d=e.split("."),a=window;e.match(/^\./)&&(d=["plura"].concat(d.splice(1)));for(c=0;c<d.length;c+=1){if(void 0!==b)a[d[c]]=c<d.length-1?a[d[c]]||{}:b;else if(c<d.length-1&&void 0===a[d[c]])return;a=a[d[c]]}return a}};
plura.obj(".constants",{Paths:{PHP:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.php"):null,SWF:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.swf"):null},RegExp:{EMAIL:/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,EMPTY:/^\s*$/}});plura.obj(".events.EventDispatcher",function(){});
plura.events.EventDispatcher.prototype={constructor:plura.events.EventDispatcher,apply:function(e){e.addEventListener=plura.events.EventDispatcher.prototype.addEventListener;e.hasEventListener=plura.events.EventDispatcher.prototype.hasEventListener;e.removeEventListener=plura.events.EventDispatcher.prototype.removeEventListener;e.dispatchEvent=plura.events.EventDispatcher.prototype.dispatchEvent},addEventListener:function(e,b){void 0===this._listeners&&(this._listeners={});var c=this._listeners,d,
a=e.split(" ");for(d=0;d<a.length;d+=1)void 0===c[a[d]]&&(c[a[d]]=[]),-1===c[a[d]].indexOf(b)&&c[a[d]].push(b)},hasEventListener:function(e,b){if(void 0===this._listeners)return!1;var c=this._listeners;return void 0!==c[e]&&-1!==c[e].indexOf(b)?!0:!1},removeEventListener:function(e,b){if(void 0!==this._listeners){var c=this._listeners[e],d;void 0!==c&&(d=c.indexOf(b),-1!==d&&c.splice(d,1))}},dispatchEvent:function(e,b){if(void 0!==this._listeners){var c={type:e},d=this._listeners[e],a,g,h;if(void 0!==
d){c.target=this;a=[];g=d.length;for(h=0;h<g;h+=1)a[h]=d[h];for(h=0;h<g;h+=1)a[h].call(this,c,b)}}}};
plura.obj(".core.Loader",function(e){var b,c,d,a,g,h,f,l=function(a){"img"===a.dataType?c[a.name]=$(new Image).error(m).load(n).prop({src:a.path}):$.ajax({url:a.path,dataType:a.dataType,type:a.type,success:function(d){c[a.name]=d;k(c[a.name])},error:function(a,c,d){b.trigger("LOADER_ERROR",p())}})},k=function(c){a[d]=c;h=Math.ceil((d+1)/f.length*100);b.trigger("LOADER_COMPLETE_ITEM",p());d<f.length-1?(d+=1,r(d)):b.trigger("LOADER_COMPLETE",p())},m=function(a){b.trigger("LOADER_ERROR",p())},n=function(a){a=
$(a.target);k(a)},p=function(){return{content:c,index:d,items:a,item:$.extend({},f[d],{obj:c[f[d].name]}),progress:h}},r=function(a){l(f[a]);b.trigger("LOADER_CHANGE",p())},t=function(){f&&"img"===f[d].dataType&&c[f[d].name].off("load")},q=function(b){t();c={};a=[];d=0;var h=$.extend([],b);for(b=0;b<h.length;b+=1)h[b].dataType||(h[b].path.match(/\.(jpg|png|gif)$/i)?h[b].dataType="img":h[b].dataType="text"),h[b].label||(h[b].label=h[b].path.match(/([^\/?]+\.[^\/?]+)$/)[1]),h[b].type||(h[b].type="GET"),
g.cache||(h[b].path=plura.utils.Cache(h[b].path));f=h;r(d)};this._data=function(a){if(void 0===a)return c;q(a)};this._items=function(){return a};this.pause=t;g=$.extend(!0,{},{data:null,cache:!1,log:!1},e);this.core=b=g.target||$(window);g.data&&q(g.data);return this});(function(){Object.defineProperties(plura.core.Loader.prototype,{data:{get:function(){return this._data()},set:function(e){this._data(e)}},items:{get:function(){return this._items()}}})})();
plura.obj(".ecommerce.Cart",function(e){var b=this,c,d,a=function(a){var b,g={units:0,value:0},e;if("object"===typeof a)return{i:{units:a.units,value:a.value*a.units}};"string"===typeof a&&c?b=c[a]:d&&(b=d);if(b)for(e in b)b.hasOwnProperty(e)&&(g.units+=b[e].units,g.value+=b[e].total);return g},g=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0};this.add=function(a){0<a.units?(d=d||{},d[a.id]?d[a.id].update(a):d[a.id]=new plura.ecommerce.CartItem(a),a.group&&(c=c||{},c[a.group]=
c[a.group]||{},c[a.group][a.id]=d[a.id])):(delete d[a.id],g(d)&&(d=null),c&&c[a.group]&&(delete c[a.group][a.id],g(c[a.group])&&(delete c[a.group],g(c)&&(c=null))));b.dispatchEvent("REFRESH",a)};this.getTotal=a;this._group=function(){return c};this._items=function(){return d};this._length=function(){var a,b=0;if(d)for(a in d)d.hasOwnProperty(a)&&(b+=1);return b};this._total=function(){return a()};$.extend({},!0,{currency:"\u20ac"},e)});
(function(){Object.defineProperties(plura.ecommerce.Cart.prototype,{group:{get:function(){return this._group()}},length:{get:function(){return this._length()}},items:{get:function(){return this._items()}},total:{get:function(){return this._total()}}});plura.events.EventDispatcher.prototype.apply(plura.ecommerce.Cart.prototype)})();
plura.obj(".ecommerce.CartItem",function(e){this.id=this.group=this.data=null;this.label="item";this.units=this.value=0;var b=this,c=function(c){for(var a in c)c.hasOwnProperty(a)&&a.match(/(data|group|id|label|value|units)/)&&(b[a]=c[a])};this.update=c;this._total=function(){return b.value*b.units};e&&c(e)});(function(){Object.defineProperties(plura.ecommerce.CartItem.prototype,{total:{get:function(){return this._total()}}})})();
plura.obj(".events.Touch",function(e){var b,c,d,a,g,h,f,l,k,m=function(){f=h=g=a=d=c=0;k=l=null};b=$.extend(!0,{},{length:72,target:null},e);this.core=b.target;m();b.target.on("MSPointerDown MSPointerMove MSPointerUp MSPointerOver MSPointerOut touchstart touchend touchmove touchcancel",function(e){e.stopImmediatePropagation();switch(e.type){case "MSPointerUp":case "touchend":e.preventDefault();1===c&&0!==g&&(f=Math.round(Math.sqrt(Math.pow(g-d,2)+Math.pow(h-a,2))),f>=b.length&&(l=Math.round(180*Math.atan2(h-
a,d-g)/Math.PI),0>l&&(l=360-Math.abs(l)),k=45>=l&&0<=l?"left":360>=l&&315<=l?"left":135<=l&&225>=l?"right":45<l&&135>l?"down":"up"),b.target.trigger("TOUCHSWIPE",{direction:f>=b.length?k:!1}));m();break;case "touchcancel":m();break;case "MSPointerMove":case "touchmove":e.preventDefault();e.originalEvent.touches&&1!==e.originalEvent.touches.length?m():(g=e.originalEvent.pageX||e.originalEvent.touches[0].pageX,h=e.originalEvent.pageY||e.originalEvent.touches[0].pageY,b.target.trigger("TOUCHMOVE",{delta:{x:d-
g,y:a-h},position:{x:g,y:h}}));break;case "MSPointerDown":case "touchstart":e.preventDefault(),c=e.originalEvent.touches?e.originalEvent.touches.length:1,1===c?(d=e.originalEvent.pageX||e.originalEvent.touches[0].pageX,a=e.originalEvent.pageY||e.originalEvent.touches[0].pageY):m()}})});
plura.obj(".form.elements.FormLabel",function(e){var b=e.field,c=e.target,d=e.data.name,a=e.data.label,g=e.data.type;e=a&&a.align?a.align:g&&g.match(/(checkbox|radio)/)?plura.form.FormLabelAlignType.RIGHT:plura.form.FormLabelAlignType.LEFT;a=a&&(a.text||(typeof a).match(/(string|number)/))?a.text||a:d;d=$("<label/>").text(a).prop({"for":d}).addClass("type-"+(g||"text"));switch(e){case plura.form.FormLabelAlignType.LEFT:d.insertBefore(b);break;case plura.form.FormLabelAlignType.LEFT_WRAP:d.append(b).appendTo(c);
break;case plura.form.FormLabelAlignType.RIGHT:d.insertAfter(b);break;case plura.form.FormLabelAlignType.RIGHT_WRAP:d.prepend(b).appendTo(c)}return d});
plura.obj(".form.elements.FormSelect",function(e){var b,c=function(b,a){var g,h,f;for(g=0;g<a.length;g+=1)if(a[g].values||a[g]instanceof Array)h=a[g].values&&a[g].label?a[g].label:"group"+g,f=a[g].values||a[g],h=$("<optgroup/>").prop({label:h}).appendTo(b),c(h,f);else{f=b;h=a[g];var l=void 0,k=l=void 0;"string"===typeof h?l=k=h:(k=void 0!==h.value?h.value:h[e.name],l=h.label||h.name||h.value);l=$("<option/>").prop({value:k}).appendTo(f).html(l);h.data&&l.data(h.data)}};this.prop=function(c){b.prop(c)};
this.data=function(d){b.empty();"select"===e.type&&b.append("<option/>");c(b,d)};this.val=function(c){b.val(c)};this.core=b=$("<select/>")});
plura.obj(".form.Form",function(e){var b,c,d,a,g,h=function(a){var b=d[a.name].field;a.values&&a.type&&a.type.match(/(list|select)/)&&b.data(a.values);a.value&&b.val(a.value)},f=function(c,e){var m,n,p=c||(a.submit?a.fields.concat([{type:"submit",value:a.submit}]):a.fields);for(m=0;m<p.length;m+=1)if(p[m]instanceof Array||p[m].fields||p[m].type&&p[m].type.match(/^(field)?set$/i))n=$("<fieldset/>").appendTo(e||b).prop({name:p[m].name}),p[m]instanceof Array||$("<legend/>").appendTo(n).text(p[m].label||
p[m].name),f(p[m].fields||p[m],n);else{n=p[m];var r=e||b,t=void 0,q=void 0,v=void 0;$("<div/>");var w=void 0,u=void 0;switch(n.type){case "list":case "select":q=new plura.form.elements.FormSelect(n);t=q.core;break;case "textarea":t=$("<textarea/>");n.wysiwyg&&window.tinyMCE&&(w=tinymce.DOM.uniqueId(),u=$.extend(!0,a.tinyMCE,{editor_selector:w},"number"!==typeof n.wysiwyg?n.wysiwyg:null,{width:300}),t.addClass(w+" tinyMCE").prop({id:w}).appendTo("body").width(t.width()).height(t.height()),tinyMCE.init(u));
break;case "file":q=new plura.form.Upload($.extend({name:n.name,target:r},a.upload));t=q.core;g.push(q);break;default:t=$("<input/>"),jQuery.ui&&"date"===n.type&&t.datepicker({dateFormat:"yy-mm-dd"})}var w=t,u=n,y=u.name,x={},z=$.extend;u.disabled&&z(x,{disabled:u.disabled});(a.id||u.id)&&z(x,{id:!0===u.id?u.name:u.id});u.type&&u.type.match(/(list|select|textarea)/)||z(x,{type:u.type&&"date"!==u.type?u.type:"text"});u.type&&u.type.match(/list/)&&z(x,{multiple:!0,size:u.size||1});u.value&&u.type.match(/(checkbox|radio)/)&&
z(x,{value:u.value});u.type&&u.type.match(/list/)&&(y+="[]");z(x,{name:y});(w.core||w).prop(x);n.change&&t.change(n.change);n.type&&n.type.match(/file/)||t.appendTo(r);n.label&&(v=new plura.form.elements.FormLabel({data:n,field:t,target:r}));d[n.name]={data:n,field:q||t,label:v};void 0===n.value&&!n.values||n.type&&!n.type.match(/(list|select|submit|text|textarea)/)?n.type&&n.type.match(/(checkbox|radio)/)&&n.checked&&t.prop("checked",!0):h(n)}};this._query=function(){return c._query()};this._params=
function(a){return c._params(a)};this.populate=function(a){var b,c,f;for(b in a)if(a.hasOwnProperty(b)&&d[b])switch(c=d[b].field,f=d[b].data,f.type){case "checkbox":c.prop("checked","0"!==a[b]);break;default:f.type&&f.type.match(/textarea/i)&&f.wysiwyg?tinyMCE.get(c.prop("id")).setContent(a[b]||""):f.type&&f.type.match(/file/)||c.val(a[b])}};this.refresh=function(a){var b,c;for(c in a)a.hasOwnProperty(c)&&d[c]&&(b=$.extend(!0,{},d[c].data,{values:a[c]}),h(b))};this.reset=function(a){c.reset(a)};a=
$.extend(!0,{},{alert:{success:"Success! Content updated!",error:"Error! Content not updated! :("},check:null,fields:null,id:!1,path:null,params:null,reset:!1,send:!0,submit:"Submit",tinyMCE:{mode:"specific_textareas",theme:"advanced",plugins:"fullscreen",theme_advanced_buttons1:"bold,italic,underline,|,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,outdent,indent",theme_advanced_buttons2:"formatselect,sub,sup,code,fullscreen,link,unlink,|,forecolor,removeformat"}},
e);b=$("<form/>").appendTo(a.target);g=[];d={};this.core=b;this.objects=d;this.uploads=g;f();c=new plura.form.FormManager($.extend(!0,{},{ajax:a.ajax||{},alert:a.alert||{},check:a.check||{},params:a.params||{}},{path:a.path,reset:a.reset,send:a.send,target:this,type:"getJSON"}));return this});(function(){Object.defineProperties(plura.form.Form.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(e){this._params(e)}}})})();
plura.obj(".form.FormLabelAlignType",{LEFT:"left",LEFT_WRAP:"left_wrap",RIGHT:"right",RIGHT_WRAP:"right_wrap"});
plura.obj(".form.FormManager",function(e){var b,c,d,a=function(a){b.find("input[type=file]").each(function(c){d[c]=new plura.form.Upload($.extend({name:$(this).attr("name"),target:b},a));d[c].core.replaceAll($(this))})},g=function(a){var c=$.extend({},{not:":button, :submit, :reset",checked:!0,selected:!0,upload:!0}),f=b.find(":input").not(c.not);f.not(":checkbox, :radio").val("");c.checked&&f.prop("checked",!1);c.selected&&f.prop("selected",!1);for(c=0;c<d.length;c+=1)d[c].reset(a);window.tinyMCE&&
b.find(".tinyMCE").each(function(){tinymce.get($(this).prop("id")).setContent("");tinymce.get($(this).prop("id")).nodeChanged()})},h=function(){var a=c.path||window.location.href,d=function(a,c){return"string"===typeof a?a:a.alert?a:$.extend(!0,{},a,{alert:c})};console&&console.log(c.ajax.dataType+" | "+c.ajax.type+" | "+a+":"+f());$.ajax({url:a,data:f(),dataType:c.ajax.dataType,type:c.ajax.type,success:function(a){b.trigger("FORM_REQUEST_SUCCESS",d(a,c.alert.complete));!a.success||"true"!==a.success&&
1!==a.success?(a.success&&"false"===a.success||0===a.success)&&b.trigger("FORM_PROCESS_ERROR",d(a,c.alert.error)):(c.reset&&g(!0),b.trigger("FORM_PROCESS_SUCCESS",d(a,c.alert.success)))},error:function(a,c,b){}});b.trigger("FORM_SUBMIT",{alert:c.alert.submit})},f=function(){return b.serialize()+"&"+$.param(c.params||{})};this._query=f;this._params=function(a){void 0!==a&&(c.params=$.extend(!0,c.params||{},a));return c.params};this.reset=g;c=$.extend(!0,{},{ajax:{dataType:"json",type:"GET"},alert:{complete:"Your form was submited.",
error:"There was an error processing your form.",field:"Please correctly fill the % field. Thank you",submit:"Form is being submitted. Please wait.",success:"Your form was successfully processed! Thank you."},check:!1,params:null,path:null,replace:!0,reset:!1,send:!0,target:null,upload:{}},e);b=c.target.core||c.target;d=c.target.uploads||[];this.form=b;c.replace&&a(c.upload);b.submit(function(a){a.preventDefault();window.tinyMCE&&tinyMCE.triggerSave();if(!(a=!c.check))a:{var d,f,e,g;for(d=0;d<c.check.length;d+=
1)for(a=c.check[d],e=a.rules?a.rules instanceof Array?a.rules:[a.rules]:[{alert:a.alert||null}],f=0;f<e.length;f+=1)if(g=plura.utils.String.test([/\./,/#/],a.id)?b.find(a.id):b.find("*[name="+a.id+"]"),e[f].exp&&!plura.utils.String.test(e[f].exp,g.val())||!e[f].exp&&g.val().match(/^\s*$/)){a=e[f].alert||c.alert.field.replace(/%/,a.id);b.trigger("FORM_VALIDATION_ERROR",{alert:a});a=!1;break a}b.trigger("FORM_VALIDATION_SUCCESS");a=!0}a&&c.send&&h()}).find("input[type=reset]").click(function(a){a.preventDefault();
g()})});(function(){Object.defineProperties(plura.form.FormManager.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(e){this._params(e)}}})})();
plura.obj(".form.upload.File",function(e){var b,c,d,a,g,h,f=function(){c.slideUp("slow",m);h.reset()},l=function(a){$.getJSON(g.process,{action:"delete",file:d.file,path:g.path,type:"upload"},function(b){"true"===b.success&&a&&(f(),c.trigger("FORM_UPLOAD_REMOVE"))})},k=function(a){if(d&&!a)l(!0);else if(!d||d&&a)d||(swf.cancel(g.id),c.trigger("FORM_UPLOAD_CANCEL")),f()},m=function(){$(this).remove()};this.update=function(f){d=f;a=a||$("<input/>").prop({type:"hidden",name:e.name+"[]"}).appendTo(c);
a.val(f.file+"|"+f.name);b.val(g.label.remove);console.log(d)};this.clean=function(){d&&l();b.val(g.label.cancel)};this.reset=k;this.refresh=function(a){h.refresh(a)};g=$.extend(!0,{},{css:{button:{border:"none","float":"right","text-align":"center",width:50},file:{"float":"left",width:"100%"},progress:{"float":"left"}},height:20,label:{cancel:"Cancel",remove:"Delete"},margin:5,swf:null,width:100},e);c=$("<div/>").addClass("file i"+g.id).appendTo(g.target);h=new plura.layout.ProgressBar({target:c,
css:{core:$.extend({},g.css.file,{width:g.width-3*g.margin-g.css.button.width})}});b=$("<input/>").prop({type:"button"}).val(g.label.cancel).addClass("delete").appendTo(c).click(function(a){k()});this.core=c;c.css($.extend({},g.css.file,{"margin-bottom":g.margin}));b.css($.extend({},g.css.button,{height:g.height}));return this});
plura.obj(".form.Upload",function(e){var b,c,d,a,g,h,f,l=function(){b.children(".files").slideUp("slow",function(){$(this).remove()})},k=function(a){if(c){for(var b in c)c.hasOwnProperty(b)&&(c[b].reset(a),delete c[b]);c=null}l()},m=function(a){a.stopImmediatePropagation();1===b.children(".files").children().length&&k()},n=function(a){var c=$("<div/>");g=swfobject.getObjectById(a.id);c.replaceAll(b);$("body").prepend(b);$("#"+a.id).css({left:h.position().left,position:"absolute",top:h.position().top,
zIndex:100});b.replaceAll(c)},p=function(a,c,b){"true"===b.success&&f.instances["i"+a].update(c,b)},r=function(a,c){f.instances["i"+a].init(c)},t=function(a,c,b){f.instances["i"+a].refresh(c,b)},q=function(a){};this.init=function(f){a.multiple||!a.multiple&&!c?(c=c||{},c["i"+f]=new plura.form.upload.File($.extend(!0,{},a.file,{id:f,name:a.name,path:plura.utils.String.path(a.path,a.process||plura.constants.Paths.PHP),process:a.process||plura.constants.Paths.PHP,swf:g,target:b.children(".files").length?
b.children(".files"):$("<div/>").appendTo(b).addClass("files").css($.extend({},a.css.files,{"margin-top":a.margin,padding:a.margin+"px "+a.margin+"px 0 "+a.margin+"px",width:a.width-2*a.margin})),width:a.width})),c["i"+f].core.on("FORM_UPLOAD_CANCEL FORM_UPLOAD_REMOVE",m)):!a.multiple&&c&&c["i"+f].clean()};this.refresh=function(a,b){c["i"+a].refresh(b)};this.reset=k;this.update=function(a,b){c["i"+a].update(b)};f=plura.form.Upload;f.count=void 0===f.count?0:f.count+1;f.instances=f.instances||{};f.instances["i"+
f.count]=this;f.complete=f.complete||p;f.init=f.init||r;f.refresh=f.refresh||t;f.test=f.test||q;d=f.count;a=$.extend(!0,{},{css:{files:{"float":"left","background-color":"#e0e0e0"},progress:{"float":"left"},trigger:{border:"none","float":"right","text-align":"center",width:70}},file:{},label:{cancel:"Cancel",remove:"Delete",upload:"Upload"},height:30,limit:0,margin:5,multiple:!1,path:"",obj:"plura.form.Upload",swf:{params:{allowscriptaccess:"always",menu:"false",wmode:"transparent"},version:"10.0"},
process:null,width:220},e);b=$("<div/>").css({position:"relative"}).addClass("upload i"+d).appendTo(a.target);new plura.layout.ProgressBar({target:b,css:{core:$.extend({},a.css.progress,{width:a.width-a.css.trigger.width-a.margin,height:a.height})}});h=$("<input/>").prop({type:"button",value:a.label.upload}).addClass("trigger").appendTo(b);this.core=b;b.css({width:a.width});h.css($.extend({},a.css.trigger,{height:a.height}));(function(){var c=$("<div/>").attr({id:"plura_form_upload_"+d}).appendTo(b),
f=h.outerHeight(!0),e={id:d,limit:a.limit,multiple:a.multiple,obj:a.obj,path:plura.utils.String.path(a.path,a.process||plura.constants.Paths.PHP),process:a.process||plura.constants.Paths.PHP,type:"upload"},g=h.outerWidth(!0);swfobject.embedSWF(plura.constants.Paths.SWF,c.attr("id"),g,f,a.swf.version,null,e,a.swf.params,null,n)})();return this});
plura.obj(".fx.Center",function(e){var b=e.target||e.obj.parent(),c=function(a){var c=e.dimensions,b=e.obj;return c&&c[a]?c[a]:b[a]()},d=function(a){var c=e.obj;return b&&$.isPlainObject(b)&&void 0!==b[a]?b[a]:b&&!$.isPlainObject(b)?b.offset()[a]-c.offsetParent().offset()[a]:0},a=function(a){var c=e.obj,b=e.target;return b&&$.isPlainObject(b)&&void 0!==b[a]?b[a]:b&&!$.isPlainObject(b)?b[a]():c.parent().length?c.parent()[a]():c[a]()},g=c("height"),h=c("width"),c=a("height"),f=d("left"),d=d("top"),
a=(a("width")-h)/2+f;e.obj.css({top:(c-g)/2+d,left:a,position:"absolute"!==e.obj.css("position")?"absolute":""})});
plura.obj(".fx.Parallax",function(e){var b,c,d,a,g,h,f,l,k,m=function(){return{height:g.dimensions&&g.dimensions.height?g.dimensions.height:g.target.height(),width:g.dimensions&&g.dimensions.width?g.dimensions.width:g.target.width()}},n=function(){return f.x+c.x>f.x&&f.x+c.x<f.x+f.width&&f.y+c.y>f.y&&f.y+c.y<f.y+f.height?!0:!1};g=$.extend(!0,{},{enabled:{x:!0,y:!0},dimensions:null,rectangle:{width:0,height:0,y:0,x:0},restrict:{x:!0,y:!0},speed:8,target:null},e);b=g.enabled;f=g.rectangle?{y:g.rectangle.y||
0,x:g.rectangle.x||0,height:g.rectangle.height||g.target.parent().height(),width:g.rectangle.width||g.target.parent().width()}:!1;l=g.restrict;k=g.target;d=k.position().left;a=k.position().top;c={x:0,y:0};h={x:0,y:0};$(document).mousemove(function(a){c={x:a.pageX-k.parent().offset().left-f.x,y:a.pageY-k.parent().offset().top-f.y}});setInterval(function(){if(!(!f||!f.width&&b.x||!f.height&&b.y)){var e,r;h.x=isNaN(h.x)?0:h.x;h.y=isNaN(h.y)?0:h.y;b.x&&(d=n()?c.x:d,f.width<m().width&&l.x||f.width>m().width&&
!l.x?(e=-d*((m().width-f.width)/f.width)+f.x,h.x+=(e-k.position().left)/g.speed):b.x&&f.width>m().width&&l.x&&(e=((f.width-k.width)/2+d-k.position().left)/g.speed,h.x+=e),1<Math.abs(e-k.position().left)&&k.css({left:h.x}));b.y&&(a=n()?c.y:a,f.height<m().height&&l.y||f.height>m().height&&!l.y?(r=-a*((m().height-f.height)/f.height)+f.y,h.y+=(r-k.position().top)/g.speed):b.x&&f.width>m().width&&l.x&&(r=((f.height-k.height)/2+a-k.position().top)/g.speed,h.y+=r),1<Math.abs(r-k.position().top)&&k.css({top:h.y}));
k.trigger("PARALLAX",{dimensions:m(),inside:n(),mouse:c,rectangle:f,target:k,position:h})}},13);return this});
plura.obj(".fx.Resize",function(e){var b=$.extend(!0,{},{center:!1,increase:!0,height:void 0,inside:!1,target:void 0,width:void 0},e),c=b.obj,d=function(a){var f=e.target;if(!f&&b[a])return b[a];f||void 0!==b.width||void 0!==b.height||(f=c.parent());return f&&$.isPlainObject(f)&&void 0!==f[a]?f[a]:f&&!$.isPlainObject(f)?f[a]():c[a]()},a=d("height"),g=d("width");c.css(function(){var d,f,e=c.width(),k=c.height();if(b.increase||!b.increase&&(k>a||e>g))e/k>g/a&&b.inside||e/k<g/a&&!b.inside?(d=g/e*e,f=
d*k/e):(f=a/k*k,d=f*e/k);return{width:d===e?"":d,height:f===k?"":f}}());b.center&&plura.fx.Center({obj:b.obj,target:b.center.target||b.target,dimensions:b.center.dimensions||!1})});plura.obj(".layout.LoaderBar",function(e){var b;b=new plura.layout.ProgressBar(e);e.loader.core.on("LOADER_COMPLETE_ITEM",function(c,d){b.refresh(d.progress)})});
plura.obj(".layout.navigation.Nav",function(e){var b,c,d,a,g,h=function(a,f){f&&(!f||b&&b[0]===a[0])||(f?a.addClass("active"):a.removeClass("active"));!f||b&&b[0]===a[0]||(b&&h(b,!1),b=a,c.trigger("SELECT",a.data()))},f=function(b){c.find(".i"+b).length?h(c.find(".i"+b),!0):a[b].data({active:!0})},l=function(c){a[c].prop({src:g.path+(g.data[c].thumb||g.data[c].file)})},k=function(a){h($(a.currentTarget),!0)},m=function(b){var e,h,m,q;b=$(b.target);var v=b.data("index");m=g.wrap?g.wrap(b).data(b.data()):
b;b.data("active")&&f(b.data("index"));m=m.addClass("item i"+b.data("index")).click(k).appendTo(d||c);q=m.prev();(g.width||g.height)&&plura.fx.Resize({target:{width:g.width,height:g.height},obj:b,inside:!0});g.css&&(e=0!==v%g.limit&&0<v?q.width()+q.position().left+g.margin:0,h=0!==v%g.limit&&0<v?q.position().top:0===v%g.limit&&0<v?q.position().top+q.height()+g.margin:0,m.css({position:"absolute",left:e,top:h}));g.parallax&&(e=0<v&&q.position().left+q.width()>e+m.width()?q.position().left+q.width():
e+m.width(),h=0<v&&q.position().top+q.height()>h+m.height()?q.position().top+q.height():h+m.height(),m.parent().width(e).height(h));b.fadeIn();a[v+1]&&l(v+1);c.trigger("COMPLETE_ITEM",v);b.data("active")&&f(v)};this.select=f;g=$.extend(!0,{},{css:{core:{position:"absolute",zIndex:2},parallax:{core:{position:"absolute",zIndex:1},holder:{top:0,left:0,position:"absolute",zIndex:2}}},height:null,holder:!1,limit:0,margin:5,overflow:!1,path:"",parallax:{},text:!1,width:null},e);c=$("<div/>").appendTo(g.target||
"body").addClass(["nav",g.text?"txt":"img"].join(" "));a=[];(function(b){var f;if(g.holder||g.parallax)d=$("<div/>").prependTo(c).addClass("holder");g.parallax&&(f=$.extend(!0,{target:d},g.parallax),new plura.fx.Parallax(f),g.css&&(d.css(g.css.parallax.holder),g.overflow||c.css({overflow:"hidden",width:f.rectangle.width,height:f.rectangle.height})));for(f=0;f<b.length;f+=1)g.text?$("<a/>").appendTo(d||c).addClass("item i"+f).data({index:f}).html(f+1).click(k):(a[f]=$(new Image).data({index:f}).hide().load(m),
0===f&&l(f))})(g.data);g.css&&c.css(g.css.core);this.core=c;return this});
plura.obj(".layout.ProgressBar",function(e){var b,c,d;this.refresh=function(a){c.height(b.height()).width(b.width()*a/100).show();100===a&&d.hide&&b.stop().fadeOut("slow")};this.reset=function(){c.fadeIn()};d=$.extend(!0,{},{bottom:!0,css:{core:{width:200,height:20,border:"2px solid #000"},bar:{backgroundColor:"#000"}},hide:!1,horizontal:!0,target:null},e);b=$("<div/>").appendTo(d.target||"body").addClass("plura progress").css(d.css.core);c=$("<div/>").appendTo(b).addClass("bar").css(d.css.bar).hide();
(function(a){a.height(a.height()-2*parseInt(a.css("border-top-width"),10)).width(a.width()-2*parseInt(a.css("border-top-width"),10))})(b);this.core=b;this.bar=c});
plura.obj(".layout.Refresh",function(e){var b,c,d=0,a,g,h=function(a){var f=c.format?c.format(a):a;c.fade?b.fadeOut(c.speed,function(){$(this).html(f).fadeIn(c.speed)}):b.html(f);b.trigger("CHANGE");c.refresh&&(clearInterval(g),g=setInterval(l,c.time))},f=function(a,b){var f,d=[],e;for(f in c.data)c.data.hasOwnProperty(f)&&(e=Math.floor(f/b),d[e]=d[e]||[],d[e].push(a[f]));return d},l=function(){"string"===typeof c.data?c.json?$.getJSON(c.data,null,function(a){h(a)}):$.get(c.data,null,function(a){h(a)}):
"object"===typeof c.data&&(h(a[d%a.length]),d+=1)};c=$.extend(!0,{},{data:!1,fade:!0,format:null,json:!1,limit:1,refresh:!0,speed:"slow",target:null,time:1E4},e);b=$("<div/>").appendTo(c.target||"body").addClass("refresh core");"object"===typeof c.data&&(a=f(c.data,c.limit));l()});
plura.obj(".layout.Slideshow",function(e){var b={auto:!0,cache:!1,center:!1,controls:!1,css:{core:{position:"relative"},media:{core:{position:"relative"},item:{position:"absolute"}}},data:null,height:null,id:"",inline:!1,loop:0,navigation:{},outside:!1,path:"",resize:!1,target:null,timer:8E3,width:null,video:null},c,d,a,g=0,h,f,l,k,m,n,p,r,t=this,q=function(b){p&&clearTimeout(p);l&&l.core.remove();var c=[],e;for(e=0;e<b.length;e+=1)"string"===typeof b[e]?c.push({file:b[e]}):c.push(b[e]);a=c;1<a.length&&
(k.navigation&&(l=new plura.layout.navigation.Nav($.extend(!0,{data:a,path:k.path,target:d},k.navigation)),t.navigation=l,l.core.on("COMPLETE_ITEM SELECT",A)),k.swipe&&(n=new plura.events.Touch($.extend({target:f},"object"===typeof k.swipe?k.swipe:null)),n.core.on("TOUCHMOVE TOUCHSWIPE",B)));v(g,!0)},v=function(b,f){f&&(void 0!==c&&c.removeClass("active").addClass("inactive").fadeOut(function(){$(this).remove()}),g=b,c=w(a[g]).addClass("item active i"+g),d.trigger("CHANGE",{index:g}),l&&l.select(g),
k.css&&c.css(k.css.media.item))},w=function(a){var b=a.data&&a.file,c=b?$("<div/>").addClass("mixed").appendTo(f):f,d,e;if(k.inline)f.css("background-image","url('"+x(a)+"')"),clearTimeout(p),p=setTimeout(u,k.timer);else if(a.data&&(d=$("<div/>").html(a.data).appendTo(c).addClass("data").hide().fadeIn()),a.file)if(a.file.match(/\.(gif|jpg|png)$/i)||a.type&&a.type.match(/image/i))a=x(a),d=$(new Image).load(z).appendTo(c).prop({src:a}).hide();else if(a.file.match(/\.(mp4)$/i)||a.type&&a.type.match(/video/i))e=
new plura.media.Video($.extend({src:x(a,!1),target:c},k.video)),d=e.core.on("METADATA",C);return $(b?c:d).data({video:e||!1})},u=function(){!1!==k.loop&&k.loop!==h||g!==a.length-1?(v(g<a.length-1?g+1:0,!0),0===g&&(h=(h||0)+1,d.trigger("LOOP"))):d.trigger("SEQUENCE_COMPLETE")},y=function(){v(0<g?g-1:a.length-1,!0)},x=function(a,b){var c=(k.path||"")+(a.path||"")+a.file;if(b||k.cache&&!1!==b)c+="?"+(new Date).getTime();return c},z=function(b){b=$(b.target).css({width:"auto",height:"auto"}).fadeIn();
if(k.resize||k.center){var c=b.height(),e=k.resize&&k.resize.target?k.resize.target.height():k.height||f.height(),g=b.width(),h=k.resize&&k.resize.target?k.resize.target.width():k.width||f.width();k.resize&&(k.outside&&(g>e||c>e)||!k.outside)&&("function"===typeof k.resize?k.resize(b):plura.fx.Resize({center:"boolean"===typeof k.resize||void 0===k.resize.center?!1:k.resize.center,inside:"boolean"===typeof k.resize||void 0===k.resize.inside?!0:k.resize.inside,obj:b,target:{width:h,height:e}}));k.center&&
plura.fx.Center({target:{width:h,height:e},obj:b})}!m&&1<a.length&&(clearTimeout(p),p=setTimeout(u,k.timer));d.trigger("COMPLETE_ITEM",b)},C=function(a){a.stopImmediatePropagation();d.trigger("COMPLETE_ITEM",$(a.target))},A=function(a,b){a.stopImmediatePropagation();switch(a.type){case "SELECT":b.index!==g&&v(b.index,!0)}d.trigger("NAVIGATION_"+a.type,b)},B=function(a,b){a.stopPropagation();var f;switch(a.type){case "TOUCHMOVE":c.css({left:-b.delta.x});break;case "TOUCHSWIPE":f=b.direction&&b.direction.match(/(left|right)/)?
("left"===b.direction?-1:1)*c.outerWidth():0,c.animate({left:f},"slow"),"left"===b.direction?u():"right"===b.direction&&y()}},D=function(){};this._index=function(a){if(void 0===a)return g;v(a,!0)};this._items=function(b){if(void 0===b)return a;q(b)};this.next=u;this.pause=function(a,b){clearTimeout(p);var f=void 0!==a?a:!m;f?f&&b&&c.data("video")&&c.data("video").pause(!0):p=setTimeout(u,k.timer);m=f};this.previous=y;(function(){k=$.extend({},b,e);d=$("<div/>").appendTo(k.target||"body").addClass("plura slideshow "+
k.id);f=$("<div/>").appendTo(d).addClass("media");m=!k.auto;"string"===typeof k.data?$.getJSON(k.data,function(a){q(a)}):k.data&&"object"===typeof k.data&&q(k.data);k.css&&(d.css(k.css.core),f.css(k.css.media.core));k.inline&&"boolean"!==typeof k.inline&&f.css(k.inline);t.core=d;t.media=f;r=plura.layout.Slideshow;r.items=r.items||[];r.stop=r.stop||D;r.items.push(t)})();return this});
(function(){Object.defineProperties(plura.layout.Slideshow.prototype,{index:{get:function(){return this._index()},set:function(e){this._index(e)}},items:{get:function(){return this._items()},set:function(e){this._items(e)}}})})();
plura.obj(".layout.Social",function(e){var b,c=function(a){var c=$("<div/>").appendTo(b).addClass("fb-like"),d=[];a=$.extend(!0,{},a,{height:"button_count"===a.layout?21:"box_count"===a.layout?65:a.show_faces?80:35,href:a.href||window.location.href});for(var f in a)a.hasOwnProperty(f)&&d.push(f+"="+(a[f]||""));$("<iframe/>").appendTo(c).css({width:a.width,height:a.height,border:"none",overflow:"hidden"}).prop({allowTransparency:"true",frameborder:0,scrolling:"no",src:"//www.facebook.com/plugins/like.php?"+
d.join("&")})},d=function(a){var c=$("<div/>").appendTo(b).addClass("twitter"),d=$("<a/>").appendTo(c).prop({href:"http://twitter.com/share"}).addClass("twitter-share-button").html("Tweet"),f=document.createElement("script"),e;for(e in a)a.hasOwnProperty(e)&&("related"===e?a[e].user&&d.attr("data-"+e,a[e].user+(a[e].text?":"+a[e].text:"")):a[e]&&d.attr("data-"+e,a[e]));$(f).attr({type:"text/javascript",src:"http://platform.twitter.com/widgets.js"}).appendTo(c)};b=$("<div/>").addClass("share");e=$.extend(!0,
{},{like:{action:"like",colorsheme:"light",font:null,href:null,layout:"standard",show_faces:!0,width:450},twitter:{count:"horizontal",related:{text:null,via:null},text:null,via:null,url:null},target:null},e);e.target&&b.appendTo(e.target);e.like&&c(e.like);e.twitter&&d(e.twitter);return b});
plura.obj(".layout.Table",function(e){var b,c,d=function(c){a();var d,f,l=[],k={};for(d in c[0])c[0].hasOwnProperty(d);for(d=0;d<c.length;d+=1)for(f in c[d])c[d].hasOwnProperty(f)&&(l[d]=l[d]||[],k[f]=k[f]||{rowspan:1},e&&e.merge&&0<d&&c[d][f]===c[d-1][f]&&("string"===typeof e.merge?(new RegExp(e.merge)).test(f):1)?(k[f].rowspan+=1,l[k[f].r][k[f].c].rowspan=k[f].rowspan):(k[f]={rowspan:1,r:d,c:l[d].length},l[d].push({value:c[d][f],span:k[f].rowspan})));var m,k=$("<table/>").appendTo(b);for(f=0;f<
l.length;f+=1)for(d=$("<tr/>").appendTo(k),c=0;c<l[f].length;c+=1)m=$("<td/>").appendTo(d).html(l[f][c].value||l[f][c]),l[f][c].rowspan&&1<l[f][c].rowspan&&m.prop({rowspan:l[f][c].rowspan})},a=function(){b.empty()};this.refresh=d;this.empty=a;c=$.extend(!0,{},{limit:0,merge:!0,target:null},e);this.core=b=$("<div/>").appendTo(c.target||"body").addClass("table core "+(c.classes||""));c.data&&d(c.data);return this});
plura.obj(".media.Audio",function(e){var b,c,d,a,g,h,f=function(c){(a=void 0===c?!a:c)?b.find(".play").removeClass("active").html(d.labels.play):b.find(".play").addClass("active").html(d.labels.pause);g?g.pause(a):a||g||p()},l=function(a){var f=$("<div/>").attr({id:"plura_media_audio_"+c}).appendTo(b);a={content:a,id:c,obj:"plura.media.Audio",type:"audio"};swfobject.embedSWF(plura.constants.Paths.SWF,f.attr("id"),"0","0","10.0.0",null,a,null,null,m)},k=function(b){f(!a)},m=function(a){g=swfobject.getObjectById(a.id)},
n=function(a){for(var b in h.instances)h.instances.hasOwnProperty(b)&&!b.match("i"+a)&&h.instances[b].pause(!0)},p=function(){d.data?l(d.data):d.path&&$.get(d.path,function(a){console.log(a);l(a)})};this.fade=function(a){b.find(".menu").fadeIn("slow")};this.pause=f;h=plura.media.Audio;h.count=void 0===h.count?0:h.count+1;h.instances=h.instances||{};h.instances["i"+h.count]=this;h.pause=h.pause||n;c=h.count;d=$.extend(!0,{},{auto:!0,data:null,controls:!0,css:{flash:{position:"relative",height:0,width:0},
test:{position:"absolute",zIndex:1E3,width:400,height:400}},fade:!0,labels:{pause:"Pause",play:"Play"},path:null,params:null,target:"body",test:!1},e);(function(){b=$("<div/>").appendTo(d.target).addClass("p audio").css({position:"relative"});var a=$("<ul/>").appendTo(b).addClass("menu controls");d.controls&&$("<li/>").appendTo(a).click(k).addClass("play");f(!d.auto)})();this.core=b});
plura.obj(".media.Video",function(e){var b,c,d=!0,a,g,h=this,f=function(b){a.empty();var c,f=b instanceof Array?b:[b],d;for(b=0;b<f.length;b+=1)c=f[b].src||f[b],d=f[b].type||"video/"+c.match(/\.([^.]+)$/)[1],$("<source/>").prop({src:c,type:d}).appendTo(a);return h},l=function(b){(d=void 0===b?!d:b)?(c.addClass("pause"),a[0].pause()):(c.removeClass("pause"),a[0].play())},k=function(b){void 0!==b&&(a[0].volume=b);return a[0].volume},m=function(a){a.stopImmediatePropagation();l()};this.pause=l;this.prop=
function(b){a.prop(b);return h};this.src=f;this.volume=k;b=new plura.net.Client;e=$.extend(!0,{},{autoplay:!0,controls:!0,pause:!0,preload:!0,loop:!0,wrap:!1},e);g={autoplay:e.autoplay,controls:e.controls,loop:e.loop,height:e.height,preload:e.preload,width:e.width,poster:e.poster};a=$("<video/>").prop(g).on("loadedmetadata",function(a){c.trigger("METADATA",{width:this.videoWidth,height:this.videoHeight})});c=e.wrap?$("boolean"===typeof e.wrap?"<div/>":e.wrap).append(a).addClass("video"):a;c.appendTo(e.target||
"body");e.src&&f(e.src);h.core=c;if(e.pause&&!e.controls||b.data.ios)a.on("click touchstart",m),e.wrap&&c.click(m);e.volume&&k(e.volume);b.data.ios||l(!e.autoplay);return this});
plura.obj(".net.Client",function(e){var b;b=navigator.userAgent;var c=Boolean(b.match(/Android/i)),d=Boolean(b.match(/(explorer|MSIE)/i)),a=Boolean(b.match(/iPad/i)),g=Boolean(b.match(/iPhone/i)),h=Boolean(b.match(/iPod/i)),g=g?"iPhone":a?"iPad":h?"iPod":null,f=Boolean(null===document.location.href.match(/https?:\/\//)),l=Boolean(g||c||b.match(/Windows.+Touch/i)),k=parseInt(navigator.appVersion,10);d&&(k=parseInt(navigator.appVersion.match(/msie ([0-9\.]+)/i)[1],10));b={agent:b,android:c,ie:d,ios:g,
ipad:a,ipod:h,offline:f,touch:l,version:k};c=[];a=e&&e.ie?e.ie:11;if(b.ie){if(c.push("ie","ie"+b.version),b.version<a)for(c.push("ie_lte"+b.version),d=b.version;d<a;d+=1)c.push("ie_lt"+(d+1))}else b.ios?c=c.concat(["ios",b.ios.toLowerCase()]):b.android&&c.push("android");b.offline&&c.push("offline");c.push((b.touch?"":"no-")+"touch");b.classes=c;this.data=b;e&&e.classes&&$("body").addClass(b.classes.join(" "))});
plura.obj(".net.URLManager",function(e){var b={analytics:!0,lang:!0,separator:"#"},c,d,a,g,h,f,l=function(a,b,c,f,d){window._gaq&&(a=["_trackEvent",a,b,c,f],void 0!==d&&!0===d&&a.push(d),_gaq.push(a))},k=function(a){var b=[];a&&c&&b.push(c);h&&b.push(h);return b.join("/")},m=function(a){void 0!==a&&a!==h&&(h=a,d.push(h));window.location.href="#!/"+k(!0);g.analytics&&(a="/"+k(!0),window._gaq&&_gaq.push(["_trackPageview",a]))};this._history=function(){return d};this._index=function(){return a};this._lang=
function(a){void 0!==a&&(c=a,m());return c};this._path=function(a){void 0!==a&&m(a);return h};this._root=function(){return f};this._url=function(){return f+"#!/"+k(!0)+"/"};this.event=function(){l.apply(null,arguments)};this.perma=function(a){return a.match(f+".*?([^=]*[^/])/?$")[1]};(function(){var k=window.location.href;g=$.extend(!0,{},b,e);d=[];a=0;f=k.match(/[^#]+/)[0];k.match(/#!\/(.+)/)&&(k=k.match(/#!\/(.+)/)[1].replace(/\/$/,"").split(/\//),g.lang&&k[0].match(/^[a-z]{2}$/)&&(c=k.shift()),
h=k.join("/"),d.push(h))})()});(function(){Object.defineProperties(plura.net.URLManager.prototype,{history:{get:function(){return this._history()}},index:{get:function(){return this._index()}},lang:{get:function(){return this._lang()},set:function(e){this._lang(e)}},path:{get:function(){return this._path()},set:function(e){this._path(e)}},root:{get:function(){return this._root()}},url:{get:function(){return this._url()}}})})();
plura.obj(".templates.alert.Slide",function(e){var b,c;this.refresh=function(d,a){clearTimeout(c);b.html(a).stop(!0,!0).slideDown().addClass(d?"success":"error").removeClass(d?"error":"success");c=setTimeout(function(){b.slideUp()},2E3)};b=$("<p/>").appendTo(e.target||"body").addClass("alert").hide()});
plura.obj(".templates.checkout.end.Form",function(e){var b;this._items=function(c){b.params={items:c}};e=$.extend(!0,{},{labels:{check:{email:{empty:"Please insert your email. Thank you!",invalid:"Your email address is invalid."},name:"Please insert your first and last name. Thank you!",message:"Please include a message. Thank you!"},fields:{email:"Email",name:"Name",message:"Message"}}},e);b=new plura.form.Form({check:[{id:"user_email",rules:[{alert:e.labels.check.email.empty},{exp:String(plura.constants.RegExp.EMAIL),
alert:e.labels.check.email.invalid}]},{id:"user_message",alert:e.labels.check.message},{id:"user_name",alert:e.labels.check.name}],fields:[[{name:"user_name",label:e.labels.fields.name},{name:"user_email",label:e.labels.fields.email},{name:"user_message",type:"textarea",label:e.labels.fields.message}]],params:$.extend({type:"checkout"},e.params),reset:!0,target:e.target});b.core.on("FORM_PROCESS_ERROR FORM_PROCESS_SUCCESS FORM_VALIDATION_ERROR",function(b,d){switch(b.type){case "FORM_PROCESS_ERROR":alert(d.alert);
break;case "FORM_PROCESS_SUCCESS":alert(d.alert);break;case "FORM_VALIDATION_ERROR":alert(d.alert)}}).addClass("big check-out");this.core=b.core});(function(){Object.defineProperties(plura.templates.checkout.end.Form.prototype,{items:{set:function(e){this._items(e)}}})})();
plura.obj(".templates.checkout.end.List",function(e){var b,c,d;this.refresh=function(a){var c,e,f,l=$("<ul/>").addClass("items");b.empty().append(l).prepend(d);for(c=0;c<a.length;c+=1){e=a[c];var k=$("<li/>").addClass("group");$("<span/>").text(e.name).addClass("group-label").appendTo(k);$("<ul/>").appendTo(k).addClass("group-items");e=k.appendTo(l);for(f in a[c].items)if(a[c].items.hasOwnProperty(f)){var k=a[c].items[f],m=$("<li/>").addClass("item item-"+k.data.ID),n=$("<ul/>").addClass("subitems").appendTo(m);
$("<li/>").addClass("icon").css("background-image","url("+k.data.img.dark+")").appendTo(n);$("<li/>").addClass("label").appendTo(n).html(k.data.title);m.appendTo(e)}}};c=$.extend(!0,{},{labels:{title:"List"}},e);b=$("<div/>").appendTo(e.target).addClass("list");d=$("<div/>").addClass("title").text(c.labels.title);this.core=b});(function(){Object.defineProperties(plura.templates.checkout.end.List.prototype,{items:{set:function(e){this.refresh(e)}}})})();
plura.obj(".templates.checkout.End",function(e){var b,c,d;this._items=function(a){void 0!==a&&(b.items=a,d.list&&(c.items=a))};d=$.extend(!0,{},{list:!0},e);e=$("<div/>").addClass("checkout-end");b=new plura.templates.checkout.end.Form({path:d.process,params:d.params,target:e});d.list&&(c=new plura.templates.checkout.end.List($.extend({target:e},d.list)));this.core=e;this.form=b;this.list=c});
(function(){Object.defineProperties(plura.templates.checkout.End.prototype,{items:{get:function(){return this._items()},set:function(e){this._items(e)}}})})();
plura.obj(".templates.Checkout",function(e){var b,c,d,a;d=$.extend(!0,{},{end:!0,labels:{sequence:{end:"Checkout"}}},e);b=$("<div/>").appendTo(e.target).addClass("checkout");a=new plura.templates.Sequence({items:function(){var a;d.end&&(c=new plura.templates.checkout.End(d.end),a=[{name:"end",label:d.labels.sequence.end,obj:c}]);return e.sequence?e.sequence.concat(a):a}(),parent:d.parent,target:b});a.core.on("CHANGE COMPLETE COMPLETE_ITEM EXIT",function(d,e){d.stopImmediatePropagation();switch(d.type){case "COMPLETE":var f,
l;if(1<a.items.length)for(l=[],f=0;f<a.items.length-1;f+=1)a.items[f].obj.cart&&l.push({name:a.items[f].name||"i"+f,items:a.items[f].obj.cart.items});c.items=l;break;case "EXIT":b.trigger("EXIT")}});this.core=b;this.sequence=a});
plura.obj(".templates.sequence.Breadcrumbs",function(e){var b,c,d,a,g=function(){b.trigger("PARENT")},h=function(a){b.trigger("SEQUENCE",$(a.target).data("index"))};this.refresh=function(a){var b,c;for(b=0;b<a.items.length;b+=1)c=[],d[b].off("click",h).removeClass("active completed disabled enabled"),a.items[b].completed||!b||b&&a.items[b-1].completed?(a.items[b].completed?c.push("completed"):c.push("enabled"),d[b].click(h)):c.push("disabled"),a.index===b&&c.push("active"),d[b].addClass(c.join(" "))};
c=$.extend(!0,{},{},e);b=$("<div/>").appendTo(c.target).addClass("breadcrumbs");(function(){var f;b.empty();d=[];c.parent&&$("<div/>").addClass("breadcrumbs-parent").text(c.parent).appendTo(b).click(g);a=$("<div/>").addClass("breadcrumbs-sequence-items").appendTo(b);for(f=0;f<c.items.length;f+=1)d[f]=$("<div/>").addClass("breadcrumbs-sequence-item breadcrumbs-sequence-item-"+f).text(c.items[f].label||f).data("index",f).appendTo(a)})();this.core=b});
plura.obj(".templates.sequence.PreviousNext",function(e){var b,c,d,a,g=function(a){a.stopImmediatePropagation();b.trigger("NEXT")},h=function(a){a.stopImmediatePropagation();b.trigger("PREVIOUS")},f=function(a){a.stopImmediatePropagation();b.trigger("PARENT")};this.refresh=function(b){a.off("click",h).off("click",f);d.off("click",g);if(!b.index&&e.parent||0<b.index)a.addClass("active").on("click",b.index?h:f);else a.removeClass("active");b.index<b.items.length-1&&b.items[b.index].completed?d.on("click",
g).addClass("active"):d.removeClass("active")};c=$.extend(!0,{},{},e);b=$("<div/>").appendTo(c.target).addClass("previous-next");d=$("<div/>").appendTo(b).addClass("previous-next-item next");a=$("<div/>").appendTo(b).addClass("previous-next-item previous");this.core=b});
plura.obj(".templates.Sequence",function(e){var b={chained:!0,navigation:{breadcrumbs:!0,previous_next:!0}},c,d,a,g,h,f,l,k,m,n=this,p=function(b){b!==a&&(g=a,a=b,r())},r=function(){var b;b=void 0===h[a].obj.completed||h[a].obj.completed;if(h[a].completed=b)c.trigger("COMPLETE_ITEM",{index:a}),a===h.length-1&&c.trigger("COMPLETE");else if(f.chained)for(b=a+1;b<h.length;b+=1){var d=b;h[d].completed=!1;"function"===typeof h[d].obj.reset&&h[d].obj.reset()}for(b=0;b<h.length;b+=1)d=[],h[b].obj.core.removeClass("active completed disabled enabled"),
h[b].completed||!b||b&&h[b-1].completed?void 0===h[b].obj.completed||h[b].obj.completed?d.push("completed"):d.push("enabled"):d.push("disabled"),a===b&&d.push("active"),h[b].obj.core.addClass(d.join(" "));void 0!==g&&c.removeClass("sequence-"+g);c.addClass("sequence-"+a);m&&m.refresh({index:a,items:h});k&&k.refresh({index:a,items:h})},t=function(a,b){a.stopImmediatePropagation();switch(a.type){case "PARENT":c.trigger("EXIT");break;case "SEQUENCE":p(b)}},q=function(b){b.stopImmediatePropagation();
switch(b.type){case "PARENT":c.trigger("EXIT");break;case "NEXT":p(a+1);break;case "PREVIOUS":p(a-1)}},v=function(a,b){a.stopImmediatePropagation();r(b)};this._items=function(){return h};(function(){f=$.extend(!0,{},b,e);c=$("<div/>").appendTo(f.target).addClass("sequence");if(f.navigation){l=$("<div/>").appendTo(c).addClass("sequence-nav");var a={target:l,items:f.items,parent:f.parent};f.navigation.breadcrumbs&&(k=new plura.templates.sequence.Breadcrumbs($.extend(!0,{},f.navigation.breadcrumbs,a)),
k.core.on("PARENT SEQUENCE",t));f.navigation.previous_next&&(m=new plura.templates.sequence.PreviousNext($.extend(!0,{},f.navigation.previous_next,a)),m.core.on("PARENT NEXT PREVIOUS",q))}var a=f.items,g;if(h){for(g=0;g<h.length;g+=1)h[g].obj.core.off("REFRESH",v).removeClass("completed");h=null}d&&d.remove();var y;d=$("<div/>").appendTo(c).addClass("sequence-items");h=[];for(g=0;g<a.length;g+=1)y=a[g].obj?a[g]:{obj:a[g]},h[g]=y,h[g].obj.core.appendTo(d).addClass("sequence-item").on("REFRESH",v);
p(0);n.core=c})()});(function(){Object.defineProperties(plura.templates.Sequence.prototype,{items:{get:function(){return this._items()}}})})();
plura.obj(".templates.structures.Content",function(e){var b,c,d,a=function(d,e){var k="string"===typeof d?h(d):d,m=void 0===e?!0:e;m&&(!m||b&&b[0]===k[0])||g(k,m);!m||b&&b[0]===k[0]||(b&&a(b,!1),b=k,c.trigger("REFRESH",k.data()))},g=function(a,b){!0===b?a.stop(!0).fadeIn().addClass("active"):a.stop(!0).fadeOut(function(){$(this).hide()}).removeClass("active")},h=function(a){a="object"===typeof a?a:{id:a};var b=[a.id,a.vanity||"",a.classes||""].join(" "),b=d[a.id]||$("<div/>").addClass("holder "+b).append(a.obj||
null).data(a).appendTo(c).hide();return d[a.id]=b};this.activate=a;this.disable=function(){b&&(a(b,!1),b=null)};this.get=h;e=$.extend(!0,{},{},e);c=$("<div/>").appendTo(e.target||"body").addClass(["content",e.classes||""].join(" "));d={};this.core=c;this.tree=d;return this});
plura.obj(".templates.structures.menu.MenuConverter",function(e){var b,c,d=function(b,e){var k,m,n,p,r,t,q;t=b.children("li");for(n=0;n<t.length;n+=1)r=t.eq(n),p=e?e+"_"+n:"i"+n,m={depth:p.split("_").length-1,id:p,label:r.children("a").html()},k=p+" node",q=r.children("a").click(h).addClass("trigger"),c[p]=r,r.children("ul").length?(q.click(a),d(r.children("ul"),p)):r.click(g),r.data(m).addClass(k)},a=function(a){b.trigger("_OPEN",$(a.currentTarget).parent())},g=function(a){b.trigger("_SELECT",$(a.currentTarget))},
h=function(a){a.preventDefault()};b=e.target.on("_OPEN _SELECT",e.handler);this.tree=c={};d(b)});
plura.obj(".templates.structures.Menu",function(e){var b,c,d,a,g=this,h=function(e,f){var g=void 0===f?!0:f;if(!g||b&&b[0]===e[0]){if(g)return;b=null}else b&&h(b,!1),b=e;var k="selected selected-"+e.data("id");g?(c.addClass(k),e.addClass("active")):(c.removeClass(k),e.removeClass("active"));var k=e.data("id").replace(/i(.+)/,"$1").split("_").slice(0,-1),l,m;if(k.length)for(l=0;l<k.length;l+=1)m="i"+k.slice(0,l?-l:k.length).join("_"),g?(0===l&&a[m].addClass("parent"),a[m].addClass("ancestor ancestor-"+
l)):g||(0===l&&a[m].removeClass("parent"),a[m].removeClass("ancestor ancestor-"+l));if(g){if(d.url){k=e.data();g=r(k);k=[k];l=[];g&&(k=g.concat(k));for(g=0;g<k.length;g+=1)l.push(k[g].vanity||k[g].id);url.path=l.join("/")}c.trigger("SELECT",e.data())}},f=function(b,e){var g,h,k=b.data("id").replace(/i(.+)/,"$1").split("_");if(void 0===e?!b.hasClass("open"):e){d.close&&c.find(".open").each(function(a){$(this).data("id").match(b.data("id"))||f($(this),!1)});for(g=0;g<k.length;g+=1)h="i"+k.slice(0,g?
-g:k.length).join("_"),a[h].addClass("open");c.trigger("OPEN",b.data())}else b.removeClass("open")},l=function(a){return d.leaf?d.leaf(a):a.children?!1:!0},k=function(a){return d.trigger?d.trigger(a):$("<a/>").prop({href:"#"}).html(a.label).click(function(a){a.preventDefault()})},m=function(b,e,f){var g,h,n,p;for(h=0;h<b.length;h+=1)n=f?f+"_"+h:"i"+h,p={data:b[h],depth:n.split("_").length-1,id:n,label:b[h].label||b[h].name||b[h].vanity||b[h].id||("string"===typeof b[h]?b[h]:n),vanity:b[h].id||b[h].vanity||
null},g=n+" node"+(p.vanity?" id-"+p.vanity:"")+(b[h][d.nodeID]?" id-"+b[h][d.nodeID]:""),g=$(d.tags.leaf||d.tags).appendTo(e).data(p).addClass(g),p=k(p).appendTo(g).addClass("trigger"),a[n]=g,l(b[h])?(g.click(u).addClass("leaf"),c.trigger("COMPLETE_ITEM",g.data())):(p.click(w),g=$(d.tags.branch||d.tags).appendTo(g).addClass("branch"),m(b[h].children,g,n))},n=function(b){c.empty();a={};g.tree=a;d.data=b;m(d.data,c);d.first&&q(d.first);c.trigger("COMPLETE")},p=function(c){var d;if(void 0===c||"boolean"===
typeof c){if(b)return b;for(d in a)if(a.hasOwnProperty(d)&&l(a[d].data("data")))return a[d]}else{if("string"===typeof c)return a[c];if("number"===typeof c)return a["i"+c]}},r=function(b){var c,d,e=b.id.split("_");if(1<e.length){c=[];for(b=1;b<e.length;b+=1)d=e.slice(0,b?-b:e.length).join("_"),c.push(a[d].data());c=c.reverse()}return c},t=function(b){var d=new plura.templates.structures.menu.MenuConverter({handler:v,target:b});c=b;a=d.tree;g.tree=a},q=function(a){a=p(a);h(a)},v=function(a,b){a.stopImmediatePropagation();
switch(a.type){case "_OPEN":f($(b));break;case "_SELECT":h($(b))}},w=function(a){f($(a.currentTarget).parent())},u=function(a){h($(this))};this.activate=h;this.ancestors=r;this.disable=function(){if(b){var a=b.data();h(b,!1);c.trigger("UNSELECT",a)}};this.get=p;this.refresh=n;this.select=q;d=$.extend(!0,{},{close:!0,data:null,first:!1,id:"",leaf:null,nodeID:"nodeID",object:null,tags:{branch:"<ul/>",leaf:"<li/>"},url:null},e);d.object?t(d.object):(c=$(d.tags.branch||d.tags).appendTo(d.target||"body"),
d.data&&n(d.data));g.core=c.addClass("menu "+d.id)});
plura.obj(".templates.structures.Tabs",function(e){var b,c,d,a,g=function(a){a=c.tree[a]?c.tree[a].data():"object"===typeof a?a:{id:a};return d.get({classes:h(a.id).join(" "),id:a.id,vanity:a.vanity})},h=function(a){var b=[],c=a.split("_").slice(0,-1);for(a=0;a<c.length;a+=1)b[a]=a?b.join("_")+"_"+c[a]:c[a].replace(/i/,"p");return b};this.disable=function(){c.disable();d.disable()};this.get=g;this.refresh=function(){c.refresh(a.tree)};this.select=function(a){c.select(a)};a=$.extend(!0,{},{first:!1,
delay:!1,id:null,menu:{},tree:null},e);b=$("<div/>").appendTo(a.target||"body").addClass("plura templates tabs core "+(a.id||""));c=new plura.templates.structures.Menu($.extend(!0,{},a.menu,{target:b,first:a.first}));c.core.on("COMPLETE COMPLETE_ITEM OPEN SELECT",function(a,c){a.stopPropagation();if("SELECT"===a.type){var e=g(c.id);d.activate(e)}b.trigger("MENU_"+a.type,c)});this.content=d=new plura.templates.structures.Content({target:b});this.core=b;this.menu=c;return this});
plura.obj(".utils.Cache",function(e){var b=(new Date).getTime();e+=e.match(/\?/)?e.match(/\&$/)?"":"&":"?";return e+b});plura.obj(".utils.Extend",function(e,b){function c(){}c.prototype=new e;b.prototype=new c;return b});
plura.obj(".utils.Flat",function(e,b,c){var d=[],a,g=b||{},h,f=plura.utils.Flat;for(a in e)if(e.hasOwnProperty(a))if(e[a]instanceof Array)for(b=0;b<e[a].length;b+=1)if("object"===typeof e[a][b]&&!(e[a][b]instanceof Array))d=d.concat(f(e[a][b],g,a));else{if("number"===typeof e[a][b]||"string"===typeof e[a][b])h=$.extend({},g),h[a]=e[a][b],d.push(h)}else"object"===typeof e[a]&&(g[c]=a,d=d.concat(f(e[a],g)));return d});
plura.obj(".utils.Hidden",function(e){var b=(new Date).getTime(),c=function(c){e.parents("body *").each(function(){$(this).is(":animated")||(!c&&void 0!==c||"none"!==$(this).css("display")?!1===c&&$(this).hasClass("i"+b)&&$(this).removeClass("i"+b).hide():$(this).addClass("i"+b).show())})};this.get=function(){c();var b={width:e.width(),height:e.height(),innerWidth:e.innerWidth(),innerHeight:e.innerHeight(),outerWidth:e.outerWidth(),outerHeight:e.outerHeight()};c(!1);return b};this.show=c});
plura.obj(".utils.String",{path:function(e,b){var c=[],d,a,g,h;d=function(a){a.match(/^https?:\/\//)||(a=window.location.href.replace(/[^\/]+$/,"")+a);return a};e=d(e);b=b?d(b):window.location.href;b.match(/^http/)&&(g=b.replace(/(https?:\/\/)(.+)(\/([^\/]+)?)$/g,"$1$2").split("/"));a=g.length;for(d=0;d<a;d+=1){if(e.match(g.join("/"))){h=e.replace(g.join("/"),"");break}g.splice(-1);c.push("..")}return c.length?c.join("/")+h:h.replace(/^\//,"")},test:function(e,b,c){var d,a,g=0;e=e instanceof Array?
e:[e];for(d=0;d<e.length;d+=1)a="string"===typeof e[d]?new RegExp(e[d].replace(/^(\/)(.*)(\/)$/,"$2")):e[d],a.test(b)&&(g+=1);return!g||c&&g<e.length?!1:!0}});