/**
 * Plura P Javascript Framework [http://plura.pt]
 * 
 * Copyright (c) 2016 Plura
 *
 * Date: 2016-09-13 12:00:00 (Tue, 13 Sep 2016)
 * Revision: 6246
 */
var plura={obj:function(e,b){var a,d=e.split("."),c=window;e.match(/^\./)&&(d=["plura"].concat(d.splice(1)));for(a=0;a<d.length;a+=1){if(void 0!==b)c[d[a]]=a<d.length-1?c[d[a]]||{}:b;else if(a<d.length-1&&void 0===c[d[a]])return;c=c[d[a]]}return c}};
plura.obj(".constants",{Paths:{PHP:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.php"):null,SWF:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.swf"):null},RegExp:{EMAIL:/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,EMPTY:/^\s*$/}});plura.obj(".events.EventDispatcher",function(){});
plura.events.EventDispatcher.prototype={constructor:plura.events.EventDispatcher,apply:function(e){e.addEventListener=plura.events.EventDispatcher.prototype.addEventListener;e.hasEventListener=plura.events.EventDispatcher.prototype.hasEventListener;e.removeEventListener=plura.events.EventDispatcher.prototype.removeEventListener;e.dispatchEvent=plura.events.EventDispatcher.prototype.dispatchEvent},addEventListener:function(e,b){void 0===this._listeners&&(this._listeners={});var a=this._listeners,d,
c=e.split(" ");for(d=0;d<c.length;d+=1)void 0===a[c[d]]&&(a[c[d]]=[]),-1===a[c[d]].indexOf(b)&&a[c[d]].push(b)},hasEventListener:function(e,b){if(void 0===this._listeners)return!1;var a=this._listeners;return void 0!==a[e]&&-1!==a[e].indexOf(b)?!0:!1},removeEventListener:function(e,b){if(void 0!==this._listeners){var a=this._listeners[e],d;void 0!==a&&(d=a.indexOf(b),-1!==d&&a.splice(d,1))}},dispatchEvent:function(e,b){if(void 0!==this._listeners){var a={type:e},d=this._listeners[e],c,g,h;if(void 0!==
d){a.target=this;c=[];g=d.length;for(h=0;h<g;h+=1)c[h]=d[h];for(h=0;h<g;h+=1)c[h].call(this,a,b)}}}};
plura.obj(".core.Loader",function(e){var b,a,d,c,g,h,f,l=function(d){"img"===d.dataType?a[d.name]=$(new Image).on("error",m).on("load",n).prop({src:d.path}):$.ajax({url:d.path,dataType:d.dataType,type:d.type,success:function(c){a[d.name]=c;k(a[d.name])},error:function(a,d,c){b.trigger("LOADER_ERROR",p())}})},k=function(a){c[d]=a;h=Math.ceil((d+1)/f.length*100);b.trigger("LOADER_COMPLETE_ITEM",p());d<f.length-1?(d+=1,q(d)):b.trigger("LOADER_COMPLETE",p())},m=function(a){b.trigger("LOADER_ERROR",p())},
n=function(a){a=$(a.target);k(a)},p=function(){return{content:a,index:d,items:c,item:$.extend({},f[d],{obj:a[f[d].name]}),progress:h}},q=function(a){l(f[a]);b.trigger("LOADER_CHANGE",p())},t=function(){f&&"img"===f[d].dataType&&a[f[d].name].off("load")},r=function(b){t();a={};c=[];d=0;var h=$.extend([],b);for(b=0;b<h.length;b+=1)h[b].dataType||(h[b].path.match(/\.(jpg|png|gif)$/i)?h[b].dataType="img":h[b].dataType="text"),h[b].label||(h[b].label=h[b].path.match(/([^\/?]+\.[^\/?]+)$/)[1]),h[b].type||
(h[b].type="GET"),g.cache||(h[b].path=plura.utils.Cache(h[b].path));f=h;q(d)};this._data=function(d){if(void 0===d)return a;r(d)};this._items=function(){return c};this.pause=t;g=$.extend(!0,{},{data:null,cache:!1,log:!1},e);this.core=b=g.target||$(window);g.data&&r(g.data);return this});(function(){Object.defineProperties(plura.core.Loader.prototype,{data:{get:function(){return this._data()},set:function(e){this._data(e)}},items:{get:function(){return this._items()}}})})();
plura.obj(".ecommerce.Cart",function(e){var b=this,a,d,c=function(b){var c,g={units:0,value:0},e;if("object"===typeof b)return{i:{units:b.units,value:b.value*b.units}};"string"===typeof b&&a?c=a[b]:d&&(c=d);if(c)for(e in c)c.hasOwnProperty(e)&&(g.units+=c[e].units,g.value+=c[e].total);return g},g=function(a){for(var d in a)if(a.hasOwnProperty(d))return!1;return!0};this.add=function(c){0<c.units?(d=d||{},d[c.id]?d[c.id].update(c):d[c.id]=new plura.ecommerce.CartItem(c),c.group&&(a=a||{},a[c.group]=
a[c.group]||{},a[c.group][c.id]=d[c.id])):(delete d[c.id],g(d)&&(d=null),a&&a[c.group]&&(delete a[c.group][c.id],g(a[c.group])&&(delete a[c.group],g(a)&&(a=null))));b.dispatchEvent("REFRESH",c)};this.getTotal=c;this._group=function(){return a};this._items=function(){return d};this._length=function(){var a,c=0;if(d)for(a in d)d.hasOwnProperty(a)&&(c+=1);return c};this._total=function(){return c()};$.extend({},!0,{currency:"\u20ac"},e)});
(function(){Object.defineProperties(plura.ecommerce.Cart.prototype,{group:{get:function(){return this._group()}},length:{get:function(){return this._length()}},items:{get:function(){return this._items()}},total:{get:function(){return this._total()}}});plura.events.EventDispatcher.prototype.apply(plura.ecommerce.Cart.prototype)})();
plura.obj(".ecommerce.CartItem",function(e){this.id=this.group=this.data=null;this.label="item";this.units=this.value=0;var b=this,a=function(a){for(var c in a)a.hasOwnProperty(c)&&c.match(/(data|group|id|label|value|units)/)&&(b[c]=a[c])};this.update=a;this._total=function(){return b.value*b.units};e&&a(e)});(function(){Object.defineProperties(plura.ecommerce.CartItem.prototype,{total:{get:function(){return this._total()}}})})();
plura.obj(".events.Touch",function(e){var b,a,d,c,g,h,f,l,k,m=function(){f=h=g=c=d=a=0;k=l=null};b=$.extend(!0,{},{length:72,target:null},e);this.core=b.target;m();b.target.on("MSPointerDown MSPointerMove MSPointerUp MSPointerOver MSPointerOut touchstart touchend touchmove touchcancel",function(e){e.stopImmediatePropagation();switch(e.type){case "MSPointerUp":case "touchend":e.preventDefault();1===a&&0!==g&&(f=Math.round(Math.sqrt(Math.pow(g-d,2)+Math.pow(h-c,2))),f>=b.length&&(l=Math.round(180*Math.atan2(h-
c,d-g)/Math.PI),0>l&&(l=360-Math.abs(l)),k=45>=l&&0<=l?"left":360>=l&&315<=l?"left":135<=l&&225>=l?"right":45<l&&135>l?"down":"up"),b.target.trigger("TOUCHSWIPE",{direction:f>=b.length?k:!1}));m();break;case "touchcancel":m();break;case "MSPointerMove":case "touchmove":e.preventDefault();e.originalEvent.touches&&1!==e.originalEvent.touches.length?m():(g=e.originalEvent.pageX||e.originalEvent.touches[0].pageX,h=e.originalEvent.pageY||e.originalEvent.touches[0].pageY,b.target.trigger("TOUCHMOVE",{delta:{x:d-
g,y:c-h},position:{x:g,y:h}}));break;case "MSPointerDown":case "touchstart":e.preventDefault(),a=e.originalEvent.touches?e.originalEvent.touches.length:1,1===a?(d=e.originalEvent.pageX||e.originalEvent.touches[0].pageX,c=e.originalEvent.pageY||e.originalEvent.touches[0].pageY):m()}})});
plura.obj(".form.elements.FormLabel",function(e){var b=e.field,a=e.target,d=e.data.name,c=e.data.label,g=e.data.type;e=c&&c.align?c.align:g&&g.match(/(checkbox|radio)/)?plura.form.FormLabelAlignType.RIGHT:plura.form.FormLabelAlignType.LEFT;c=c&&(c.text||(typeof c).match(/(string|number)/))?c.text||c:d;d=$("<label/>").text(c).prop({"for":d}).addClass("type-"+(g||"text"));switch(e){case plura.form.FormLabelAlignType.LEFT:d.insertBefore(b);break;case plura.form.FormLabelAlignType.LEFT_WRAP:d.append(b).appendTo(a);
break;case plura.form.FormLabelAlignType.RIGHT:d.insertAfter(b);break;case plura.form.FormLabelAlignType.RIGHT_WRAP:d.prepend(b).appendTo(a)}return d});
plura.obj(".form.elements.FormSelect",function(e){var b,a=function(d,c){var b,h,f;for(b=0;b<c.length;b+=1)if(c[b].values||c[b]instanceof Array)h=c[b].values&&c[b].label?c[b].label:"group"+b,f=c[b].values||c[b],h=$("<optgroup/>").prop({label:h}).appendTo(d),a(h,f);else{h=d;f=c[b];var l,k;"string"===typeof f?l=k=f:(k=void 0!==f.value?f.value:f[e.name],l=f.label||f.name||f.value);h=$("<option/>").prop({value:k}).appendTo(h).html(l);f.data&&h.data(f.data)}};this.prop=function(a){b.prop(a)};this.data=
function(d){b.empty();"select"===e.type&&b.append("<option/>");a(b,d)};this.val=function(a){b.val(a)};this.core=b=$("<select/>")});
plura.obj(".form.Form",function(e){var b,a,d,c,g,h=function(a){var c=d[a.name].field;a.values&&a.type&&a.type.match(/(list|select)/)&&c.data(a.values);a.value&&c.val(a.value)},f=function(a,d){var h,e,g=a||(c.submit?c.fields.concat([{type:"submit",value:c.submit}]):c.fields);for(h=0;h<g.length;h+=1)g[h]instanceof Array||g[h].fields||g[h].type&&g[h].type.match(/^(field)?set$/i)?(e=$("<fieldset/>").appendTo(d||b).prop({name:g[h].name}),g[h]instanceof Array||$("<legend/>").appendTo(e).text(g[h].label||
g[h].name),f(g[h].fields||g[h],e)):l(g[h],d||b)},l=function(a,b){var f,e,l;$("<div/>");var r;switch(a.type){case "list":case "select":e=new plura.form.elements.FormSelect(a);f=e.core;break;case "textarea":f=$("<textarea/>");a.wysiwyg&&window.tinyMCE&&(r=tinymce.DOM.uniqueId(),f.addClass(r+" tinyMCE").prop({id:r}).appendTo(b),setTimeout(function(){console.log(f.outerWidth());tinyMCE.init($.extend(!0,c.tinyMCE,{editor_selector:r,width:a.wysiwyg&&a.wysiwyg.width?a.wysiwyg.width:f.outerWidth()},"object"===
typeof a.wysiwyg?a.wysiwyg:null))},100));break;case "file":e=new plura.form.Upload($.extend({name:a.name,target:b},c.upload,a.options));f=e.core;g.push(e);break;default:f=$("<input/>"),jQuery.ui&&"date"===a.type&&f.datepicker({dateFormat:"yy-mm-dd"})}k(f,a);a.change&&f.change(a.change);a.type&&(a.type.match(/file/)||a.type.match(/textarea/)&&a.wysiwyg)||f.appendTo(b);a.label&&(l=new plura.form.elements.FormLabel({data:a,field:f,target:b}));d[a.name]={data:a,field:e||f,label:l};void 0===a.value&&!a.values||
a.type&&!a.type.match(/(list|select|submit|text|textarea)/)?a.type&&a.type.match(/(checkbox|radio)/)&&a.checked&&f.prop("checked",!0):h(a)},k=function(a,b){var d=b.name,f={},h=$.extend;b.disabled&&h(f,{disabled:b.disabled});(c.id||b.id)&&h(f,{id:!0===b.id?b.name:b.id});b.type&&b.type.match(/(list|select|textarea)/)||h(f,{type:b.type&&"date"!==b.type?b.type:"text"});b.type&&b.type.match(/list/)&&h(f,{multiple:!0,size:b.size||1});b.value&&b.type.match(/(checkbox|radio)/)&&h(f,{value:b.value});b.type&&
b.type.match(/list/)&&(d+="[]");h(f,{name:d});(a.core||a).prop(f)};this._query=function(){return a._query()};this._params=function(b){return a._params(b)};this.populate=function(a){var b,c,f;for(b in a)if(a.hasOwnProperty(b)&&d[b])switch(c=d[b].field,f=d[b].data,f.type){case "checkbox":c.prop("checked","0"!==a[b]);break;default:f.type&&f.type.match(/textarea/i)&&f.wysiwyg?tinyMCE.get(c.prop("id")).setContent(a[b]||""):f.type&&f.type.match(/file/)||c.val(a[b])}};this.refresh=function(a){var b,c;for(c in a)a.hasOwnProperty(c)&&
d[c]&&(b=$.extend(!0,{},d[c].data,{values:a[c]}),h(b))};this.reset=function(b){a.reset(b)};c=$.extend(!0,{},{alert:{success:"Success! Content updated!",error:"Error! Content not updated! :("},check:null,fields:null,id:!1,path:null,params:null,reset:!1,send:!0,submit:"Submit",tinyMCE:{mode:"specific_textareas",menubar:!1,theme:"modern",plugins:"fullscreen code link",toolbar:["bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent","formatselect subscript superscript code fullscreen | link unlink"]}},
e);b=$("<form/>").appendTo(c.target).addClass("p-form");g=[];d={};this.core=b;this.objects=d;this.uploads=g;f();a=new plura.form.FormManager($.extend(!0,{},{ajax:c.ajax||{},alert:c.alert||{},check:c.check||{},params:c.params||{}},{path:c.path,reset:c.reset,send:c.send,target:this,type:"getJSON"}));return this});(function(){Object.defineProperties(plura.form.Form.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(e){this._params(e)}}})})();
plura.obj(".form.FormLabelAlignType",{LEFT:"left",LEFT_WRAP:"left_wrap",RIGHT:"right",RIGHT_WRAP:"right_wrap"});
plura.obj(".form.FormManager",function(e){var b,a,d,c=function(a){b.find("input[type=file]").each(function(c){d[c]=new plura.form.Upload($.extend({name:$(this).attr("name"),target:b},a));d[c].core.replaceAll($(this))})},g=function(a){var c=$.extend({},{not:":button, :submit, :reset",checked:!0,selected:!0,upload:!0}),f=b.find(":input").not(c.not);f.not(":checkbox, :radio").val("");c.checked&&f.prop("checked",!1);c.selected&&f.prop("selected",!1);for(c=0;c<d.length;c+=1)d[c].reset(a);window.tinyMCE&&
b.find(".tinyMCE").each(function(){tinymce.get($(this).prop("id")).setContent("");tinymce.get($(this).prop("id")).nodeChanged()})},h=function(){var c=a.path||window.location.href,d=function(a,b){return"string"===typeof a?a:a.alert?a:$.extend(!0,{},a,{alert:b})};console&&console.log(a.ajax.dataType+" | "+a.ajax.type+" | "+c+":"+f());$.ajax({url:c,data:f(),dataType:a.ajax.dataType,type:a.ajax.type,success:function(c){b.trigger("FORM_REQUEST_SUCCESS",d(c,a.alert.complete));!c.success||"true"!==c.success&&
1!==c.success?(c.success&&"false"===c.success||0===c.success)&&b.trigger("FORM_PROCESS_ERROR",d(c,a.alert.error)):(a.reset&&g(!0),b.trigger("FORM_PROCESS_SUCCESS",d(c,a.alert.success)))},error:function(a,c,b){}});b.trigger("FORM_SUBMIT",{alert:a.alert.submit})},f=function(){return b.serialize()+"&"+$.param(a.params||{})};this._query=f;this._params=function(c){void 0!==c&&(a.params=$.extend(!0,a.params||{},c));return a.params};this.reset=g;a=$.extend(!0,{},{ajax:{dataType:"json",type:"GET"},alert:{complete:"Your form was submited.",
error:"There was an error processing your form.",field:"Please correctly fill the % field. Thank you",submit:"Form is being submitted. Please wait.",success:"Your form was successfully processed! Thank you."},check:!1,params:null,path:null,replace:!0,reset:!1,send:!0,target:null,upload:{}},e);b=a.target.core||a.target;d=a.target.uploads||[];this.form=b;a.replace&&c(a.upload);b.submit(function(c){c.preventDefault();window.tinyMCE&&tinyMCE.triggerSave();if(!(c=!a.check))a:{var d,f,e,g;for(d=0;d<a.check.length;d+=
1)for(c=a.check[d],e=c.rules?c.rules instanceof Array?c.rules:[c.rules]:[{alert:c.alert||null}],f=0;f<e.length;f+=1)if(g=plura.utils.String.test([/\./,/#/],c.id)?b.find(c.id):b.find("*[name="+c.id+"]"),e[f].exp&&!plura.utils.String.test(e[f].exp,g.val())||!e[f].exp&&g.val().match(/^\s*$/)){c=e[f].alert||a.alert.field.replace(/%/,c.id);b.trigger("FORM_VALIDATION_ERROR",{alert:c});c=!1;break a}b.trigger("FORM_VALIDATION_SUCCESS");c=!0}c&&a.send&&h()}).find("input[type=reset]").click(function(a){a.preventDefault();
g()})});(function(){Object.defineProperties(plura.form.FormManager.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(e){this._params(e)}}})})();
plura.obj(".form.upload.File",function(e){var b,a,d,c,g,h,f=function(){a.slideUp("slow",m);h.reset()},l=function(c){$.getJSON(g.process,{action:"delete",file:d.file,path:g.path,type:"upload"},function(b){"true"===b.success&&c&&(f(),a.trigger("FORM_UPLOAD_REMOVE",g.id))})},k=function(c){var b;d&&!c?(g.confirm&&(b=confirm(g.label.confirm)),g.confirm&&!b||l(!0)):d&&c?f():d||(g.swf.cancel(g.id),f(),a.trigger("FORM_UPLOAD_CANCEL",g.id))},m=function(){$(this).remove()},n=function(a){var c;return g.css?
(c={height:20,margin:5,width:100,button:{border:"none","float":"right","text-align":"center",width:50},file:{"float":"left",width:"100%"},progress:{"float":"left"}},"object"===typeof g.css&&(c=$.extend(!0,c,g.css)),"file"===a?c.file.width=c.width-3*c.margin-c.button.width:"button"===a?c.button.height=c.height:c.file["margin-bottom"]=g.margin,c[a||"file"]):!1};this.clean=function(){d&&l();b.val(g.label.cancel)};this.update=function(f){d=f;c=c||$("<input/>").prop({type:"hidden",name:e.name+"[]"}).appendTo(a);
c.val(d.file+"|"+d.name);b.val(g.label.remove)};this.reset=k;this.refresh=function(a){h.refresh(a)};g=$.extend(!0,{},{css:!1,confirm:!0,label:{cancel:"Cancel",confirm:"Do you wish to remove this item?",remove:"Delete"},swf:null},e);a=$("<div/>").addClass("file i"+g.id).appendTo(g.target).attr("data-name",g.filename);h=new plura.layout.ProgressBar({target:a,css:g.css?{core:n("file")}:null});b=$("<input/>").prop({type:"button"}).val(g.label.cancel).addClass("file-trigger").appendTo(a).click(function(a){k()});
g.css&&(a.css(n()||""),b.css(n("button")||""));this.core=a;return this});
plura.obj(".form.Upload",function(e){var b,a,d,c,g,h,f,l=function(){var a;b.children(".files").length?a=b.children(".files"):(a=$("<div/>").appendTo(b).addClass("files"),c.css&&a.css(m("files")||""));return a},k=function(){a=null;b.addClass("empty").children(".files").slideUp("slow",function(){$(this).remove()})},m=function(a){if(c.css){var b={height:30,margin:5,width:220,file:{},files:{"float":"left","background-color":"#e0e0e0"},trigger:{border:"none","float":"right","text-align":"center",width:70}};
"object"===typeof c.css&&(b=$.extend(!0,b,c.css));"file"===a?b.file.width={width:c.width}:"files"===a?b.files=$.extend(!0,b.files,{"margin-top":c.margin,padding:c.margin+"px "+c.margin+"px 0 "+c.margin+"px",width:c.width-2*c.margin}):"trigger"===a?b.trigger.height=b.height:b={position:"relative",width:b.width};return b[a]||b}return!1},n=function(c,b){c.stopImmediatePropagation();delete a["i"+b];var d,f=0;for(d in a)a.hasOwnProperty(d)&&(f+=1);0===f&&k()},p=function(a){g=swfobject.getObjectById(a.id);
c.swf.position&&setTimeout(function(){var c=$("<div/>");c.replaceAll(b);$("body").prepend(b);$("#"+a.id).css({position:"absolute",left:h.position().left,top:h.position().top,zIndex:100}).prop({width:h.outerWidth(),height:h.outerHeight()});b.replaceAll(c)},0)},q=function(a,c,b){"true"===b.success&&f.instances["i"+a].update(c,b)},t=function(a,c,b){f.instances["i"+a].init(c,b)},r=function(a,c,b){f.instances["i"+a].refresh(c,b)},v=function(a){console&&console.log(a)};this.init=function(d,f){c.multiple||
!c.multiple&&!a?(a=a||{},a["i"+d]=new plura.form.upload.File($.extend(!0,{},c.file,{id:d,css:m("file"),filename:f,name:c.name,path:plura.utils.String.path(c.path,c.process||plura.constants.Paths.PHP),process:c.process||plura.constants.Paths.PHP,swf:g,target:l()})),a["i"+d].core.on("FORM_UPLOAD_CANCEL FORM_UPLOAD_REMOVE",n),d||b.removeClass("empty")):!c.multiple&&a&&a["i"+d].clean()};this.refresh=function(c,b){a["i"+c].refresh(b)};this.reset=function(c){if(a){for(var b in a)a.hasOwnProperty(b)&&(a[b].reset(c),
delete a[b]);k()}};this.update=function(c,b){a["i"+c].update(b)};f=plura.form.Upload;void 0===f.count?(f.complete=q,f.count=0,f.instances={},f.init=t,f.refresh=r,f.test=v):f.count+=1;d=f.count;f.instances["i"+f.count]=this;c=$.extend(!0,{},{css:!1,file:null,label:{upload:"Upload"},limit:0,multiple:!1,path:"",obj:"plura.form.Upload",swf:{params:{allowscriptaccess:"always",menu:"false",wmode:"transparent"},position:!1,test:!1,version:"10.0"},process:null},e);b=$("<div/>").addClass(function(){var a=
["upload","upload-"+d,"upload-"+c.name,"empty"];c.multiple&&a.push("multiple");return a.join(" ")}()).appendTo(c.target);h=$("<input/>").prop({type:"button",value:c.label.upload}).addClass("upload-trigger").appendTo(b);c.css&&(b.css(m()||"").addClass("has-css"),h.css(m("trigger")||""));this.core=b;(function(){var a=$("<div/>").attr({id:"plura_form_upload_"+d}).appendTo(b),f={id:d,limit:c.limit,multiple:c.multiple,obj:c.obj,path:plura.utils.String.path(c.path,c.process||plura.constants.Paths.PHP),
process:c.process||plura.constants.Paths.PHP,test:c.swf.test,type:"upload"};swfobject.embedSWF(plura.constants.Paths.SWF,a.attr("id"),1,1,c.swf.version,null,f,c.swf.params,null,p)})();return this});
plura.obj(".fx.Center",function(e){var b=e.target||e.obj.parent(),a=function(a){var c=e.dimensions,b=e.obj;return c&&c[a]?c[a]:b[a]()},d=function(a){var c=e.obj;return b&&$.isPlainObject(b)&&void 0!==b[a]?b[a]:b&&!$.isPlainObject(b)?b.offset()[a]-c.offsetParent().offset()[a]:0},c=function(a){var c=e.obj,b=e.target;return b&&$.isPlainObject(b)&&void 0!==b[a]?b[a]:b&&!$.isPlainObject(b)?b[a]():c.parent().length?c.parent()[a]():c[a]()},g=a("height"),a=a("width"),h=c("height"),f=d("left"),d=d("top"),
c=c("width");e.obj.css({top:(h-g)/2+d,left:(c-a)/2+f,position:"absolute"!==e.obj.css("position")?"absolute":""})});
plura.obj(".fx.Parallax",function(e){var b,a,d,c,g,h,f,l,k,m=function(){return{height:g.dimensions&&g.dimensions.height?g.dimensions.height:g.target.height(),width:g.dimensions&&g.dimensions.width?g.dimensions.width:g.target.width()}},n=function(){return f.x+a.x>f.x&&f.x+a.x<f.x+f.width&&f.y+a.y>f.y&&f.y+a.y<f.y+f.height?!0:!1};g=$.extend(!0,{},{enabled:{x:!0,y:!0},dimensions:null,rectangle:{width:0,height:0,y:0,x:0},restrict:{x:!0,y:!0},speed:8,target:null},e);b=g.enabled;l=g.restrict;k=g.target;
d=k.position().left;c=k.position().top;a={x:0,y:0};h={x:0,y:0};$(document).mousemove(function(c){a={x:c.pageX-k.parent().offset().left-f.x,y:c.pageY-k.parent().offset().top-f.y}});setInterval(function(){f=g.rectangle?{y:g.rectangle.y||0,x:g.rectangle.x||0,height:g.rectangle.height||g.target.parent().height(),width:g.rectangle.width||g.target.parent().width()}:!1;if(!(!f||!f.width&&b.x||!f.height&&b.y)){var e,q;h.x=isNaN(h.x)?0:h.x;h.y=isNaN(h.y)?0:h.y;b.x&&(d=n()?a.x:d,f.width<m().width&&l.x||f.width>
m().width&&!l.x?(e=-d*((m().width-f.width)/f.width)+f.x,h.x+=(e-k.position().left)/g.speed):b.x&&f.width>m().width&&l.x&&(e=((f.width-k.width)/2+d-k.position().left)/g.speed,h.x+=e),1<Math.abs(e-k.position().left)&&k.css({left:h.x}));b.y&&(c=n()?a.y:c,f.height<m().height&&l.y||f.height>m().height&&!l.y?(q=-c*((m().height-f.height)/f.height)+f.y,h.y+=(q-k.position().top)/g.speed):b.y&&f.height>m().height&&l.y&&(q=((f.height-k.height)/2+c-k.position().top)/g.speed,h.y+=q),1<Math.abs(q-k.position().top)&&
k.css({top:h.y}));k.trigger("PARALLAX",{dimensions:m(),inside:n(),mouse:a,rectangle:f,target:k,position:h})}},13);return this});
plura.obj(".fx.Resize",function(e){var b=$.extend(!0,{},{center:!1,increase:!0,height:void 0,inside:!1,target:void 0,width:void 0},e),a=b.obj,d=function(c){var d=e.target;if(!d&&b[c])return b[c];d||void 0!==b.width||void 0!==b.height||(d=a.parent());return d&&$.isPlainObject(d)&&void 0!==d[c]?d[c]:d&&!$.isPlainObject(d)?d[c]():a[c]()},c=d("height"),g=d("width");a.css(function(){var d,f,e=a.width(),k=a.height();if(b.increase||!b.increase&&(k>c||e>g))e/k>g/c&&b.inside||e/k<g/c&&!b.inside?(d=g/e*e,f=
d*k/e):(f=c/k*k,d=f*e/k);return{width:d,height:f}}());b.center&&plura.fx.Center({obj:b.obj,target:b.center.target||b.target,dimensions:b.center.dimensions||!1})});plura.obj(".layout.LoaderBar",function(e){var b;b=new plura.layout.ProgressBar(e);e.loader.core.on("LOADER_COMPLETE_ITEM",function(a,d){b.core.attr({"data-item-label":d.item.label});b.refresh(d.progress)})});
plura.obj(".layout.navigation.Nav",function(e){var b,a,d,c,g,h=function(c,d){d&&(!d||b&&b[0]===c[0])||(d?c.addClass("active"):c.removeClass("active"));!d||b&&b[0]===c[0]||(b&&h(b,!1),b=c,a.trigger("SELECT",c.data()))},f=function(b){a.find(".i"+b).length?h(a.find(".i"+b),!0):c[b].data({active:!0})},l=function(a){c[a].prop({src:g.path+(g.data[a].thumb||g.data[a].file)})},k=function(a){var c={core:{position:"absolute",zIndex:2},parallax:{core:{position:"absolute",zIndex:1},holder:{top:0,left:0,position:"absolute",
zIndex:2}}};"object"===typeof g.css&&(c=$.extend(!0,c,g.css));return plura.utils.Object.path(c,a)||""},m=function(a){h($(a.currentTarget),!0)},n=function(b){var e,h,k,n;b=$(b.target);var u=b.data("index");k=g.wrap?g.wrap(b).data(b.data()):b;b.data("active")&&f(b.data("index"));k=k.addClass("item i"+b.data("index")).click(m).appendTo(d||a);n=k.prev();(g.width||g.height)&&plura.fx.Resize({target:{width:g.width,height:g.height},obj:b,inside:!0});g.css&&(e=0!==u%g.limit&&0<u?n.width()+n.position().left+
g.margin:0,h=0!==u%g.limit&&0<u?n.position().top:0===u%g.limit&&0<u?n.position().top+n.height()+g.margin:0,k.css({position:"absolute",left:e,top:h}));g.parallax&&(e=0<u&&n.position().left+n.width()>e+k.width()?n.position().left+n.width():e+k.width(),h=0<u&&n.position().top+n.height()>h+k.height()?n.position().top+n.height():h+k.height(),k.parent().width(e).height(h));b.fadeIn();c[u+1]&&l(u+1);a.trigger("COMPLETE_ITEM",u);b.data("active")&&f(u)};this.select=f;g=$.extend(!0,{},{css:!1,height:null,holder:!1,
limit:0,margin:5,overflow:!1,path:"",parallax:{},text:!1,width:null},e);a=$("<div/>").appendTo(g.target||"body").addClass(["nav",g.text?"txt":"img"].join(" "));c=[];(function(b){var f;if(g.holder||g.parallax)d=$("<div/>").prependTo(a).addClass("holder");g.parallax&&(f=$.extend(!0,{target:d},g.parallax),new plura.fx.Parallax(f),g.css&&(d.css(k("parallax.holder")),g.overflow||a.css({overflow:"hidden",width:f.rectangle.width,height:f.rectangle.height})));for(f=0;f<b.length;f+=1)g.text?$("<a/>").appendTo(d||
a).addClass("item i"+f).data({index:f}).html(f+1).click(m):(c[f]=$(new Image).data({index:f}).hide().on("load",n),0===f&&l(f))})(g.data);g.css&&a.css(k("core"));this.core=a;return this});
plura.obj(".layout.navigation.PreviousNext",function(e){var b,a=0,d,c,g,h=function(e){e.stopImmediatePropagation();var h;e=$(e.currentTarget)[0]===c[0];!d.limit||e&&a+1<d.limit||!e&&0<=a-1?h=e?a+1:a-1:d.loop&&(h=e?0:d.limit-1);void 0!==h&&h!==a&&(a=h,d.limit&&d.controls&&f(),b.trigger("CONTROLS",{count:a}))},f=function(){!d.loop&&d.limit&&0===a?l(g,!1):l(g);!d.loop&&d.limit&&a===d.limit-1?l(c,!1):l(c)},l=function(a,c){void 0===c||c?a.on("click",h).addClass("active"):a.off("click",h).removeClass("active")},
k=function(a){var c=["p-previousnext"],f=d.controls,e;"parent"===a?e=d.target?$("<div/>").appendTo(d.target):f.previous.parent():(e="object"===typeof f[a]?f[a]:$("<div/>"),c=[c[0]+"-"+a,c[0]+"-controls",a],"object"!==typeof f[a]&&e.appendTo(b));return e.addClass(c.join(" "))};this._count=function(c){void 0!==c&&(a=c,d.limit&&d.controls&&f());return a};d=$.extend(!0,{},{limit:0,loop:!1,controls:{next:!0,parent:!0,previous:!0}},e);b=k("parent");d.controls&&(c=k("next"),g=k("previous"));this.core=b;
f();return this});(function(){Object.defineProperties(plura.layout.navigation.PreviousNext.prototype,{count:{get:function(){return this._count()},set:function(e){this._count(e)}}})})();
plura.obj(".layout.ProgressBar",function(e){var b,a,d,c=function(a){var c={core:{width:200,height:20,border:"2px solid #000"},bar:{backgroundColor:"#000"}};"object"===typeof d.css&&(c=$.extend(!0,c,d.css));return c[a]};this.refresh=function(c){b.attr({"data-percent":c});a.width(c+"%");100===c&&d.hide&&b.stop().fadeOut("slow");d.css&&"boolean"===typeof d.css&&a.height(b.height()).show()};this.reset=function(){a.fadeIn()};d=$.extend(!0,{},{bottom:!0,css:!1,hide:!1,horizontal:!0,target:null},e);b=$("<div/>").appendTo(d.target||
"body").addClass("p-progressbar");a=$("<div/>").appendTo(b).addClass("bar");d.css&&(b.css(c("core")||""),a.css(c("bar")||""));this.core=b});
plura.obj(".layout.Refresh",function(e){var b,a,d=0,c,g,h=function(c){var d=a.format?a.format(c):c;a.fade?b.fadeOut(a.speed,function(){$(this).html(d).fadeIn(a.speed)}):b.html(d);b.trigger("CHANGE");a.refresh&&(clearInterval(g),g=setInterval(k,a.time))},f=function(c,b){var d,f=[],e;for(d in a.data)a.data.hasOwnProperty(d)&&(e=Math.floor(d/b),f[e]=f[e]||[],f[e].push(c[d]));return f},l=function(a){h(a)},k=function(){"string"===typeof a.data?a.json?$.getJSON(a.data,null,l):$.get(a.data,null,l):"object"===
typeof a.data&&(h(c[d%c.length]),d+=1)};a=$.extend(!0,{},{data:!1,fade:!0,format:null,json:!1,limit:1,refresh:!0,speed:"slow",target:null,time:1E4},e);b=$("<div/>").appendTo(a.target||"body").addClass("p-refresh");"object"===typeof a.data&&(c=f(a.data,a.limit));k()});
plura.obj(".layout.Slideshow",function(e){var b={auto:!0,cache:!1,center:!1,css:!1,data:null,height:null,id:"",inline:!1,loop:0,navigation:!0,path:"",previousnext:!0,resize:!1,swipe:!1,target:null,timer:8E3,width:null,video:null},a,d,c,g=0,h,f,l,k,m,n,p,q,t=this,r=function(a){k&&clearTimeout(k);n&&n.core.remove();var b=[],f;for(f=0;f<a.length;f+=1)"string"===typeof a[f]?b.push({file:a[f]}):b.push(a[f]);c=b;1<c.length&&(h.navigation&&(n=new plura.layout.navigation.Nav($.extend(!0,{data:c,path:h.path,
target:d},h.navigation)),t.navigation=n,n.core.on("COMPLETE_ITEM SELECT",A)),h.previousnext&&(p=new plura.layout.navigation.PreviousNext($.extend(!0,{limit:a.length,loop:!0,target:d},h.previousnext)),t.previousnext=p,p.core.on("CONTROLS",B)),h.swipe&&(l=new plura.events.Touch($.extend({target:m},"object"===typeof h.swipe?h.swipe:null)),l.core.on("TOUCHMOVE TOUCHSWIPE",C)));v(g,!0)},v=function(b,f){f&&(void 0!==a&&a.removeClass("active").addClass("inactive").fadeOut(function(){$(this).remove()}),g=
b,a=u(c[g]).addClass("item active i"+g),d.trigger("CHANGE",{index:g}),n&&n.select(g),p&&p.count!==g&&(p.count=g),h.css&&a.css(h.css.media.item))},u=function(a){var c=a.data&&a.file,b=c?$("<div/>").addClass("mixed").appendTo(m):m,d,f;if(h.inline)m.css("background-image","url('"+y(a)+"')"),clearTimeout(k),k=setTimeout(w,h.timer);else if(a.data&&(d=$("<div/>").html(a.data).appendTo(b).addClass("data").hide().fadeIn()),a.file)if(a.file.match(/\.(gif|jpg|png)$/i)||a.type&&a.type.match(/image/i))a=y(a),
d=$(new Image).on("load",D).appendTo(b).prop({src:a}).hide();else if(a.file.match(/\.(mp4)$/i)||a.type&&a.type.match(/video/i))f=new plura.media.Video($.extend({src:y(a,!1),target:b},h.video)),d=f.core.on("METADATA",E);return $(c?b:d).data({video:f||!1})},w=function(){v(g<c.length-1?g+1:0,!0);0===g&&d.trigger("LOOP")},x=function(){v(0<g?g-1:c.length-1,!0)},y=function(a,c){var b=(h.path||"")+(a.path||"")+a.file;if(c||h.cache&&!1!==c)b+="?"+(new Date).getTime();return b},D=function(a){a=$(a.target).css({width:"",
height:""}).fadeIn();if(h.resize||h.center){var b,e={obj:a},g=h.center,l=h.resize;l&&"function"===typeof l?l(a):l&&("object"===typeof l&&(b=$.extend(!0,{},l,e)),console.log("resize"),plura.fx.Resize(b||e));!g||"function"!==typeof l&&l.center||("object"===typeof g&&(b=$.extend(!0,{},g,e)),plura.fx.Center(b||e))}!f&&1<c.length&&h.auto&&(clearTimeout(k),k=setTimeout(w,h.timer));d.trigger("COMPLETE_ITEM",a)},E=function(a){a.stopImmediatePropagation();d.trigger("COMPLETE_ITEM",$(a.target))},A=function(a,
c){a.stopImmediatePropagation();switch(a.type){case "SELECT":c.index!==g&&v(c.index,!0)}d.trigger("NAVIGATION_"+a.type,c)},B=function(a,c){a.stopImmediatePropagation();v(c.count,!0)},C=function(c,b){c.stopPropagation();var d;switch(c.type){case "TOUCHMOVE":a.css({left:-b.delta.x});break;case "TOUCHSWIPE":d=b.direction&&b.direction.match(/(left|right)/)?("left"===b.direction?-1:1)*a.outerWidth():0,a.animate({left:d},"slow"),"left"===b.direction?w():"right"===b.direction&&x()}},z=function(a){var c=
{core:{position:"relative"},media:{core:{position:"relative"},item:{position:"absolute"}}};"object"===typeof h.css&&(c=$.extend(!0,c,h.css));return plura.utils.Object.path(c,a)},F=function(){};this._index=function(a){if(void 0===a)return g;v(a,!0)};this._items=function(a){if(void 0===a)return c;r(a)};this.next=w;this.pause=function(c,b){clearTimeout(k);var d=void 0!==c?c:!f;d?d&&b&&a.data("video")&&a.data("video").pause(!0):k=setTimeout(w,h.timer);f=d};this.previous=x;(function(){h=$.extend({},b,
e);d=$("<div/>").appendTo(h.target||"body").addClass("p-slideshow "+h.id);m=$("<div/>").appendTo(d).addClass("media");f=!h.auto;"string"===typeof h.data?$.getJSON(h.data,function(a){r(a)}):h.data&&"object"===typeof h.data&&r(h.data);h.css&&(d.css(z("core")||""),m.css(z("media.core")||""));h.inline&&"boolean"!==typeof h.inline&&m.css(h.inline);t.core=d;t.media=m;q=plura.layout.Slideshow;q.items||(q.items=[],q.stop=F);q.items.push(t)})();return this});
(function(){Object.defineProperties(plura.layout.Slideshow.prototype,{index:{get:function(){return this._index()},set:function(e){this._index(e)}},items:{get:function(){return this._items()},set:function(e){this._items(e)}}})})();
plura.obj(".layout.Social",function(e){var b,a=function(a){var d=$("<div/>").appendTo(b).addClass("fb-like"),e=[];a=$.extend(!0,{},a,{height:"button_count"===a.layout?21:"box_count"===a.layout?65:a.show_faces?80:35,href:a.href||window.location.href});for(var f in a)a.hasOwnProperty(f)&&e.push(f+"="+(a[f]||""));$("<iframe/>").appendTo(d).css({width:a.width,height:a.height,border:"none",overflow:"hidden"}).prop({allowTransparency:"true",frameborder:0,scrolling:"no",src:"//www.facebook.com/plugins/like.php?"+
e.join("&")})},d=function(a){var d=$("<div/>").appendTo(b).addClass("twitter"),e=$("<a/>").appendTo(d).prop({href:"http://twitter.com/share"}).addClass("twitter-share-button").html("Tweet"),f=document.createElement("script"),l;for(l in a)a.hasOwnProperty(l)&&("related"===l?a[l].user&&e.attr("data-"+l,a[l].user+(a[l].text?":"+a[l].text:"")):a[l]&&e.attr("data-"+l,a[l]));$(f).attr({type:"text/javascript",src:"http://platform.twitter.com/widgets.js"}).appendTo(d)};b=$("<div/>").addClass("share");e=$.extend(!0,
{},{like:{action:"like",colorsheme:"light",font:null,href:null,layout:"standard",show_faces:!0,width:450},twitter:{count:"horizontal",related:{text:null,via:null},text:null,via:null,url:null},target:null},e);e.target&&b.appendTo(e.target);e.like&&a(e.like);e.twitter&&d(e.twitter);return b});
plura.obj(".layout.Table",function(e){var b,a,d=function(a){c();var d,f,l=[],k={};for(d in a[0])a[0].hasOwnProperty(d);for(d=0;d<a.length;d+=1)for(f in a[d])a[d].hasOwnProperty(f)&&(l[d]=l[d]||[],k[f]=k[f]||{rowspan:1},e&&e.merge&&0<d&&a[d][f]===a[d-1][f]&&("string"===typeof e.merge?(new RegExp(e.merge)).test(f):1)?(k[f].rowspan+=1,l[k[f].r][k[f].c].rowspan=k[f].rowspan):(k[f]={rowspan:1,r:d,c:l[d].length},l[d].push({value:a[d][f],span:k[f].rowspan})));var m,k=$("<table/>").appendTo(b);for(f=0;f<
l.length;f+=1)for(d=$("<tr/>").appendTo(k),a=0;a<l[f].length;a+=1)m=$("<td/>").appendTo(d).html(l[f][a].value||l[f][a]),l[f][a].rowspan&&1<l[f][a].rowspan&&m.prop({rowspan:l[f][a].rowspan})},c=function(){b.empty()};this.refresh=d;this.empty=c;a=$.extend(!0,{},{limit:0,merge:!0,target:null},e);this.core=b=$("<div/>").appendTo(a.target||"body").addClass("p-table "+(a.classes||""));a.data&&d(a.data);return this});
plura.obj(".media.Audio",function(e){var b,a,d,c,g,h,f=function(a){(c=void 0===a?!c:a)?b.find(".play").removeClass("active").html(d.labels.play):b.find(".play").addClass("active").html(d.labels.pause);g?g.pause(c):c||g||p()},l=function(c){var d=$("<div/>").attr({id:"plura_media_audio_"+a}).appendTo(b);c={content:c,id:a,obj:"plura.media.Audio",type:"audio"};swfobject.embedSWF(plura.constants.Paths.SWF,d.attr("id"),"0","0","10.0.0",null,c,null,null,m)},k=function(a){f(!c)},m=function(a){g=swfobject.getObjectById(a.id)},
n=function(a){for(var c in h.instances)h.instances.hasOwnProperty(c)&&!c.match("i"+a)&&h.instances[c].pause(!0)},p=function(){d.data?l(d.data):d.path&&$.get(d.path,function(a){console.log(a);l(a)})};this.fade=function(a){b.find(".menu").fadeIn("slow")};this.pause=f;h=plura.media.Audio;h.count=void 0===h.count?0:h.count+1;h.instances=h.instances||{};h.instances["i"+h.count]=this;h.pause=h.pause||n;a=h.count;d=$.extend(!0,{},{auto:!0,data:null,controls:!0,css:{flash:{position:"relative",height:0,width:0},
test:{position:"absolute",zIndex:1E3,width:400,height:400}},fade:!0,labels:{pause:"Pause",play:"Play"},path:null,params:null,target:"body",test:!1},e);(function(){b=$("<div/>").appendTo(d.target).addClass("p-audio").css({position:"relative"});var a=$("<ul/>").appendTo(b).addClass("menu controls");d.controls&&$("<li/>").appendTo(a).click(k).addClass("play");f(!d.auto)})();this.core=b});
plura.obj(".media.Video",function(e){var b,a,d=!0,c,g,h=this,f=function(a){c.empty();var b,d=a instanceof Array?a:[a],f;for(a=0;a<d.length;a+=1)b=d[a].src||d[a],f=d[a].type||"video/"+b.match(/\.([^.]+)$/)[1],$("<source/>").prop({src:b,type:f}).appendTo(c);return h},l=function(b){(d=void 0===b?!d:b)?(a.addClass("pause"),c[0].pause()):(a.removeClass("pause"),c[0].play())},k=function(a){void 0!==a&&(c[0].volume=a);return c[0].volume},m=function(a){a.stopImmediatePropagation();l()};this.pause=l;this.prop=
function(a){c.prop(a);return h};this.src=f;this.volume=k;b=new plura.net.Client;e=$.extend(!0,{},{autoplay:!0,controls:!0,pause:!0,preload:!0,loop:!0,wrap:!1},e);g={autoplay:e.autoplay,controls:e.controls,loop:e.loop,height:e.height,preload:e.preload,width:e.width,poster:e.poster};c=$("<video/>").prop(g).on("loadedmetadata",function(c){a.trigger("METADATA",{width:this.videoWidth,height:this.videoHeight})});a=e.wrap?$("boolean"===typeof e.wrap?"<div/>":e.wrap).append(c).addClass("video"):c;a.appendTo(e.target||
"body");e.src&&f(e.src);h.core=a;if(e.pause&&!e.controls||b.data.ios)c.on("click touchstart",m),e.wrap&&a.click(m);e.volume&&k(e.volume);b.data.ios||l(!e.autoplay);return this});
plura.obj(".net.Client",function(e){var b;b=navigator.userAgent;var a=!!b.match(/Android/i),d=!!b.match(/(explorer|MSIE)/i),c=!!b.match(/iPad/i),g=!!b.match(/iPhone/i),h=!!b.match(/iPod/i),g=g?"iPhone":c?"iPad":h?"iPod":null,f=null===document.location.href.match(/https?:\/\//),l=!!(g||a||b.match(/Windows.+Touch/i)),k=parseInt(navigator.appVersion,10);d&&(k=parseInt(navigator.appVersion.match(/msie ([0-9\.]+)/i)[1],10));b={agent:b,android:a,ie:d,ios:g,ipad:c,ipod:h,offline:f,touch:l,version:k};a=[];
c=e&&e.ie?e.ie:11;if(b.ie){if(a.push("ie","ie"+b.version),b.version<c)for(a.push("ie_lte"+b.version),d=b.version;d<c;d+=1)a.push("ie_lt"+(d+1))}else b.ios?a=a.concat(["ios",b.ios.toLowerCase()]):b.android&&a.push("android");b.offline&&a.push("offline");a.push((b.touch?"":"no-")+"touch");b.classes=a;this.data=b;e&&e.classes&&$("body").addClass(b.classes.join(" "))});
plura.obj(".net.URLManager",function(e){var b={analytics:!0,lang:!0,separator:"#"},a,d,c,g,h,f,l=function(a,c,b,d,f){window._gaq&&(a=["_trackEvent",a,c,b,d],void 0!==f&&!0===f&&a.push(f),_gaq.push(a))},k=function(c){var b=[];c&&a&&b.push(a);h&&b.push(h);return b.join("/")},m=function(a){void 0!==a&&a!==h&&(h=a,d.push(h));window.location.href="#!/"+k(!0);g.analytics&&(a="/"+k(!0),window._gaq&&_gaq.push(["_trackPageview",a]))};this._history=function(){return d};this._index=function(){return c};this._lang=
function(c){void 0!==c&&(a=c,m());return a};this._path=function(a){void 0!==a&&m(a);return h};this._root=function(){return f};this._url=function(){return f+"#!/"+k(!0)+"/"};this.event=function(){l.apply(null,arguments)};this.perma=function(a){return a.match(f+".*?([^=]*[^/])/?$")[1]};(function(){var l=window.location.href;g=$.extend(!0,{},b,e);d=[];c=0;f=l.match(/[^#]+/)[0];l.match(/#!\/(.+)/)&&(l=l.match(/#!\/(.+)/)[1].replace(/\/$/,"").split(/\//),g.lang&&l[0].match(/^[a-z]{2}$/)&&(a=l.shift()),
h=l.join("/"),d.push(h))})()});(function(){Object.defineProperties(plura.net.URLManager.prototype,{history:{get:function(){return this._history()}},index:{get:function(){return this._index()}},lang:{get:function(){return this._lang()},set:function(e){this._lang(e)}},path:{get:function(){return this._path()},set:function(e){this._path(e)}},root:{get:function(){return this._root()}},url:{get:function(){return this._url()}}})})();
plura.obj(".templates.alert.Slide",function(e){var b,a;this.refresh=function(d,c){clearTimeout(a);b.html(c).stop(!0,!0).slideDown().addClass(d?"success":"error").removeClass(d?"error":"success");a=setTimeout(function(){b.slideUp()},2E3)};b=$("<p/>").appendTo(e.target||"body").addClass("alert").hide()});
plura.obj(".templates.checkout.end.Form",function(e){var b;this._items=function(a){b.params={items:a}};e=$.extend(!0,{},{labels:{check:{email:{empty:"Please insert your email. Thank you!",invalid:"Your email address is invalid."},name:"Please insert your first and last name. Thank you!",message:"Please include a message. Thank you!"},fields:{email:"Email",name:"Name",message:"Message"}}},e);b=new plura.form.Form({check:[{id:"user_email",rules:[{alert:e.labels.check.email.empty},{exp:String(plura.constants.RegExp.EMAIL),
alert:e.labels.check.email.invalid}]},{id:"user_message",alert:e.labels.check.message},{id:"user_name",alert:e.labels.check.name}],fields:[[{name:"user_name",label:e.labels.fields.name},{name:"user_email",label:e.labels.fields.email},{name:"user_message",type:"textarea",label:e.labels.fields.message}]],params:$.extend({type:"checkout"},e.params),reset:!0,target:e.target});b.core.on("FORM_PROCESS_ERROR FORM_PROCESS_SUCCESS FORM_VALIDATION_ERROR",function(a,b){switch(a.type){case "FORM_PROCESS_ERROR":alert(b.alert);
break;case "FORM_PROCESS_SUCCESS":alert(b.alert);break;case "FORM_VALIDATION_ERROR":alert(b.alert)}}).addClass("big check-out");this.core=b.core});(function(){Object.defineProperties(plura.templates.checkout.end.Form.prototype,{items:{set:function(e){this._items(e)}}})})();
plura.obj(".templates.checkout.end.List",function(e){var b,a,d;this.refresh=function(a){var e,h,f,l=$("<ul/>").addClass("items");b.empty().append(l).prepend(d);for(e=0;e<a.length;e+=1){h=a[e];var k=$("<li/>").addClass("group");$("<span/>").text(h.name).addClass("group-label").appendTo(k);$("<ul/>").appendTo(k).addClass("group-items");h=k.appendTo(l);for(f in a[e].items)if(a[e].items.hasOwnProperty(f)){var k=a[e].items[f],m=$("<li/>").addClass("item item-"+k.data.ID),n=$("<ul/>").addClass("subitems").appendTo(m);
$("<li/>").addClass("icon").css("background-image","url("+k.data.img.dark+")").appendTo(n);$("<li/>").addClass("label").appendTo(n).html(k.data.title);m.appendTo(h)}}};a=$.extend(!0,{},{labels:{title:"List"}},e);b=$("<div/>").appendTo(e.target).addClass("list");d=$("<div/>").addClass("title").text(a.labels.title);this.core=b});(function(){Object.defineProperties(plura.templates.checkout.end.List.prototype,{items:{set:function(e){this.refresh(e)}}})})();
plura.obj(".templates.checkout.End",function(e){var b,a,d;this._items=function(c){void 0!==c&&(b.items=c,d.list&&(a.items=c))};d=$.extend(!0,{},{list:!0},e);e=$("<div/>").addClass("checkout-end");b=new plura.templates.checkout.end.Form({path:d.process,params:d.params,target:e});d.list&&(a=new plura.templates.checkout.end.List($.extend({target:e},d.list)));this.core=e;this.form=b;this.list=a});
(function(){Object.defineProperties(plura.templates.checkout.End.prototype,{items:{get:function(){return this._items()},set:function(e){this._items(e)}}})})();
plura.obj(".templates.Checkout",function(e){var b,a,d,c;d=$.extend(!0,{},{end:!0,labels:{sequence:{end:"Checkout"}}},e);b=$("<div/>").appendTo(e.target).addClass("checkout");c=new plura.templates.Sequence({items:function(){var c;d.end&&(a=new plura.templates.checkout.End(d.end),c=[{name:"end",label:d.labels.sequence.end,obj:a}]);return e.sequence?e.sequence.concat(c):c}(),parent:d.parent,target:b});c.core.on("CHANGE COMPLETE COMPLETE_ITEM EXIT",function(d,e){d.stopImmediatePropagation();switch(d.type){case "COMPLETE":var f,
l;if(1<c.items.length)for(l=[],f=0;f<c.items.length-1;f+=1)c.items[f].obj.cart&&l.push({name:c.items[f].name||"i"+f,items:c.items[f].obj.cart.items});a.items=l;break;case "EXIT":b.trigger("EXIT")}});this.core=b;this.sequence=c});
plura.obj(".templates.sequence.Breadcrumbs",function(e){var b,a,d,c,g=function(){b.trigger("PARENT")},h=function(a){b.trigger("SEQUENCE",$(a.target).data("index"))};this.refresh=function(a){var c,b;for(c=0;c<a.items.length;c+=1)b=[],d[c].off("click",h).removeClass("active completed disabled enabled"),a.items[c].completed||!c||c&&a.items[c-1].completed?(a.items[c].completed?b.push("completed"):b.push("enabled"),d[c].click(h)):b.push("disabled"),a.index===c&&b.push("active"),d[c].addClass(b.join(" "))};
a=$.extend(!0,{},{},e);b=$("<div/>").appendTo(a.target).addClass("breadcrumbs");(function(){var f;b.empty();d=[];a.parent&&$("<div/>").addClass("breadcrumbs-parent").text(a.parent).appendTo(b).click(g);c=$("<div/>").addClass("breadcrumbs-sequence-items").appendTo(b);for(f=0;f<a.items.length;f+=1)d[f]=$("<div/>").addClass("breadcrumbs-sequence-item breadcrumbs-sequence-item-"+f).text(a.items[f].label||f).data("index",f).appendTo(c)})();this.core=b});
plura.obj(".templates.sequence.PreviousNext",function(e){var b,a,d,c,g=function(a){a.stopImmediatePropagation();b.trigger("NEXT")},h=function(a){a.stopImmediatePropagation();b.trigger("PREVIOUS")},f=function(a){a.stopImmediatePropagation();b.trigger("PARENT")};this.refresh=function(a){c.off("click",h).off("click",f);d.off("click",g);if(!a.index&&e.parent||0<a.index)c.addClass("active").on("click",a.index?h:f);else c.removeClass("active");a.index<a.items.length-1&&a.items[a.index].completed?d.on("click",
g).addClass("active"):d.removeClass("active")};a=$.extend(!0,{},{},e);b=$("<div/>").appendTo(a.target).addClass("previous-next");d=$("<div/>").appendTo(b).addClass("previous-next-item next");c=$("<div/>").appendTo(b).addClass("previous-next-item previous");this.core=b});
plura.obj(".templates.Sequence",function(e){var b={chained:!0,navigation:{breadcrumbs:!0,previous_next:!0}},a,d,c,g,h,f,l,k,m,n=this,p=function(a){a!==c&&(g=c,c=a,q())},q=function(){var b;b=void 0===h[c].obj.completed||h[c].obj.completed;if(h[c].completed=b)a.trigger("COMPLETE_ITEM",{index:c}),c===h.length-1&&a.trigger("COMPLETE");else if(f.chained)for(b=c+1;b<h.length;b+=1){var d=b;h[d].completed=!1;"function"===typeof h[d].obj.reset&&h[d].obj.reset()}for(b=0;b<h.length;b+=1)d=[],h[b].obj.core.removeClass("active completed disabled enabled"),
h[b].completed||!b||b&&h[b-1].completed?void 0===h[b].obj.completed||h[b].obj.completed?d.push("completed"):d.push("enabled"):d.push("disabled"),c===b&&d.push("active"),h[b].obj.core.addClass(d.join(" "));void 0!==g&&a.removeClass("sequence-"+g);a.addClass("sequence-"+c);m&&m.refresh({index:c,items:h});k&&k.refresh({index:c,items:h})},t=function(c,b){c.stopImmediatePropagation();switch(c.type){case "PARENT":a.trigger("EXIT");break;case "SEQUENCE":p(b)}},r=function(b){b.stopImmediatePropagation();
switch(b.type){case "PARENT":a.trigger("EXIT");break;case "NEXT":p(c+1);break;case "PREVIOUS":p(c-1)}},v=function(a,c){a.stopImmediatePropagation();q(c)};this._items=function(){return h};(function(){f=$.extend(!0,{},b,e);a=$("<div/>").appendTo(f.target).addClass("sequence");if(f.navigation){l=$("<div/>").appendTo(a).addClass("sequence-nav");var c={target:l,items:f.items,parent:f.parent};f.navigation.breadcrumbs&&(k=new plura.templates.sequence.Breadcrumbs($.extend(!0,{},f.navigation.breadcrumbs,c)),
k.core.on("PARENT SEQUENCE",t));f.navigation.previous_next&&(m=new plura.templates.sequence.PreviousNext($.extend(!0,{},f.navigation.previous_next,c)),m.core.on("PARENT NEXT PREVIOUS",r))}var c=f.items,g;if(h){for(g=0;g<h.length;g+=1)h[g].obj.core.off("REFRESH",v).removeClass("completed");h=null}d&&d.remove();var x;d=$("<div/>").appendTo(a).addClass("sequence-items");h=[];for(g=0;g<c.length;g+=1)x=c[g].obj?c[g]:{obj:c[g]},h[g]=x,h[g].obj.core.appendTo(d).addClass("sequence-item").on("REFRESH",v);
p(0);n.core=a})()});(function(){Object.defineProperties(plura.templates.Sequence.prototype,{items:{get:function(){return this._items()}}})})();
plura.obj(".templates.structures.Content",function(e){var b,a,d,c=function(d,e){var k="string"===typeof d?h(d):d,m=void 0===e?!0:e;m&&(!m||b&&b[0]===k[0])||g(k,m);!m||b&&b[0]===k[0]||(b&&c(b,!1),b=k,a.trigger("REFRESH",k.data()))},g=function(a,c){!0===c?a.stop(!0).fadeIn().addClass("active"):a.stop(!0).fadeOut(function(){$(this).hide()}).removeClass("active")},h=function(c){c="object"===typeof c?c:{id:c};var b=[c.id,c.vanity||"",c.classes||""].join(" "),b=d[c.id]||$("<div/>").addClass("holder "+b).append(c.obj||
null).data(c).appendTo(a).hide();return d[c.id]=b};this.activate=c;this.disable=function(){b&&(c(b,!1),b=null)};this.get=h;e=$.extend(!0,{},{},e);a=$("<div/>").appendTo(e.target||"body").addClass(["content",e.classes||""].join(" "));d={};this.core=a;this.tree=d;return this});
plura.obj(".templates.structures.menu.MenuConverter",function(e){var b,a,d=function(b,e){var k,m,n,p,q,t,r;t=b.children("li");for(n=0;n<t.length;n+=1)q=t.eq(n),p=e?e+"_"+n:"i"+n,m={depth:p.split("_").length-1,id:p,label:q.children("a").html()},k=p+" node",r=q.children("a").click(h).addClass("trigger"),a[p]=q,q.children("ul").length?(r.click(c),d(q.children("ul"),p)):q.click(g),q.data(m).addClass(k)},c=function(a){b.trigger("_OPEN",$(a.currentTarget).parent())},g=function(a){b.trigger("_SELECT",$(a.currentTarget))},
h=function(a){a.preventDefault()};b=e.target.on("_OPEN _SELECT",e.handler);this.tree=a={};d(b)});
plura.obj(".templates.structures.Menu",function(e){var b,a,d,c,g=this,h=function(e,f){var g=void 0===f?!0:f;if(!g||b&&b[0]===e[0]){if(g)return;b=null}else b&&h(b,!1),b=e;var k="selected selected-"+e.data("id");g?(a.addClass(k),e.addClass("active")):(a.removeClass(k),e.removeClass("active"));var k=e.data("id").replace(/i(.+)/,"$1").split("_").slice(0,-1),l,m;if(k.length)for(l=0;l<k.length;l+=1)m="i"+k.slice(0,l?-l:k.length).join("_"),g?(0===l&&c[m].addClass("parent"),c[m].addClass("ancestor ancestor-"+
l)):g||(0===l&&c[m].removeClass("parent"),c[m].removeClass("ancestor ancestor-"+l));if(g){if(d.url){k=e.data();g=q(k);k=[k];l=[];g&&(k=g.concat(k));for(g=0;g<k.length;g+=1)l.push(k[g].vanity||k[g].id);url.path=l.join("/")}a.trigger("SELECT",e.data())}},f=function(b,e){var h,g,k=b.data("id").replace(/i(.+)/,"$1").split("_");if(void 0===e?!b.hasClass("open"):e){d.close&&a.find(".open").each(function(a){$(this).data("id").match(b.data("id"))||f($(this),!1)});for(h=0;h<k.length;h+=1)g="i"+k.slice(0,h?
-h:k.length).join("_"),c[g].addClass("open");a.trigger("OPEN",b.data())}else b.removeClass("open")},l=function(a){return d.leaf?d.leaf(a):a.children?!1:!0},k=function(a){return d.trigger?d.trigger(a):$("<a/>").prop({href:"#"}).html(a.label).click(function(a){a.preventDefault()})},m=function(b,e,f){var h,g,n,p;for(g=0;g<b.length;g+=1)n=f?f+"_"+g:"i"+g,p={data:b[g],depth:n.split("_").length-1,id:n,label:b[g].label||b[g].name||b[g].vanity||b[g].id||("string"===typeof b[g]?b[g]:n),vanity:b[g].id||b[g].vanity||
null},h=n+" node"+(p.vanity?" id-"+p.vanity:"")+(b[g][d.nodeID]?" id-"+b[g][d.nodeID]:""),h=$(d.tags.leaf||d.tags).appendTo(e).data(p).addClass(h),p=k(p).appendTo(h).addClass("trigger"),c[n]=h,l(b[g])?(h.click(w).addClass("leaf"),a.trigger("COMPLETE_ITEM",h.data())):(p.click(u),h=$(d.tags.branch||d.tags).appendTo(h).addClass("branch"),m(b[g].children,h,n))},n=function(b){a.empty();c={};g.tree=c;d.data=b;m(d.data,a);d.first&&r(d.first);a.trigger("COMPLETE")},p=function(a){var d;if(void 0===a||"boolean"===
typeof a){if(b)return b;for(d in c)if(c.hasOwnProperty(d)&&l(c[d].data("data")))return c[d]}else{if("string"===typeof a)return c[a];if("number"===typeof a)return c["i"+a]}},q=function(a){var b,d,e=a.id.split("_");if(1<e.length){b=[];for(a=1;a<e.length;a+=1)d=e.slice(0,a?-a:e.length).join("_"),b.push(c[d].data());b=b.reverse()}return b},t=function(b){var d=new plura.templates.structures.menu.MenuConverter({handler:v,target:b});a=b;c=d.tree;g.tree=c},r=function(a){a=p(a);h(a)},v=function(a,b){a.stopImmediatePropagation();
switch(a.type){case "_OPEN":f($(b));break;case "_SELECT":h($(b))}},u=function(a){f($(a.currentTarget).parent())},w=function(a){h($(this))};this.activate=h;this.ancestors=q;this.disable=function(){if(b){var c=b.data();h(b,!1);a.trigger("UNSELECT",c)}};this.get=p;this.refresh=n;this.select=r;d=$.extend(!0,{},{close:!0,data:null,first:!1,id:"",leaf:null,nodeID:"nodeID",object:null,tags:{branch:"<ul/>",leaf:"<li/>"},url:null},e);d.object?t(d.object):(a=$(d.tags.branch||d.tags).appendTo(d.target||"body"),
d.data&&n(d.data));g.core=a.addClass("menu "+d.id)});
plura.obj(".templates.structures.Tabs",function(e){var b,a,d,c,g=function(b){b=a.tree[b]?a.tree[b].data():"object"===typeof b?b:{id:b};return d.get({classes:h(b.id).join(" "),id:b.id,vanity:b.vanity})},h=function(a){var b=[],c=a.split("_").slice(0,-1);for(a=0;a<c.length;a+=1)b[a]=a?b.join("_")+"_"+c[a]:c[a].replace(/i/,"p");return b};this.disable=function(){a.disable();d.disable()};this.get=g;this.refresh=function(){a.refresh(c.tree)};this.select=function(b){a.select(b)};c=$.extend(!0,{},{first:!1,
delay:!1,id:null,menu:{},tree:null},e);b=$("<div/>").appendTo(c.target||"body").addClass("plura templates tabs core "+(c.id||""));a=new plura.templates.structures.Menu($.extend(!0,{},c.menu,{target:b,first:c.first}));a.core.on("COMPLETE COMPLETE_ITEM OPEN SELECT",function(a,c){a.stopPropagation();if("SELECT"===a.type){var e=g(c.id);d.activate(e)}b.trigger("MENU_"+a.type,c)});this.content=d=new plura.templates.structures.Content({target:b});this.core=b;this.menu=a;return this});
plura.obj(".utils.Cache",function(e){var b=(new Date).getTime();e+=e.match(/\?/)?e.match(/\&$/)?"":"&":"?";return e+b});plura.obj(".utils.Extend",function(e,b){function a(){}a.prototype=new e;b.prototype=new a;return b});
plura.obj(".utils.Flat",function(e,b,a){var d=[],c,g=b||{},h,f=plura.utils.Flat;for(c in e)if(e.hasOwnProperty(c))if(e[c]instanceof Array)for(b=0;b<e[c].length;b+=1)if("object"===typeof e[c][b]&&!(e[c][b]instanceof Array))d=d.concat(f(e[c][b],g,c));else{if("number"===typeof e[c][b]||"string"===typeof e[c][b])h=$.extend({},g),h[c]=e[c][b],d.push(h)}else"object"===typeof e[c]&&(g[a]=c,d=d.concat(f(e[c],g)));return d});
plura.obj(".utils.Hidden",function(e){var b=(new Date).getTime(),a=function(a){e.parents("body *").each(function(){$(this).is(":animated")||(!a&&void 0!==a||"none"!==$(this).css("display")?!1===a&&$(this).hasClass("i"+b)&&$(this).removeClass("i"+b).hide():$(this).addClass("i"+b).show())})};this.get=function(){a();var b={width:e.width(),height:e.height(),innerWidth:e.innerWidth(),innerHeight:e.innerHeight(),outerWidth:e.outerWidth(),outerHeight:e.outerHeight()};a(!1);return b};this.show=a});
plura.obj(".utils.Object",{path:function(e,b){var a,d=b.split("."),c=e;for(a=0;a<d.length;a+=1)if(void 0!==c[d[a]]){if(c=c[d[a]],a===d.length-1)return c}else return!1}});
plura.obj(".utils.String",{path:function(e,b){var a=[],d,c,g,h;d=function(a){a.match(/^https?:\/\//)||(a=window.location.href.replace(/[^\/]+$/,"")+a);return a};e=d(e);b=b?d(b):window.location.href;b.match(/^http/)&&(g=b.replace(/(https?:\/\/)(.+)(\/([^\/]+)?)$/g,"$1$2").split("/"));c=g.length;for(d=0;d<c;d+=1){if(e.match(g.join("/"))){h=e.replace(g.join("/"),"");break}g.splice(-1);a.push("..")}return a.length?a.join("/")+h:h.replace(/^\//,"")},test:function(e,b,a){var d,c,g=0;e=e instanceof Array?
e:[e];for(d=0;d<e.length;d+=1)c="string"===typeof e[d]?new RegExp(e[d].replace(/^(\/)(.*)(\/)$/,"$2")):e[d],c.test(b)&&(g+=1);return!g||a&&g<e.length?!1:!0}});
